---
title: "ShinyApps"
output: github_document
---

A collection of links to [Shiny apps](https://shinyapps.io)
that have been shared on Twitter.

## Table of Contents (alphabetically by app name)
+ [A](#a)
+ [B](#b)
+ [C](#c)
+ [D](#d)
+ [E](#e)
+ [F](#f)
+ [G](#g)
+ [H](#h)
+ [I](#i)
+ [J](#j)
+ [K](#k)
+ [L](#l)
+ [M](#m)
+ [N](#n)
+ [O](#o)
+ [P](#p)
+ [Q](#q)
+ [R](#r)
+ [S](#s)
+ [T](#t)
+ [U](#u)
+ [V](#v)
+ [W](#w)
+ [Y](#y)
+ [Z](#z)
+ [0](#0)
+ [1](#1)
+ [2](#2)
+ [3](#3)
+ [7](#7)

## A
+ [**AaltoAltmSince2007** by *ttso*](https://ttso.shinyapps.io/AaltoAltmSince2007): Some (alt)metric data for Aalto University articles published since 2007
+ [**aaltodimensions** by *ttso*](https://ttso.shinyapps.io/aaltodimensions): Citations and OA full text availability of Aalto University publications 2015-2017
+ [**aaltovirta** by *ttso*](https://ttso.shinyapps.io/aaltovirta): (Alt)metrics of Aalto University publications in VIRTA
+ [**ab-test-calculator-bayes** by *onlinedialogue*](https://onlinedialogue.shinyapps.io/ab-test-calculator-bayes): Having trouble explaining confidence levels to your colleagues and managers?
+ [**Abbreviator** by *sahelanth*](https://sahelanth.shinyapps.io/Abbreviator): Abbreviation List Maker
+ [**abs_census2016_incomes_visualisation** by *virusme*](https://virusme.shinyapps.io/abs_census2016_incomes_visualisation): ABS Census 2016
+ [**acciones** by *jesusyoel*](https://jesusyoel.shinyapps.io/acciones): MERCADO DE CAPITALES EN VENEZUELA
+ [**acsCounty** by *jasonajones73*](https://jasonajones73.shinyapps.io/acsCounty): Mapping ACS Data
+ [**ACSExplorer** by *brandonkopp*](https://brandonkopp.shinyapps.io/ACSExplorer): ACS Explorer
+ [**actionbutton** by *gallery*](https://gallery.shinyapps.io/actionbutton): actionButton example
+ [**activity-dashboard** by *winston*](https://winston.shinyapps.io/activity-dashboard): Activity tracker
+ [**ACTRInterference** by *engelmann*](https://engelmann.shinyapps.io/ACTRInterference): Similarity-based interference in sentence comprehension
+ [**acwc-2020-fantasy** by *etychang*](https://etychang.shinyapps.io/acwc-2020-fantasy): AC World Championship Fantasy Competition
+ [**AD_prediction** by *kanli*](https://kanli.shinyapps.io/AD_prediction): Dynamic Prediction of Future Health Outcomes and Risk of Alzheimer's Disease
+ [**adaptR** by *cjbattey*](https://cjbattey.shinyapps.io/adaptR): adaptR:
+ [**adavis** by *gokhan*](https://gokhan.shinyapps.io/adavis): adavis
+ [**adjacency_plot** by *mdlincoln*](https://mdlincoln.shinyapps.io/adjacency_plot): Adjacency matrices
+ [**admin** by *www*](https://www.shinyapps.io/admin): shinyapps.io
+ [**Administration_Departures** by *matthewmorriss*](https://matthewmorriss.shinyapps.io/Administration_Departures): Cabinent Agency Evolution
+ [**advancedr_jbook** by *teramonagi*](https://teramonagi.shinyapps.io/advancedr_jbook): Amazon Rank
+ [**advrquiz** by *hoxom*](https://hoxom.shinyapps.io/advrquiz): R言語徹底解説クイズ
+ [**AEMRExplorerShinyApp** by *johnyagecic*](https://johnyagecic.shinyapps.io/AEMRExplorerShinyApp): Wastewater Treatment Effluent Nutrient Explorer
+ [**afazali5** by *afazali*](https://afazali.shinyapps.io/afazali5): DIDAT
+ [**afheritability** by *afheritability*](https://afheritability.shinyapps.io/afheritability): The attributable fraction and the heritability
+ [**AFLW** by *petehaitch*](https://petehaitch.shinyapps.io/AFLW): AFLW Explorer
+ [**Afraus_app** by *afraus*](https://afraus.shinyapps.io/Afraus_app): Afraus
+ [**AgeGuesser** by *wangfan8*](https://wangfan8.shinyapps.io/AgeGuesser): Age_Guesser
+ [**AgeStructureShiny** by *johnyagecic*](https://johnyagecic.shinyapps.io/AgeStructureShiny): Input Variables
+ [**Ahput4** by *wyquek71*](https://wyquek71.shinyapps.io/Ahput4): Ahput 2.0
+ [**ai-banker** by *samitheberber*](https://samitheberber.shinyapps.io/ai-banker): AI-Banker
+ [**aircrash_** by *tianyigu*](https://tianyigu.shinyapps.io/aircrash_): Aircrash Insight
+ [**aircrashes** by *arthur*](https://arthur.shinyapps.io/aircrashes): Aviation data
+ [**AirportSecurity** by *davidruvolo*](https://davidruvolo.shinyapps.io/AirportSecurity): TSA Air Marshal Data
+ [**AirQuality-Data-Analysis-App-v11** by *manuelblancovalentin*](https://manuelblancovalentin.shinyapps.io/AirQuality-Data-Analysis-App-v11): AirQuality Data Analysis App v11.0
+ [**Alcohol_admissions** by *stevenlsenior*](https://stevenlsenior.shinyapps.io/Alcohol_admissions): Alcohol-Related Hospital Admissions
+ [**ALCS_Dashboard** by *cso-of-afghanistan*](https://cso-of-afghanistan.shinyapps.io/ALCS_Dashboard): The Afghanistan Living Conditions Survey
+ [**alex-course-project** by *alevashov*](https://alevashov.shinyapps.io/alex-course-project): Comparing Big 4 Australian banks tweets
+ [**algo_diversification** by *robotwealth*](https://robotwealth.shinyapps.io/algo_diversification): Algo Diversification
+ [**all-complications-should-count** by *grattan*](https://grattan.shinyapps.io/all-complications-should-count): Hospital complications calculator
+ [**AlleghenyCrashes** by *laurenrenaud*](https://laurenrenaud.shinyapps.io/AlleghenyCrashes): Allegheny County Crashes
+ [**alleleFrequencyApp** by *jamesware*](https://jamesware.shinyapps.io/alleleFrequencyApp): Frequency Filter
+ [**allsvenskan** by *erik-andreasson*](https://erik-andreasson.shinyapps.io/allsvenskan): Allsvenskan
+ [**alpha_variance** by *kk-gds*](https://kk-gds.shinyapps.io/alpha_variance): 降水量の一般化分散
+ [**alphasimrshiny** by *alphagenes*](https://alphagenes.shinyapps.io/alphasimrshiny): AlphaSimR
+ [**alternative_media_sources_in_afd-centered_facebook_discussions** by *bachl*](https://bachl.shinyapps.io/alternative_media_sources_in_afd-centered_facebook_discussions): Figures for "(Alternative) Media Sources in AfD-centered Facebook Discussions"
+ [**altm2015top100** by *ttso*](https://ttso.shinyapps.io/altm2015top100): Average metrics by country
+ [**altm2016top100** by *ttso*](https://ttso.shinyapps.io/altm2016top100): Average metrics by country
+ [**altmpolicy** by *ttso*](https://ttso.shinyapps.io/altmpolicy): Click to select items to table below. You can also zoom in/out
+ [**AMADA** by *cosmostatisticsinitiative*](https://cosmostatisticsinitiative.shinyapps.io/AMADA): AMADA Web User Interface (v0.2)
+ [**AmazingBirds** by *gatesd*](https://gatesd.shinyapps.io/AmazingBirds): 10 Amazing Birds
+ [**ames-explorer** by *gallery*](https://gallery.shinyapps.io/ames-explorer): Ames Housing Data Explorer
+ [**amphitheaterelevations** by *sfsheath*](https://sfsheath.shinyapps.io/amphitheaterelevations): Roman Amphitheaters
+ [**analisis-candidatos-diputado-2017** by *pdelboca*](https://pdelboca.shinyapps.io/analisis-candidatos-diputado-2017): Candidatos Córdoba 2017
+ [**andromeda_shock_bayesian** by *benjamin-andrew*](https://benjamin-andrew.shinyapps.io/andromeda_shock_bayesian): ANDROMEDA-SHOCK Bayesian Re-Analysis
+ [**Anova** by *drkhaled*](https://drkhaled.shinyapps.io/Anova): one-way ANOVA sample calculator by Khaled Alqahtani @alqahtani_khald
+ [**anova_shiny_rstudio** by *gallery*](https://gallery.shinyapps.io/anova_shiny_rstudio): Sums of squares in ANOVA
+ [**anscombe** by *thisisnic*](https://thisisnic.shinyapps.io/anscombe): Exploring Anscombe's Quartet
+ [**Anscombes-Quartet** by *mangothecat*](https://mangothecat.shinyapps.io/Anscombes-Quartet): About
+ [**ant_collective_decision** by *sjmgarnier*](https://sjmgarnier.shinyapps.io/ant_collective_decision): Collective food source selection in ants
+ [**APIM_MM** by *davidakenny*](https://davidakenny.shinyapps.io/APIM_MM): Actor-Partner Interdependence Model
+ [**APIM_SEM** by *larastas*](https://larastas.shinyapps.io/APIM_SEM): The Actor Partner Interdependence Model
+ [**APIMeM** by *davidakenny*](https://davidakenny.shinyapps.io/APIMeM): Actor-Partner Interdependence Mediation Model
+ [**APIMPowerR** by *robert-ackerman*](https://robert-ackerman.shinyapps.io/APIMPowerR): APIM Power
+ [**APIMPowerRdis** by *robert-a-ackerman*](https://robert-a-ackerman.shinyapps.io/APIMPowerRdis): Power Analysis for the Actor-Partner Interdependence Model
+ [**AplusB** by *graham-wheeler*](https://graham-wheeler.shinyapps.io/AplusB): AplusB: A + B design investigator for phase I dose-escalation studies
+ [**aportesprivados** by *ekonos*](https://ekonos.shinyapps.io/aportesprivados): Filtros
+ [**App-1** by *actuarialanddataanalytics*](https://actuarialanddataanalytics.shinyapps.io/App-1): Reserve(ML)
+ [**App-1** by *gabrielareto*](https://gabrielareto.shinyapps.io/App-1): Palette Extractor
+ [**App-1** by *jerryaoverton*](https://jerryaoverton.shinyapps.io/App-1): DXC's Business Model Simulator
+ [**App-1** by *murilofm*](https://murilofm.shinyapps.io/App-1): Ilhas de votação - Eleições de 2014 [2o turno]
+ [**App-FashionOnTwitter** by *powchow*](https://powchow.shinyapps.io/App-FashionOnTwitter): Fashion on Twitter
+ [**app-gui** by *zedoul*](https://zedoul.shinyapps.io/app-gui): Prototype: Gang of Four
+ [**app1** by *darrendahly*](https://darrendahly.shinyapps.io/app1): What % of females should I expect, given these differences in the 	 					 sex-specific normal distributions of techiness?
+ [**app_cellcycle** by *david-systemsforecasting*](https://david-systemsforecasting.shinyapps.io/app_cellcycle): CellCycler
+ [**app_HLL** by *rivm*](https://rivm.shinyapps.io/app_HLL): Prototype dashboard sensoren Hollandse Luchten
+ [**app_rentorbuyer** by *david-systemsforecasting*](https://david-systemsforecasting.shinyapps.io/app_rentorbuyer): RentOrBuyer
+ [**AppCC** by *pawelmatuszewski*](https://pawelmatuszewski.shinyapps.io/AppCC): Tematy
+ [**apple_watch_dashboard** by *raviolli77*](https://raviolli77.shinyapps.io/apple_watch_dashboard): Apple Watch Dashboard
+ [**application** by *mounabelaid*](https://mounabelaid.shinyapps.io/application): Mona's up 1: Create your wordcloud
+ [**AppOnline** by *colombian-schools-geodata*](https://colombian-schools-geodata.shinyapps.io/AppOnline): Station Lookup
+ [**AppPredPerf** by *gvinue*](https://gvinue.shinyapps.io/AppPredPerf): Forecasting basketball performance
+ [**appShiny** by *alvarobusot*](https://alvarobusot.shinyapps.io/appShiny): Body Mass Index (BMI), Body Fat Percentaje (BFP) and ideal weight
+ [**AppTypeIPower** by *vasishth*](https://vasishth.shinyapps.io/AppTypeIPower): Type I and Type II error in the Normal distribution
+ [**aqua-mapping-dashboard** by *sfg-ucsb*](https://sfg-ucsb.shinyapps.io/aqua-mapping-dashboard): Aquaculture Mapping Dashboard
+ [**aranoisy** by *jlgroup*](https://jlgroup.shinyapps.io/aranoisy): AraNoisy
+ [**arbrenadal** by *ubidi*](https://ubidi.shinyapps.io/arbrenadal): Configure your SIGNIFICANT christmas tree (beta v.1.0)
+ [**archidart** by *plantmodelling*](https://plantmodelling.shinyapps.io/archidart): archiDART
+ [**arewerepresented** by *wandernat*](https://wandernat.shinyapps.io/arewerepresented): Are We Represented?
+ [**ARPsimulator** by *jepusto*](https://jepusto.shinyapps.io/ARPsimulator): Alternating Renewal Process Simulator
+ [**arsef_hypocreales_mapping** by *lovettbr*](https://lovettbr.shinyapps.io/arsef_hypocreales_mapping): Geographical Distribution of ARSEF Hypocreales
+ [**arxiv_topicmodels** by *polyphant*](https://polyphant.shinyapps.io/arxiv_topicmodels): Topic Modelling astro-ph
+ [**asashootingapp_development** by *asashinyapps*](https://asashinyapps.shinyapps.io/asashootingapp_development): ASA Database
+ [**ascvd** by *sanjaybasu*](https://sanjaybasu.shinyapps.io/ascvd): ASCVD
+ [**askmusic** by *askmusic*](https://askmusic.shinyapps.io/askmusic): Understand the risk of prostate cancer
+ [**Assignment_Part1_files** by *a6111e*](https://a6111e.shinyapps.io/Assignment_Part1_files): Gross Domestic Product App
+ [**assist_networks** by *lbenz730*](https://lbenz730.shinyapps.io/assist_networks): College Basketball Assist Networks
+ [**Association_Categorical** by *istats*](https://istats.shinyapps.io/Association_Categorical): Association Categorical Variables
+ [**asymptotics** by *ukacz*](https://ukacz.shinyapps.io/asymptotics): asymptotics & the behavior of large sample sizes
+ [**atheist_rate** by *willgervais*](https://willgervais.shinyapps.io/atheist_rate): Direct and Indirect Atheist Prevalence Estimates
+ [**atlas_nacional** by *medea3*](https://medea3.shinyapps.io/atlas_nacional): Atlas Nacional de Mortalidad en España
+ [**ATP-Tennis-Player-Ranking-Forecast** by *bigtimestats*](https://bigtimestats.shinyapps.io/ATP-Tennis-Player-Ranking-Forecast): BigTimeStats Tennis
+ [**ATRmap** by *tree-ring*](https://tree-ring.shinyapps.io/ATRmap): Map of tree-ring labs
+ [**ausemploymentflows** by *timcameron*](https://timcameron.shinyapps.io/ausemploymentflows): Australian Monthly Employment Flows
+ [**AusGovInfo** by *marcuspaget*](https://marcuspaget.shinyapps.io/AusGovInfo): Disaster Events
+ [**Auswaertstor-Siegchancen** by *datakicks*](https://datakicks.shinyapps.io/Auswaertstor-Siegchancen): Siegchancen nach dem Hinspiel in der Champions- oder Europaleague
+ [**AutomatedForecastingWithShiny** by *pmaier1971*](https://pmaier1971.shinyapps.io/AutomatedForecastingWithShiny): Economic Dashboard
+ [**autosmry** by *bruce-meng*](https://bruce-meng.shinyapps.io/autosmry): autoSmry
+ [**AVbingo** by *hayle*](https://hayle.shinyapps.io/AVbingo): Animal Sound Bingo
+ [**avian_stochcrm** by *dmpstats*](https://dmpstats.shinyapps.io/avian_stochcrm): Avian Stochastic CRM

## B
+ [**B-VBGM** by *fishecology*](https://fishecology.shinyapps.io/B-VBGM): B-VBGM! Bayesian Von Bertalanffy Growth Model
+ [**baby_names_shiny_appy** by *ronammar*](https://ronammar.shinyapps.io/baby_names_shiny_appy): Popularity of baby names in the USA since 1880 (data from SSA )
+ [**babynames** by *justmarkham*](https://justmarkham.shinyapps.io/babynames): Baby Names by Birth Year
+ [**babynames-master** by *bsuthersan*](https://bsuthersan.shinyapps.io/babynames-master): Baby names
+ [**babypower** by *langcog*](https://langcog.shinyapps.io/babypower): Statistics and Power Analysis in Infancy Research
+ [**BabyPredictor** by *mikebirdgeneau*](https://mikebirdgeneau.shinyapps.io/BabyPredictor): Birdgeneau Baby Predictor
+ [**bachelorsPHD** by *d-miller*](https://d-miller.shinyapps.io/bachelorsPHD): Bachelor's -> PhD rates
+ [**BacktestVaR** by *cfrm*](https://cfrm.shinyapps.io/BacktestVaR): Value at Risk Backtest
+ [**bakkenExplorer** by *enfinexplorer*](https://enfinexplorer.shinyapps.io/bakkenExplorer): Bakken Explorer
+ [**BARDA_sepsis_study** by *lippincott*](https://lippincott.shinyapps.io/BARDA_sepsis_study): Sepsis among Medicare beneficiaries
+ [**barplotNonsense** by *stekhoven*](https://stekhoven.shinyapps.io/barplotNonsense): Why barplots are (often) nonsense
+ [**BaseballStats** by *malter61*](https://malter61.shinyapps.io/BaseballStats): Baseball Runs Potential Analysis by Mark Malter
+ [**basic** by *thomassiegmund*](https://thomassiegmund.shinyapps.io/basic): Basic usage of D3TableFilter in Shiny
+ [**Basic_Values** by *rudnev*](https://rudnev.shinyapps.io/Basic_Values): Basic values in Europe
+ [**basics-vis** by *fgeocomm*](https://fgeocomm.shinyapps.io/basics-vis): Data Visualization Basics
+ [**basicShiny** by *dreamrs-vic*](https://dreamrs-vic.shinyapps.io/basicShiny): Bienvenue dans l'application basic sur les R Addicts !
+ [**basicstats** by *jalapic*](https://jalapic.shinyapps.io/basicstats): Exploring Data
+ [**bayes** by *patrickbarks*](https://patrickbarks.shinyapps.io/bayes): Bayesian inference for a population mean
+ [**Bayes-App** by *ldberriz*](https://ldberriz.shinyapps.io/Bayes-App): Bayesian Clinical Diagnostic Model
+ [**BayesCalculator** by *ahalterman*](https://ahalterman.shinyapps.io/BayesCalculator): Getting to Donbass
+ [**bayesNeuro** by *sapsi*](https://sapsi.shinyapps.io/bayesNeuro): Estimativas para estudos caso-controle
+ [**bayesonline** by *matthewmatix*](https://matthewmatix.shinyapps.io/bayesonline): Easy Bayesian data analysis online
+ [**Beatles_Live_Perfomances** by *lebryant126*](https://lebryant126.shinyapps.io/Beatles_Live_Perfomances): The Beatles' Live Performances from August 1960 to August 1966
+ [**BECon** by *redgar598*](https://redgar598.shinyapps.io/BECon): BECon
+ [**Bees-Needs-App** by *cjschwantes*](https://cjschwantes.shinyapps.io/Bees-Needs-App): Bees Needs Interactive Data
+ [**bencana** by *bencanavis*](https://bencanavis.shinyapps.io/bencana): BencanaVis
+ [**bensinkalkulator** by *enerwe*](https://enerwe.shinyapps.io/bensinkalkulator): Bensinkalkulator
+ [**Beta61** by *tokyofoundation*](https://tokyofoundation.shinyapps.io/Beta61): 推計結果
+ [**beta_maker** by *blackfist*](https://blackfist.shinyapps.io/beta_maker): Beta Parameter getter
+ [**BeyondEPV** by *mvansmeden*](https://mvansmeden.shinyapps.io/BeyondEPV): This is a BETA version
+ [**bifor** by *aglhurley*](https://aglhurley.shinyapps.io/bifor): Birmingham Institute of Forest Research
+ [**billboard** by *reisanar*](https://reisanar.shinyapps.io/billboard): Songs from Billboard Top 100 List (1960 to 2015)
+ [**bioenergetics4** by *bioenergetics4*](https://bioenergetics4.shinyapps.io/bioenergetics4): R Fish Bioenergetics 4.0
+ [**biopsy_nomogram** by *canarypass*](https://canarypass.shinyapps.io/biopsy_nomogram): PASS Risk Calculator
+ [**Biostatistics_Review_Times** by *jhubiostatistics*](https://jhubiostatistics.shinyapps.io/Biostatistics_Review_Times): Biostatistics Review Times
+ [**bird_beauty_quiz** by *boecul*](https://boecul.shinyapps.io/bird_beauty_quiz): A couple quick questions before you start
+ [**bird_map** by *alex-baransky*](https://alex-baransky.shinyapps.io/bird_map): 2016 US Bird Range
+ [**bird_vocal_scaling** by *wilkins*](https://wilkins.shinyapps.io/bird_vocal_scaling): Bird Vocal Scaling
+ [**birdsong_beauty_quiz** by *boecul*](https://boecul.shinyapps.io/birdsong_beauty_quiz): A couple quick questions before you start
+ [**birthday_app** by *spholmes*](https://spholmes.shinyapps.io/birthday_app): Random Birthday Applet
+ [**black-white-life-expectancy** by *corinne-riddell*](https://corinne-riddell.shinyapps.io/black-white-life-expectancy): Explore the black-white life expectancy gap in the United States
+ [**blogimpact** by *wilkinsondi*](https://wilkinsondi.shinyapps.io/blogimpact): Blog Impact
+ [**BMOP** by *cawthron*](https://cawthron.shinyapps.io/BMOP): Blue Mussel Oversettlement
+ [**boardgame_reco** by *larrydag*](https://larrydag.shinyapps.io/boardgame_reco): Boardgame Recommendations
+ [**BoatRunExplorer** by *johnyagecic*](https://johnyagecic.shinyapps.io/BoatRunExplorer): DRBC Delaware Estuary Water Quality (Boat Run) Explorer
+ [**BookRecommendation** by *philippsp*](https://philippsp.shinyapps.io/BookRecommendation): Book Recommender
+ [**books** by *runzemc*](https://runzemc.shinyapps.io/books): Recommender for New York Times and NPR best-sellers, and Goodreads 'books that everyone should read at least once'
+ [**boot-perm-dash** by *mattkmiecik*](https://mattkmiecik.shinyapps.io/boot-perm-dash): Bootstrapping and Permutation Testing
+ [**bootci** by *istats*](https://istats.shinyapps.io/bootci): Bootstrap Confidence Interval for a Parameter from a Single Population
+ [**bootLRshiny** by *abfriedman*](https://abfriedman.shinyapps.io/bootLRshiny): Diagnostic test statistics from a 2x2 table
+ [**BoredPanda** by *rahulsinghania*](https://rahulsinghania.shinyapps.io/BoredPanda): Bored Panda
+ [**boston_police_incidents** by *vlandham*](https://vlandham.shinyapps.io/boston_police_incidents): Boston Police Incident Data
+ [**bostonsolar** by *tcb-analytics*](https://tcb-analytics.shinyapps.io/bostonsolar): Beantown Solar: The Future Never Looked So Bright
+ [**botornot** by *mikewk*](https://mikewk.shinyapps.io/botornot): {TweetBotOrNot}
+ [**Bots** by *itaysisso*](https://itaysisso.shinyapps.io/Bots): Making MTurk Great Again
+ [**boxplot** by *gallery*](https://gallery.shinyapps.io/boxplot): Boxplots & Histograms
+ [**brain_gene_expression** by *amckenz*](https://amckenz.shinyapps.io/brain_gene_expression): Brain cell gene expression data
+ [**BrewTourAnalytics** by *derekqiu*](https://derekqiu.shinyapps.io/BrewTourAnalytics): Brewery Explorer
+ [**BrownianMotion** by *abichat*](https://abichat.shinyapps.io/BrownianMotion): Simulation of Brownian Motion
+ [**brutalizeR** by *bfrickert*](https://bfrickert.shinyapps.io/brutalizeR): A Satanic Study of Time Series Variance
+ [**bs4DashDemo** by *dgranjon*](https://dgranjon.shinyapps.io/bs4DashDemo): bs4Dash Showcase
+ [**BTCmining** by *canaan*](https://canaan.shinyapps.io/BTCmining): Bitcoin Mining Profits
+ [**btshiny** by *dgabbe*](https://dgabbe.shinyapps.io/btshiny): Bicycle Tire Pressure Optimizer
+ [**bud1** by *econdata*](https://econdata.shinyapps.io/bud1): Budget of the United States Government
+ [**Build-A-Bayes** by *cidlab*](https://cidlab.shinyapps.io/Build-A-Bayes): Build-A-Bayes
+ [**building_ols_intuition** by *evangelinereynolds*](https://evangelinereynolds.shinyapps.io/building_ols_intuition): Minimize sum of squared residuals ('Manual OLS'):
+ [**bulmaExtension** by *dgranjon*](https://dgranjon.shinyapps.io/bulmaExtension): Inputs
+ [**BumpCharts** by *data-slinky*](https://data-slinky.shinyapps.io/BumpCharts): College Rankings Bump Charts
+ [**BurghsEyeView** by *pittsburghpa*](https://pittsburghpa.shinyapps.io/BurghsEyeView): Burgh's Eye View Points
+ [**BurghsEyeViewParcels** by *pittsburghpa*](https://pittsburghpa.shinyapps.io/BurghsEyeViewParcels): Burgh's Eye View Parcels
+ [**BurghsEyeViewTrees** by *pittsburghpa*](https://pittsburghpa.shinyapps.io/BurghsEyeViewTrees): Trees N'At
+ [**burn-hurt** by *johnson*](https://johnson.shinyapps.io/burn-hurt): 八仙塵爆分析
+ [**bus_simulator** by *marcus*](https://marcus.shinyapps.io/bus_simulator): Beat the Trend - The Domino Bus Group
+ [**Business_Dashboard** by *reacfintools*](https://reacfintools.shinyapps.io/Business_Dashboard): Business Dashboard
+ [**BWB_ontwikkeling_Japanse_fruivlieg** by *udenvh*](https://udenvh.shinyapps.io/BWB_ontwikkeling_Japanse_fruivlieg): Activiteit van de Japanse fruitvlieg

## C
+ [**CA_municipal_finance** by *tgwhite*](https://tgwhite.shinyapps.io/CA_municipal_finance): Municipal Finance in California
+ [**calculator** by *severetesting*](https://severetesting.shinyapps.io/calculator): Severe Testing
+ [**calculusofconsent** by *tarko*](https://tarko.shinyapps.io/calculusofconsent): Calculus of Consent
+ [**calendar_shinyio** by *phoebewong*](https://phoebewong.shinyapps.io/calendar_shinyio): Statistics of My Meetings
+ [**CaliforniaSchools** by *dmaust*](https://dmaust.shinyapps.io/CaliforniaSchools): California Schools
+ [**cambio-de-hora** by *pabrod*](https://pabrod.shinyapps.io/cambio-de-hora): ¿Cómo me afecta el cambio de hora?
+ [**cambridge** by *mikabr*](https://mikabr.shinyapps.io/cambridge): Cambridge Municipal Election 2017
+ [**CampaignPlanner** by *win-vector*](https://win-vector.shinyapps.io/CampaignPlanner): Response Driven Campaign Planner
+ [**cantaroazul** by *capitalsustentable*](https://capitalsustentable.shinyapps.io/cantaroazul): ¡Nos mudamos!
+ [**CanvasAccess** by *nercompshiny*](https://nercompshiny.shinyapps.io/CanvasAccess): Content Access Analytics
+ [**canyons-sci-landscape** by *canyons-research-mapping*](https://canyons-research-mapping.shinyapps.io/canyons-sci-landscape): Submarine Canyon Scientific Landscape
+ [**cap-region-housing** by *ukacz*](https://ukacz.shinyapps.io/cap-region-housing): Where Do Capital Region Homeowners Spend Their Housing Dollars? Hint: It's Not Where They Work
+ [**capstone** by *tomlous*](https://tomlous.shinyapps.io/capstone): KILOS™ Predictive Text
+ [**Capstone-Andina** by *dinnah88*](https://dinnah88.shinyapps.io/Capstone-Andina): Spotify 3 Decades
+ [**Capstone_Shiny_App** by *raheemiqbal1*](https://raheemiqbal1.shinyapps.io/Capstone_Shiny_App): Predict Next Word
+ [**Capstone_ShinyApp** by *jxieds*](https://jxieds.shinyapps.io/Capstone_ShinyApp): Capstone Shiny App: N-Gram Predictor (Release 1.0.0)
+ [**CapstoneApp2** by *joereads*](https://joereads.shinyapps.io/CapstoneApp2): Capstone APP for Coursera Data Science
+ [**Car2_App** by *bigcomputing*](https://bigcomputing.shinyapps.io/Car2_App): Motor Trend Cars data with rCharts
+ [**CarpeDiem** by *tberic*](https://tberic.shinyapps.io/CarpeDiem): Carpe Diem
+ [**CartePrenoms** by *floriangd*](https://floriangd.shinyapps.io/CartePrenoms): Carte des prénoms en France
+ [**carvis** by *sweiss*](https://sweiss.shinyapps.io/carvis): Car Sales
+ [**cast_spells** by *jhubiostatistics*](https://jhubiostatistics.shinyapps.io/cast_spells): Cast your spell!
+ [**castellsdenou** by *castellsdenou*](https://castellsdenou.shinyapps.io/castellsdenou): INTRODUCCIÓ
+ [**CausalExplorer** by *stevepowell*](https://stevepowell.shinyapps.io/CausalExplorer): The Wiggle Room
+ [**caviomorph_ecomorphology_resources_app** by *luisdva*](https://luisdva.shinyapps.io/caviomorph_ecomorphology_resources_app): Caviomorph Ecomorphology App
+ [**CaviR** by *watjoa*](https://watjoa.shinyapps.io/CaviR): CaviR statistics
+ [**cbcmatrix_app** by *calgaryzoolk*](https://calgaryzoolk.shinyapps.io/cbcmatrix_app): SPECCS
+ [**cbcrisk** by *cbc-predictor-utd*](https://cbc-predictor-utd.shinyapps.io/cbcrisk): CBCRisk: Contralateral Breast Cancer (CBC) Risk Predictor
+ [**CBCRisk** by *cbc-predictor-utd*](https://cbc-predictor-utd.shinyapps.io/CBCRisk): CBCRisk: Contralateral Breast Cancer (CBC) Risk Predictor
+ [**CC-App** by *ssifleet*](https://ssifleet.shinyapps.io/CC-App): Toxics and Climate Change
+ [**ccrs_2015-2016** by *ahmadmobin*](https://ahmadmobin.shinyapps.io/ccrs_2015-2016): The number of residents in residential care facilities submitting to CCRS by province/territory
+ [**CDCPlot** by *gallery*](https://gallery.shinyapps.io/CDCPlot): CDC Data Visualization
+ [**CDCPlot** by *michaud*](https://michaud.shinyapps.io/CDCPlot): CDC Data Visualization
+ [**cdfs** by *johnricco*](https://johnricco.shinyapps.io/cdfs): Cumulative distribution functions of rent per bedroom, by urban area
+ [**cdv_final2** by *kruse-alex*](https://kruse-alex.shinyapps.io/cdv_final2): Hamburger Schüler im Museum
+ [**cea_error** by *potterzot*](https://potterzot.shinyapps.io/cea_error): Linear fit to nonlinear data shows an effect for any cutoff date
+ [**CellView** by *mbolisetty*](https://mbolisetty.shinyapps.io/CellView): Single Cell Biology
+ [**census-app** by *sheffieldbeer*](https://sheffieldbeer.shinyapps.io/census-app): Sheffield Beer Census 2017
+ [**CensusVis** by *ardecarlo*](https://ardecarlo.shinyapps.io/CensusVis): Census Visualizer
+ [**center** by *gamma-trader*](https://gamma-trader.shinyapps.io/center): G.O. Volatility Center
+ [**centralLimitTheorem** by *casertamarco*](https://casertamarco.shinyapps.io/centralLimitTheorem): Exploring the Central Limit Theorem (CLT): The Age of Coins
+ [**CentralLimitTheorem** by *jssteele*](https://jssteele.shinyapps.io/CentralLimitTheorem): Central Limit Theorem
+ [**cfbRankings** by *tylerhunt*](https://tylerhunt.shinyapps.io/cfbRankings): Tyler Hunt's College Football Rankings
+ [**ch2sir** by *bjornstad*](https://bjornstad.shinyapps.io/ch2sir): The SIR model
+ [**ch5seir** by *bjornstad*](https://bjornstad.shinyapps.io/ch5seir): Seasonally forced SEIR
+ [**ch8orv** by *bjornstad*](https://bjornstad.shinyapps.io/ch8orv): ORV
+ [**chaos** by *automaths*](https://automaths.shinyapps.io/chaos): Jeu du chaos
+ [**cheatR** by *almogsi*](https://almogsi.shinyapps.io/cheatR): Gotta Catch 'em All
+ [**check_r_versions_of_package_dependencies** by *ateucher*](https://ateucher.shinyapps.io/check_r_versions_of_package_dependencies): Find appropriate versions of dependencies for your package
+ [**chicago_app** by *cchanial*](https://cchanial.shinyapps.io/chicago_app): Gentrification and Crime in the City of Chicago
+ [**chicagoSnowApp** by *helenhh*](https://helenhh.shinyapps.io/chicagoSnowApp): Historic Snow Fall Records in Chicago (1958-present)
+ [**chicken** by *salamonaska*](https://salamonaska.shinyapps.io/chicken): Poultry Market From Open Data
+ [**chicrime** by *miningchi2*](https://miningchi2.shinyapps.io/chicrime): MiningChi - Chicago Crime Data Visualization
+ [**ChinaMap** by *yichuanw*](https://yichuanw.shinyapps.io/ChinaMap): China Mapping Application
+ [**chinese-diplomacy-and-financing** by *gbwalker*](https://gbwalker.shinyapps.io/chinese-diplomacy-and-financing): Elite Chinese Diplomacy and Financial Flows
+ [**ChlamyNET** by *frannetworks*](https://frannetworks.shinyapps.io/ChlamyNET): ChlamyNET, a Chlamydomonas reinhardtii Gene Co-expression Network
+ [**choropleth** by *jcheng*](https://jcheng.shinyapps.io/choropleth): Choropleths with Shiny and Leaflet
+ [**choropleth3** by *jcheng*](https://jcheng.shinyapps.io/choropleth3): US Population Density
+ [**Choughs** by *fomshinyapps*](https://fomshinyapps.shinyapps.io/Choughs): +++ Choughs Typisierung +++
+ [**Christmas_Dinner_app** by *rpdearden*](https://rpdearden.shinyapps.io/Christmas_Dinner_app): Christmas Dinner Plan
+ [**citi-bike-data-with-rCharts** by *joejansen*](https://joejansen.shinyapps.io/citi-bike-data-with-rCharts): Citi Bike usage data
+ [**citibikeanalysis** by *jhonasttan*](https://jhonasttan.shinyapps.io/citibikeanalysis): NYC Citi Bike Data via REST API
+ [**cityapp** by *fitzlab*](https://fitzlab.shinyapps.io/cityapp): What will climate feel like in 60 years?
+ [**CL_und_EL_KO-Runden-Prognose** by *datakicks*](https://datakicks.shinyapps.io/CL_und_EL_KO-Runden-Prognose): Siegchancen nach dem Hinspiel in der Champions- oder Europaleague
+ [**classificationaccuracy** by *ajthurston*](https://ajthurston.shinyapps.io/classificationaccuracy): Classification Accuracy
+ [**client-data-and-query-string** by *gallery*](https://gallery.shinyapps.io/client-data-and-query-string): Client data and query string example
+ [**climate** by *mytinyshinys*](https://mytinyshinys.shinyapps.io/climate): Recent Earthquakes - Click on Circle for more data
+ [**climate** by *uo-geography*](https://uo-geography.shinyapps.io/climate): Climate and Water Balance Plotter
+ [**climate_displacement** by *adaptwest*](https://adaptwest.shinyapps.io/climate_displacement): Climate Displacement in Protected Areas
+ [**climate_partitioning_app** by *seedmapper*](https://seedmapper.shinyapps.io/climate_partitioning_app): Climate Partitioning App
+ [**ClinicalAccuracyAndUtility** by *micncltools*](https://micncltools.shinyapps.io/ClinicalAccuracyAndUtility): Introduction to the clinical accuracy and clinical utility of a diagnostic test
+ [**clippr** by *trestle*](https://trestle.shinyapps.io/clippr): Shiny Helper
+ [**CLT_mean** by *gallery*](https://gallery.shinyapps.io/CLT_mean): CLT for means
+ [**clusterfun** by *amandadobbyn*](https://amandadobbyn.shinyapps.io/clusterfun): Clusters in Beer
+ [**Coalescence** by *pyhatanja*](https://pyhatanja.shinyapps.io/Coalescence): Discrete time and coalescence
+ [**CoalescenceContinuous** by *pyhatanja*](https://pyhatanja.shinyapps.io/CoalescenceContinuous): Continuous time coalescence
+ [**coastal_sharks** by *fisheriesecology*](https://fisheriesecology.shinyapps.io/coastal_sharks): Tiburones pelagicos Galicia
+ [**coastlinetrip** by *ranlot*](https://ranlot.shinyapps.io/coastlinetrip): What's on the other side of the sea?
+ [**CoCSalaries** by *sgrim*](https://sgrim.shinyapps.io/CoCSalaries): City of Chicago Average Employee Salaries by Job or Department
+ [**Codogno** by *rmidura*](https://rmidura.shinyapps.io/Codogno): Ottavio Codogno's Postal Itinerary
+ [**cofunctional_app_18Q4** by *greenleaf*](https://greenleaf.shinyapps.io/cofunctional_app_18Q4): Co-functional network settings
+ [**cognitive_calculator** by *jonathan-underwood*](https://jonathan-underwood.shinyapps.io/cognitive_calculator): Cognitive impairment calculator
+ [**cognitive_impairment_comparison** by *jonathan-underwood*](https://jonathan-underwood.shinyapps.io/cognitive_impairment_comparison): Compare classification techniques for HIV-associated cognitive impairment
+ [**col2018_tend** by *nelsonamayad*](https://nelsonamayad.shinyapps.io/col2018_tend): Entrada: Tendencias presidenciales Colombia 2018
+ [**college_explorer-master** by *gallery*](https://gallery.shinyapps.io/college_explorer-master): Four-Year Not-for-Profit Colleges
+ [**college_insight** by *rich*](https://rich.shinyapps.io/college_insight): Data Table
+ [**collinearity** by *gallery*](https://gallery.shinyapps.io/collinearity): Multicollinearity in multiple regression
+ [**ColumbiaTaxiProject** by *tarashui*](https://tarashui.shinyapps.io/ColumbiaTaxiProject): When Columbia Students Leave the Bubble...
+ [**complexity_shiny** by *csqsiew*](https://csqsiew.shinyapps.io/complexity_shiny): Complex Forma Mentis
+ [**cond2sal_shiny** by *jsta*](https://jsta.shinyapps.io/cond2sal_shiny): Conductivity to Salinity Conversion
+ [**confidenceFallacy** by *richarddmorey*](https://richarddmorey.shinyapps.io/confidenceFallacy): The lost submarine
+ [**ConfirmationBias-News-BeliefPolarization** by *amohseni*](https://amohseni.shinyapps.io/ConfirmationBias-News-BeliefPolarization): Reporting, Bias, and Belief Distortion
+ [**consumer_price_index** by *kunov*](https://kunov.shinyapps.io/consumer_price_index): CPI Dashboard
+ [**contingencyTables** by *richarddmorey*](https://richarddmorey.shinyapps.io/contingencyTables): Contingency tables
+ [**ContiuousInteractions** by *jssteele*](https://jssteele.shinyapps.io/ContiuousInteractions): Continuous By Continuous Interactions
+ [**contributions** by *rkahne*](https://rkahne.shinyapps.io/contributions): Contributions Dashboards
+ [**contributr** by *ropensci*](https://ropensci.shinyapps.io/contributr): contributr 🌻
+ [**ConversionStratification** by *tanaka-group-imperial*](https://tanaka-group-imperial.shinyapps.io/ConversionStratification): Value-wise conversion
+ [**cooking-drake-tutorial** by *krlmlr*](https://krlmlr.shinyapps.io/cooking-drake-tutorial): Exercises: Cooking with drake
+ [**Cor2** by *ytake2*](https://ytake2.shinyapps.io/Cor2): CORRELATION
+ [**coronavirus** by *loanrobinson*](https://loanrobinson.shinyapps.io/coronavirus): CoronaVirus
+ [**correlacion** by *juliomulero*](https://juliomulero.shinyapps.io/correlacion): Relación lineal entre dos variables cuantitativas
+ [**correlation_game** by *gallery*](https://gallery.shinyapps.io/correlation_game): Correlation Game
+ [**cos_registered_reports** by *katiedrax*](https://katiedrax.shinyapps.io/cos_registered_reports): Comparison of Registered Reports (RRs)
+ [**cosinor-shinyapp** by *sachsmc*](https://sachsmc.shinyapps.io/cosinor-shinyapp): Cosinor analysis
+ [**Cost-of-Commute** by *discoursemedia*](https://discoursemedia.shinyapps.io/Cost-of-Commute): Calculate the full cost of your commute
+ [**CostofCommute** by *discoursemedia*](https://discoursemedia.shinyapps.io/CostofCommute): Calculate the full cost of your commute
+ [**costresistantecoli** by *aushsi*](https://aushsi.shinyapps.io/costresistantecoli): ResImpact- tracking drug resistance for action
+ [**COTDataIntelligenceTool** by *leohermoso*](https://leohermoso.shinyapps.io/COTDataIntelligenceTool): COT Data Intelligence Tool
+ [**counties** by *knjogu2015*](https://knjogu2015.shinyapps.io/counties): Kenya Counties: Data Visualization Dashboards and Maps: Data Sources, KNBS and CIDPs
+ [**counties** by *lenalyticslab*](https://lenalyticslab.shinyapps.io/counties): Visualize Ward Data
+ [**county_data_dashboard_v2** by *markbergen-shiny*](https://markbergen-shiny.shinyapps.io/county_data_dashboard_v2): U.S. County Data Center
+ [**CountyHealthApp** by *juliasilge*](https://juliasilge.shinyapps.io/CountyHealthApp): Health Indicators in Utah Counties
+ [**course_project** by *cmstewart*](https://cmstewart.shinyapps.io/course_project): Ten-Item Personality Inventory
+ [**CourseProject** by *tom-courtney*](https://tom-courtney.shinyapps.io/CourseProject): Gear Grinding - Machine Learning App
+ [**coursera** by *couchpsycho*](https://couchpsycho.shinyapps.io/coursera): Evaluation of the Results of an AB-Test
+ [**coursera_capstone** by *luislundquist*](https://luislundquist.shinyapps.io/coursera_capstone): SwiftKey Capstone
+ [**coursera_nlp_capstone** by *bengapple*](https://bengapple.shinyapps.io/coursera_nlp_capstone): Coursera NLP Capstone
+ [**covariance** by *sarahromanes*](https://sarahromanes.shinyapps.io/covariance): Visualising Covariance Matrices
+ [**COVID-19** by *bleedrake*](https://bleedrake.shinyapps.io/COVID-19): COVID-19 Estimates
+ [**cran-downloads** by *hadley*](https://hadley.shinyapps.io/cran-downloads): CRAN downloads
+ [**crandash** by *jcheng*](https://jcheng.shinyapps.io/crandash): Popularity by package (last 5 min)
+ [**cranview** by *dgrtwo*](https://dgrtwo.shinyapps.io/cranview): Package Downloads Over Time
+ [**CrashFatalities** by *nraley*](https://nraley.shinyapps.io/CrashFatalities): Car Crashes in Allegheny County (2004-2016)
+ [**cricket** by *jalapic*](https://jalapic.shinyapps.io/cricket): Test match batting
+ [**cricket** by *mytinyshinys*](https://mytinyshinys.shinyapps.io/cricket): CricInfo Image
+ [**Cricket_Visualisation** by *oste434*](https://oste434.shinyapps.io/Cricket_Visualisation): Getting your eye in
+ [**crime_explorer** by *algospark*](https://algospark.shinyapps.io/crime_explorer): Crime Explorer
+ [**crime_pred** by *ilssc*](https://ilssc.shinyapps.io/crime_pred): Predicted Crime Rates
+ [**crimemap** by *blenditbayes*](https://blenditbayes.shinyapps.io/crimemap): Crime Data Visualisation
+ [**crimeVis** by *dnaeye*](https://dnaeye.shinyapps.io/crimeVis): Violent Crime Rates by U.S. State
+ [**crossedpower** by *jakewestfall*](https://jakewestfall.shinyapps.io/crossedpower): Power Analysis with Crossed Random Effects
+ [**crypto** by *marcelo-ventura*](https://marcelo-ventura.shinyapps.io/crypto): Live webscrapper from coinmarketcap.com
+ [**Crypto_Prices** by *andrewrmcneil*](https://andrewrmcneil.shinyapps.io/Crypto_Prices): Cryptocurrency prices
+ [**cryptoapp** by *acm9q*](https://acm9q.shinyapps.io/cryptoapp): Frequency Decryption: A Broken Algorithm
+ [**cryptocurr** by *casimir*](https://casimir.shinyapps.io/cryptocurr): CryptoCurrency Explorer
+ [**ctmmweb** by *ctmm*](https://ctmm.shinyapps.io/ctmmweb): ctmmweb
+ [**ctsu** by *pdrhiggins*](https://pdrhiggins.shinyapps.io/ctsu): Converting CTSU Files to Summary Reports
+ [**Cultures-of-Knowledge_whole-network** by *livedataoxford*](https://livedataoxford.shinyapps.io/Cultures-of-Knowledge_whole-network): Visualizations of the Prosopographical Network of Samuel Hartlib
+ [**Curva_OC** by *arantegui*](https://arantegui.shinyapps.io/Curva_OC): Curva OC
+ [**custodiesel** by *claudiolucinda*](https://claudiolucinda.shinyapps.io/custodiesel): Quanto vai custar o desconto do Diesel?
+ [**custom-input-bindings** by *gallery*](https://gallery.shinyapps.io/custom-input-bindings): Custom input example
+ [**cvdnight1** by *tladeras*](https://tladeras.shinyapps.io/cvdnight1): cvdRisk Data
+ [**cws-d1** by *meysubb*](https://meysubb.shinyapps.io/cws-d1): CWS 2019
+ [**cycleMelbourne** by *willhl*](https://willhl.shinyapps.io/cycleMelbourne): Melbourne Bicycle Paths

## D
+ [**d3piechart** by *alanwilliams*](https://alanwilliams.shinyapps.io/d3piechart): R Shiny with D3
+ [**dallas-police** by *trestletech*](https://trestletech.shinyapps.io/dallas-police): Real-time Dallas Police Calls
+ [**dance_a** by *ou-statswidgets*](https://ou-statswidgets.shinyapps.io/dance_a): A simulation of p values and confidence intervals for t-tests
+ [**DARKO** by *apanalytics*](https://apanalytics.shinyapps.io/DARKO): DARKO Exploration
+ [**darts** by *chringer-apps*](https://chringer-apps.shinyapps.io/darts): Simulate Cricket
+ [**dash** by *gabrielmutua*](https://gabrielmutua.shinyapps.io/dash): WHO TB Burden Dashboard
+ [**dash** by *winston*](https://winston.shinyapps.io/dash): Support Team 5 mins
+ [**dashboard** by *levv-logic*](https://levv-logic.shinyapps.io/dashboard): LEVV-LOGIC Best Practices
+ [**dashboard** by *mytinyshinys*](https://mytinyshinys.shinyapps.io/dashboard): myTinyShinys
+ [**dashboard_ecomix** by *dreamrs-vic*](https://dreamrs-vic.shinyapps.io/dashboard_ecomix): Production d'électricité journalière
+ [**dashboard_elec** by *dreamrs*](https://dreamrs.shinyapps.io/dashboard_elec): Electricity dashboard French electricity production and consumption (via RTE)
+ [**dashboard_v1** by *btb-statistics*](https://btb-statistics.shinyapps.io/dashboard_v1): Bovine TB stats Dashboard
+ [**dashEleicao2018** by *marceloalvesuff*](https://marceloalvesuff.shinyapps.io/dashEleicao2018): Eleição de 2018
+ [**Data-Summariser** by *adhokshaja*](https://adhokshaja.shinyapps.io/Data-Summariser): Welcome to the Data Summarizer
+ [**data_explorer_adult** by *ubdc-apps*](https://ubdc-apps.shinyapps.io/data_explorer_adult): Data Explorer
+ [**datacollect** by *debruine*](https://debruine.shinyapps.io/datacollect): Data Collection & Feedback
+ [**dataExplorer** by *ndslds*](https://ndslds.shinyapps.io/dataExplorer): North Dakota SLDS Data Explorer
+ [**datafest-map-all-years** by *gallery*](https://gallery.shinyapps.io/datafest-map-all-years): ASA DataFest over the years
+ [**DataProduct** by *mkarp94*](https://mkarp94.shinyapps.io/DataProduct): The Stanley Cup Difference
+ [**DataProduct** by *wugology*](https://wugology.shinyapps.io/DataProduct): How long does a PhD really take in the United States?
+ [**dataproducts** by *jsramos*](https://jsramos.shinyapps.io/dataproducts): Videogames ratings in Metacritic for top 100 of all time
+ [**dataproducts-titanic** by *thiemom*](https://thiemom.shinyapps.io/dataproducts-titanic): Titanic: machine learning from disaster ... a Shiny App
+ [**dataR** by *rain1024*](https://rain1024.shinyapps.io/dataR): dataR
+ [**dataset_sharing** by *shao-shuai*](https://shao-shuai.shinyapps.io/dataset_sharing): Downloading Data
+ [**dataton17_m30int** by *muranga*](https://muranga.shinyapps.io/dataton17_m30int): M30 - Gestión Inteligente del Tráfico
+ [**dataviz** by *dynamicrna*](https://dynamicrna.shinyapps.io/dataviz): RNA-seq and SILAC proteomics of DUX4-expressing cells
+ [**DataViz** by *fveronesi*](https://fveronesi.shinyapps.io/DataViz): DataViz
+ [**David-Score** by *amiyaal*](https://amiyaal.shinyapps.io/David-Score): David's Score calculator. Created by Amiyaal Ilany
+ [**DavidBowieSingles** by *chartmkr*](https://chartmkr.shinyapps.io/DavidBowieSingles): Popularity of David Bowie Singles (1966-2015)
+ [**dBETS** by *dbets*](https://dbets.shinyapps.io/dBETS): dBETS - diffusion Breakpoint Estimation Testing Software
+ [**ddcreator** by *debruine*](https://debruine.shinyapps.io/ddcreator): DDConvertor
+ [**ddp-project** by *herchu*](https://herchu.shinyapps.io/ddp-project): Psychiatric beds in European Hospitals
+ [**DDP_app** by *floren*](https://floren.shinyapps.io/DDP_app): Plotting a Random Normal Distribution
+ [**ddp_noaa** by *chanamasa*](https://chanamasa.shinyapps.io/ddp_noaa): Weather Event Analysis
+ [**DDP_project** by *amirrudin*](https://amirrudin.shinyapps.io/DDP_project): MOOC DDP Project
+ [**ddp_project** by *ghostdatalearner*](https://ghostdatalearner.shinyapps.io/ddp_project): Unemployent evolution in Spain 2005-2014
+ [**deathandco** by *k-doyle*](https://k-doyle.shinyapps.io/deathandco): Another Death & Co. Index
+ [**Deaths** by *drugtrends*](https://drugtrends.shinyapps.io/Deaths): Deaths induced by:
+ [**decision_mining_app** by *johnakwei1*](https://johnakwei1.shinyapps.io/decision_mining_app): Decision Mining App
+ [**deletefacebook** by *jheppler*](https://jheppler.shinyapps.io/deletefacebook): Social data analysis
+ [**DEMENT** by *lbnlshiny*](https://lbnlshiny.shinyapps.io/DEMENT): carbon usage efficiency (CUE)
+ [**demetR** by *pop-eco*](https://pop-eco.shinyapps.io/demetR): demetR
+ [**democrats** by *timphan*](https://timphan.shinyapps.io/democrats): 2016 Democratic Primary Election Analysis
+ [**destination_probability** by *nyctaxi*](https://nyctaxi.shinyapps.io/destination_probability): Where Do People Go?
+ [**devdatapdt** by *dnafrance*](https://dnafrance.shinyapps.io/devdatapdt): Simple Interest Calculator
+ [**devdataprod** by *adornes*](https://adornes.shinyapps.io/devdataprod): Analysis of Violent Crime Rates by US State
+ [**devdataprod-005** by *icarda*](https://icarda.shinyapps.io/devdataprod-005): Motor Trend Car Road Tests
+ [**devdataprod-016** by *chribonn*](https://chribonn.shinyapps.io/devdataprod-016): Maltese Tourist Analysis for 2012
+ [**DevDataProduct** by *amyjiangsu*](https://amyjiangsu.shinyapps.io/DevDataProduct): Swear Word Analysis using Google NGram Data
+ [**DevDataProject** by *jcllorente*](https://jcllorente.shinyapps.io/DevDataProject): Exercise with Iris dataset
+ [**developer-talent-map** by *brookfieldiie*](https://brookfieldiie.shinyapps.io/developer-talent-map): Developer Talent Map - StackOverflow + BII+E
+ [**Developing-Data-Products-Course-Project** by *jplcva*](https://jplcva.shinyapps.io/Developing-Data-Products-Course-Project): Random Distributions
+ [**developingdataproductsclass** by *oszkar*](https://oszkar.shinyapps.io/developingdataproductsclass): Movie charts
+ [**diagprimer** by *crsu*](https://crsu.shinyapps.io/diagprimer): Quantifying Diagnostic Test Accuracy: An Interactive Primer (v1.0)
+ [**dialect_map_shiny_project** by *supstat*](https://supstat.shinyapps.io/dialect_map_shiny_project): Hack Session: Maps in R
+ [**diet** by *megumi-oshima*](https://megumi-oshima.shinyapps.io/diet): Diet Database
+ [**DiNAR** by *nib-si*](https://nib-si.shinyapps.io/DiNAR): DiNAR
+ [**Dingy** by *davidakenny*](https://davidakenny.shinyapps.io/Dingy): Tests of Distinguishability and Nonindependence
+ [**directory** by *jordanbutz*](https://jordanbutz.shinyapps.io/directory): Predicting Risk of Opioid Overdoses in Providence, Rhode Island
+ [**dis-elect-app** by *datalabgh*](https://datalabgh.shinyapps.io/dis-elect-app): Regional district-level elections in Ghana since 1988...
+ [**Disability** by *statisticsnz*](https://statisticsnz.shinyapps.io/Disability): Disability Estimates
+ [**Discretisator** by *archeomatic*](https://archeomatic.shinyapps.io/Discretisator): Discretisator
+ [**DiseaseDynamics** by *mkiang*](https://mkiang.shinyapps.io/DiseaseDynamics): Basic ODE Models of Disease Dynamics
+ [**disruption** by *apanalytics*](https://apanalytics.shinyapps.io/disruption): Defensive Metrics
+ [**dissemination** by *erasmusmcmgz*](https://erasmusmcmgz.shinyapps.io/dissemination): Health and economic impact of meeting the WHO targets
+ [**dist_calc** by *gallery*](https://gallery.shinyapps.io/dist_calc): Distribution Calculator
+ [**Distribucion_nodos_wrdtrade** by *diegokoz*](https://diegokoz.shinyapps.io/Distribucion_nodos_wrdtrade): Distribución de centralidad de los nodos
+ [**distribution-zoo** by *ben18785*](https://ben18785.shinyapps.io/distribution-zoo): The distribution zoo
+ [**distributionexplorer** by *parameterlibrary*](https://parameterlibrary.shinyapps.io/distributionexplorer): Aquatic ecosystem modelling parameter library v0.7
+ [**Distributions** by *rsangole*](https://rsangole.shinyapps.io/Distributions): Poisson Distribution
+ [**diversidade_eleicoes** by *faz-diferenca-br*](https://faz-diferenca-br.shinyapps.io/diversidade_eleicoes): Faz Diferença
+ [**diveRsity-online** by *popgen*](https://popgen.shinyapps.io/diveRsity-online): diveRsity Online
+ [**divida_web** by *gabrielrega*](https://gabrielrega.shinyapps.io/divida_web): Equilibrando a dívida pública
+ [**divMigrate-online** by *popgen*](https://popgen.shinyapps.io/divMigrate-online): divMigrate-online: Visualise and test gene flow patterns among populations
+ [**DK_App** by *jmaburto*](https://jmaburto.shinyapps.io/DK_App): Lifespan inequality in Denmark, Sweden and Norway
+ [**DND_Dice_Roll** by *aglhurley*](https://aglhurley.shinyapps.io/DND_Dice_Roll): Dungeons and Dragons Dice Roller
+ [**dpmixapp** by *stablemarkets*](https://stablemarkets.shinyapps.io/dpmixapp): Interactive Dirichlet Process Tutorial
+ [**dproduct** by *amice13*](https://amice13.shinyapps.io/dproduct): Results of the Ukrainian presidential elections in 2014
+ [**drarbitrage** by *kczat*](https://kczat.shinyapps.io/drarbitrage): Dynasty / Redraft Arbitrage App
+ [**drawadist** by *nstrayer*](https://nstrayer.shinyapps.io/drawadist): Draw your (beta) prior
+ [**drawyourprior** by *jhubiostatistics*](https://jhubiostatistics.shinyapps.io/drawyourprior): Draw your (beta) prior
+ [**driftR** by *cjbattey*](https://cjbattey.shinyapps.io/driftR): driftR: Population Genetic Simulations in R
+ [**drinkr** by *gallery*](https://gallery.shinyapps.io/drinkr): drinkR: Estimate your Blood Alcohol Concentration (BAC)
+ [**drinkr** by *rasmusab*](https://rasmusab.shinyapps.io/drinkr): drinkR: Estimate your Blood Alcohol Concentration (BAC)
+ [**drive** by *oncologynibr*](https://oncologynibr.shinyapps.io/drive): DRIVE DATA PORTAL
+ [**drought_prediction** by *frzambra*](https://frzambra.shinyapps.io/drought_prediction): Series Temporales NDVI acumulado Temporada Agrícola
+ [**dsc-shiny** by *yxtay*](https://yxtay.shinyapps.io/dsc-shiny): Data Science Capstone Project
+ [**DT-filter** by *yihui*](https://yihui.shinyapps.io/DT-filter): Column Filters on the Server Side
+ [**DT-info** by *yihui*](https://yihui.shinyapps.io/DT-info): DataTables Information
+ [**DT-proxy** by *yihui*](https://yihui.shinyapps.io/DT-proxy): Manipulate an Existing Table
+ [**DT-rows** by *yihui*](https://yihui.shinyapps.io/DT-rows): Select Table Rows
+ [**DT-scroller** by *yihui*](https://yihui.shinyapps.io/DT-scroller): Using the Scroller Extension in DataTables
+ [**dta_ma** by *crsu*](https://crsu.shinyapps.io/dta_ma): MetaDTA: Diagnostic Test Accuracy Meta-analysis
+ [**DualProcessROC** by *maureen*](https://maureen.shinyapps.io/DualProcessROC): Dual Process ROC Demo
+ [**dummy_example** by *yrochat*](https://yrochat.shinyapps.io/dummy_example): Manipulating thresholds
+ [**DVHshiny** by *dwoll*](https://dwoll.shinyapps.io/DVHshiny): About DVHmetrics
+ [**Dynamic_Probabilities** by *webapptester*](https://webapptester.shinyapps.io/Dynamic_Probabilities): Dynamic Probabilities
+ [**DynamicUI** by *upsa*](https://upsa.shinyapps.io/DynamicUI): upsa - Uncertainty Propagation & Sensitivity Analysis

## E
+ [**e-coli-beach-predictions** by *rchesak*](https://rchesak.shinyapps.io/e-coli-beach-predictions): City of Chicago Beaches
+ [**e-value-calculator** by *corinne-riddell*](https://corinne-riddell.shinyapps.io/e-value-calculator): E-value calculator for sensitivity analysis in observational studies
+ [**eapmap** by *irtdemo*](https://irtdemo.shinyapps.io/eapmap): eapmap
+ [**eBirdmass** by *slager*](https://slager.shinyapps.io/eBirdmass): eBird Biomass Calculator
+ [**Ebola-Dynamic** by *gallery*](https://gallery.shinyapps.io/Ebola-Dynamic): Ebola Model
+ [**Ebola-Dynamic-Model** by *econometricsbysimulation*](https://econometricsbysimulation.shinyapps.io/Ebola-Dynamic-Model): Ebola Model
+ [**Ebola_Sim** by *mile*](https://mile.shinyapps.io/Ebola_Sim): Which Chimpanzees Should be Vaccinated?
+ [**ec_atlas** by *endotheliomics*](https://endotheliomics.shinyapps.io/ec_atlas): EC Atlas
+ [**ECAD-data-browser** by *mdefelice*](https://mdefelice.shinyapps.io/ECAD-data-browser): European Climate Assessment & Dataset (ECA&D) stations data browser
+ [**ecocastapp** by *heatherwelch*](https://heatherwelch.shinyapps.io/ecocastapp): EcoCast Explorer
+ [**EconSeminarDiversity** by *econseminardiversity*](https://econseminardiversity.shinyapps.io/EconSeminarDiversity): Econ Seminar Diversity
+ [**EconSpeakerDiversity** by *econspeakerdiversity*](https://econspeakerdiversity.shinyapps.io/EconSpeakerDiversity): Diversifying Economics Seminars - Speakers List
+ [**EctoMAP** by *monsoro-lab-ectomap*](https://monsoro-lab-ectomap.shinyapps.io/EctoMAP): EctoMap_lite
+ [**EcycleCollectorSite** by *wisconsindnr*](https://wisconsindnr.shinyapps.io/EcycleCollectorSite): E-Cycle Wisconsin registered collection sites
+ [**EDA_categorical** by *istats*](https://istats.shinyapps.io/EDA_categorical): Exploring Categorical Data
+ [**EDA_quantitative** by *istats*](https://istats.shinyapps.io/EDA_quantitative): Exploring Quantitative Data
+ [**edge_shiny** by *billpetti*](https://billpetti.shinyapps.io/edge_shiny): Edge%: 2010-Present
+ [**edinbR_heatmap** by *gdevailly*](https://gdevailly.shinyapps.io/edinbR_heatmap): Interactive heatmap with R
+ [**eDNA_App** by *edna-probability-of-detection-calculator*](https://edna-probability-of-detection-calculator.shinyapps.io/eDNA_App): eDNA detection probability calculator
+ [**EDsimulation** by *gallery*](https://gallery.shinyapps.io/EDsimulation): Emergency Department Simulation
+ [**education_combined_scatter_v3** by *richleysh84*](https://richleysh84.shinyapps.io/education_combined_scatter_v3): School Finance
+ [**eduseq** by *jensenlab*](https://jensenlab.shinyapps.io/eduseq): DNA Short Read Generator
+ [**eggnogr** by *hadley*](https://hadley.shinyapps.io/eggnogr): eggnogr
+ [**elecciones21d** by *elecciones21d*](https://elecciones21d.shinyapps.io/elecciones21d): Simulador de los resultados del 21D-2017, a partir de datos introducidos por el usuario
+ [**Election2016** by *rkahne*](https://rkahne.shinyapps.io/Election2016): Kentucky 2016 General Election
+ [**electionpulsemap** by *curiositybits*](https://curiositybits.shinyapps.io/electionpulsemap): Underdog vs. Outlier
+ [**elections2** by *yiddishdata*](https://yiddishdata.shinyapps.io/elections2): די 2016 וואלן רעזולטאטן
+ [**electoralrules** by *jlsumner*](https://jlsumner.shinyapps.io/electoralrules): Electoral Rules Simulation Tool
+ [**eleicoes2014** by *neconiesp*](https://neconiesp.shinyapps.io/eleicoes2014): Pesquisa das Pesquisas
+ [**eltiempo** by *jmprietob*](https://jmprietob.shinyapps.io/eltiempo): El Tiempo - The weather
+ [**embryonic_pancreas** by *lynnlab*](https://lynnlab.shinyapps.io/embryonic_pancreas): Welcome to the Lynn Lab's Single Cell Gene Expression Atlas
+ [**Emergent_Epidemics_Lab_nCoV2019** by *scarpino*](https://scarpino.shinyapps.io/Emergent_Epidemics_Lab_nCoV2019): nCoV2019
+ [**emra** by *instatemra*](https://instatemra.shinyapps.io/emra): Title
+ [**emra** by *statemra*](https://statemra.shinyapps.io/emra): Title
+ [**EncuestaSalarialDataScientistArgentina2017** by *lpogorelsky*](https://lpogorelsky.shinyapps.io/EncuestaSalarialDataScientistArgentina2017): Encuesta Salarial de Data Scientist Argentina 2017
+ [**endodb** by *endotheliomics*](https://endotheliomics.shinyapps.io/endodb): EndoDB
+ [**enfinexplorer** by *enfinexplorer*](https://enfinexplorer.shinyapps.io/enfinexplorer): EnFinExplorer
+ [**engsoccerbeta** by *jalapic*](https://jalapic.shinyapps.io/engsoccerbeta): Exploring Historical English Soccer Data
+ [**Enronapp** by *michaelc*](https://michaelc.shinyapps.io/Enronapp): Could we have seen Enron coming?
+ [**Enronapp?utm_content=bufferae006&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer** by *michaelc*](https://michaelc.shinyapps.io/Enronapp?utm_content=bufferae006&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer): Could we have seen Enron coming?
+ [**EPIC_1-1** by *gfellerlab*](https://gfellerlab.shinyapps.io/EPIC_1-1): EPIC
+ [**EpiCOGSDEMO** by *amcrisan*](https://amcrisan.shinyapps.io/EpiCOGSDEMO): Load and View Data
+ [**epidcm** by *statnet*](https://statnet.shinyapps.io/epidcm): EpiModel: Deterministic Compartmental Models
+ [**epidemix** by *royalveterinarycollege*](https://royalveterinarycollege.shinyapps.io/epidemix): Epidemix
+ [**epigeneticclock** by *aging*](https://aging.shinyapps.io/epigeneticclock): Epigenetic clock
+ [**Epiquant** by *hetmanb*](https://hetmanb.shinyapps.io/Epiquant): EpiQuant
+ [**EpiQuant** by *hetmanb*](https://hetmanb.shinyapps.io/EpiQuant): EpiQuant
+ [**episensr_shiny** by *dhaine*](https://dhaine.shinyapps.io/episensr_shiny): episensr: Basic Sensitivity Analysis of Epidemiological Results
+ [**equator** by *aushsi*](https://aushsi.shinyapps.io/equator): A university league table based on good research practice
+ [**ERequirements** by *diana-thomas*](https://diana-thomas.shinyapps.io/ERequirements): Adult Energy Requirements Calculator
+ [**ERP-waveform-visualization_CMS-experiment** by *pablobernabeu*](https://pablobernabeu.shinyapps.io/ERP-waveform-visualization_CMS-experiment): ERP waveforms from experiment on Conceptual Modality Switch (Bernabeu et al., 2017)
+ [**ERPdemo** by *craddm*](https://craddm.shinyapps.io/ERPdemo): Exploring ERP plot options
+ [**ERPVis** by *pbloom*](https://pbloom.shinyapps.io/ERPVis): Interactive ERP Viewing Tool
+ [**ET_calculator** by *asianturfgrass*](https://asianturfgrass.shinyapps.io/ET_calculator): Reference and crop evapotranspiration (ET) calculator
+ [**etf-leverage-simulator** by *pchuck*](https://pchuck.shinyapps.io/etf-leverage-simulator): Leveraged ETF Returns
+ [**EthTownFloorROI** by *ether*](https://ether.shinyapps.io/EthTownFloorROI): Eth Town floor flip ROI
+ [**eu_pollster** by *kamilgregor*](https://kamilgregor.shinyapps.io/eu_pollster): Jaký je aktuální podíl hlasů pro stranu?
+ [**eu_pollster** by *kohovoliteu*](https://kohovoliteu.shinyapps.io/eu_pollster): Czech Polling Results
+ [**euclid** by *backfour*](https://backfour.shinyapps.io/euclid): Acute/Chronic Workload Ratio
+ [**eumigration** by *bnowok*](https://bnowok.shinyapps.io/eumigration): Migration composition
+ [**eurodatos** by *kamecon*](https://kamecon.shinyapps.io/eurodatos): Datos de Empleo (EUROSTAT)
+ [**eurofootycharts** by *aashanand*](https://aashanand.shinyapps.io/eurofootycharts): Euro Footy Charts
+ [**eurovision** by *mignonwuestman*](https://mignonwuestman.shinyapps.io/eurovision): Predicting the future
+ [**evalue** by *mmathur*](https://mmathur.shinyapps.io/evalue): E-value calculator
+ [**evanetworks** by *evanets*](https://evanets.shinyapps.io/evanetworks): EVA co-working networks in MDRS
+ [**exec** by *supraprimate*](https://supraprimate.shinyapps.io/exec): SUPRAPRIMATE: An online resource for cross-species single cell transcriptome data integration
+ [**expand_preston** by *jgassen*](https://jgassen.shinyapps.io/expand_preston): Explore the Preston Curve with ExPanDaR
+ [**expectancyApp** by *dczhang*](https://dczhang.shinyapps.io/expectancyApp): ShinyAESC
+ [**expertus** by *monex*](https://monex.shinyapps.io/expertus): Многокритериальная ОНлайн-ЭКСпертиза (МОНЭКС): интерактивный анализ и визуализация результатов
+ [**explore** by *richarddmorey*](https://richarddmorey.shinyapps.io/explore): Morey & Hoekstra 2019 Data
+ [**explore-timeseries** by *mabrek*](https://mabrek.shinyapps.io/explore-timeseries): Visual Exploration of Performance Monitoring Time Series
+ [**Explore_Instagram** by *moridani*](https://moridani.shinyapps.io/Explore_Instagram): EXPLORE INSTAGRAM IN YOUR NEIGHBORHOOD
+ [**ExploreCoverage** by *istats*](https://istats.shinyapps.io/ExploreCoverage): Explore Coverage of Confidence Intervals
+ [**ExploreModels** by *win-vector*](https://win-vector.shinyapps.io/ExploreModels): Explore Model Behavior
+ [**explorer** by *rest-wordcount*](https://rest-wordcount.shinyapps.io/explorer): Track the popularity of words and phrases over time in the articles of the Review of Economics and Statistics.
+ [**Exploring_Climate_Change_1900-2014** by *omaymas*](https://omaymas.shinyapps.io/Exploring_Climate_Change_1900-2014): Climate Change in Major Cities (1900-2014)
+ [**Exploring_Regression_in_R** by *aoshotse*](https://aoshotse.shinyapps.io/Exploring_Regression_in_R): Navbar!
+ [**exponential_discounting_demo** by *inferencelab*](https://inferencelab.shinyapps.io/exponential_discounting_demo): Exponential Discounting
+ [**extending-xG-gain** by *kubamichalczyk*](https://kubamichalczyk.shinyapps.io/extending-xG-gain): Transform function visualisation

## F
+ [**F1_twitter_app** by *atajti*](https://atajti.shinyapps.io/F1_twitter_app): Number of F1 tweets
+ [**facts** by *aapidata*](https://aapidata.shinyapps.io/facts): Community Facts
+ [**faktury-pravni** by *samizdat*](https://samizdat.shinyapps.io/faktury-pravni): Proplacené faktury ministerstva financí
+ [**false_discovery** by *lawsofthought*](https://lawsofthought.shinyapps.io/false_discovery): Why Most Published Research Findings Are False
+ [**FalseDiscoveryRate** by *philipp*](https://philipp.shinyapps.io/FalseDiscoveryRate): Controlling the False Discovery Rate
+ [**fansstructure** by *slerka*](https://slerka.shinyapps.io/fansstructure): Fans by Countries
+ [**fantasytools** by *fantasydota*](https://fantasydota.shinyapps.io/fantasytools): Fantasy Dota
+ [**FB_page_analyzer** by *thinktostart*](https://thinktostart.shinyapps.io/FB_page_analyzer): Facebook Page Analyzer BETA 1
+ [**FCount** by *econometricsbysimulation*](https://econometricsbysimulation.shinyapps.io/FCount): Function Counter for R
+ [**fe-apprenticeship-statistics** by *department-for-education*](https://department-for-education.shinyapps.io/fe-apprenticeship-statistics): Apprenticeships Statistics
+ [**FearNot** by *taxsmack*](https://taxsmack.shinyapps.io/FearNot): 2017 Tax Planning
+ [**febrile_app** by *templepeds*](https://templepeds.shinyapps.io/febrile_app): Welcome to the serious bacterial infection model for young infants. This model was developed by a team from the Lewis Katz School of Medicine at Temple University utilizing a large data set of febrile infants collected by the Pediatric Emergency Applied Research Network (PECARN). The purpose of this model is to estimate the risk of urinary tract infection, bacteremia and/or meningitis in a subset of infants deemed to be at low risk for these infections. This model is for clinical prediction only and does not include recommendations for patient management.
+ [**FedElect2015** by *robscottd*](https://robscottd.shinyapps.io/FedElect2015): Ottawa Federal Election Twitter Analysis 2015
+ [**fertility** by *mbcladwell*](https://mbcladwell.shinyapps.io/fertility): Fertility
+ [**fg-models** by *jamesledoux*](https://jamesledoux.shinyapps.io/fg-models): Field Goal Models
+ [**fieller** by *sb452*](https://sb452.shinyapps.io/fieller): Fieller's theorem
+ [**filtering-badness** by *hrbrmstr*](https://hrbrmstr.shinyapps.io/filtering-badness): Wastebook Article 13 Infringement Filter Control Panel
+ [**final** by *fishdata*](https://fishdata.shinyapps.io/final): How is climate changing and where with R
+ [**final** by *irjerad*](https://irjerad.shinyapps.io/final): An Improved Aproximation of Blood Alcohol Content
+ [**Final** by *jafec*](https://jafec.shinyapps.io/Final): Beginner's Tutorial
+ [**final-baseball-app** by *thiessen*](https://thiessen.shinyapps.io/final-baseball-app): Homeruns per Game
+ [**final_project** by *mile*](https://mile.shinyapps.io/final_project): Sample Size Calculation for one-sample t-test
+ [**FINAL_PROJECT_COURSERA_DDP** by *valeria*](https://valeria.shinyapps.io/FINAL_PROJECT_COURSERA_DDP): Internet Services Utility (Conjoint market simulator)
+ [**FinalAppPolioData** by *jddavis*](https://jddavis.shinyapps.io/FinalAppPolioData): Polio Vaccine Efficacy in the US: Visual Assessment
+ [**finalhomework** by *benhives*](https://benhives.shinyapps.io/finalhomework): Tony Awards
+ [**finance_app** by *kylethomas*](https://kylethomas.shinyapps.io/finance_app): Financial Plots
+ [**financialecon** by *gulraiz*](https://gulraiz.shinyapps.io/financialecon): financial economitrics
+ [**Finemapping** by *atgu*](https://atgu.shinyapps.io/Finemapping): International IBD Genetics Consortium Fine-mapping project
+ [**finflows** by *followthemoney*](https://followthemoney.shinyapps.io/finflows): Financial Flows Euro Area
+ [**finny** by *jobechoi*](https://jobechoi.shinyapps.io/finny): Guess the word up to the 6th one...
+ [**fintrends** by *fsdkenya*](https://fsdkenya.shinyapps.io/fintrends): fin::trends
+ [**firstApp** by *mclapham*](https://mclapham.shinyapps.io/firstApp): First appearances
+ [**fish** by *macartan*](https://macartan.shinyapps.io/fish): An Exact Fishy Test
+ [**fish_trend_graphs** by *statisticsnz*](https://statisticsnz.shinyapps.io/fish_trend_graphs): Fish abundance trends
+ [**fishcast2** by *sfg-ucsb*](https://sfg-ucsb.shinyapps.io/fishcast2): Global-level fisheries forecasts and adaptive strategies
+ [**fisheries** by *scotland*](https://scotland.shinyapps.io/fisheries): Landings of key species into Scotland by Scottish registered vessels from 2000-2015
+ [**FishViz** by *james-thorson*](https://james-thorson.shinyapps.io/FishViz): Visualize fish populations
+ [**FLAM** by *ajpete*](https://ajpete.shinyapps.io/FLAM): Fused Lasso Additive Model - Simulated Data Application
+ [**FlightPlanner** by *anantgupta*](https://anantgupta.shinyapps.io/FlightPlanner): Flight Planner
+ [**FluGBSapp** by *stevenhawken*](https://stevenhawken.shinyapps.io/FluGBSapp): Individual Guillain Barré Syndrome (GBS) Risk Calculator
+ [**foia_shiny_app** by *datadotworld*](https://datadotworld.shinyapps.io/foia_shiny_app): Predict Your FOIA Request Success
+ [**food_check_live** by *usaskssrl*](https://usaskssrl.shinyapps.io/food_check_live): Peel Public Health
+ [**food_price_changes** by *blin02*](https://blin02.shinyapps.io/food_price_changes): Food price changes over time, from year 1974 - 2015. Food price changes vs all-items prices changes. All-items include all consumer goods and services, including food. Food price changes vs Producer price changes. Producer price changes measures the average change in prices paid to domestic producers for their output.
+ [**football_analytics_dashboard** by *apita*](https://apita.shinyapps.io/football_analytics_dashboard): Match HUD
+ [**ForestChange_ProofOfConcept** by *spades*](https://spades.shinyapps.io/ForestChange_ProofOfConcept): SpaDES - Proof of concept model - THESE DO NOT CONTAIN REAL DATA
+ [**formatR** by *yihui*](https://yihui.shinyapps.io/formatR): Tidy R Code with formatR (Yihui Xie)
+ [**fourfactors123** by *tvbassine*](https://tvbassine.shinyapps.io/fourfactors123): Threes and Layups NBA Net Rating Calculator
+ [**fourier-deseasonality** by *algorithmia*](https://algorithmia.shinyapps.io/fourier-deseasonality): NY Births with Fourier Detrend
+ [**Fourier_Smoother** by *jeffreyuslan*](https://jeffreyuslan.shinyapps.io/Fourier_Smoother): Fourier Smoother Demonstration
+ [**fpl_fixture_difficulty** by *tojyouso*](https://tojyouso.shinyapps.io/fpl_fixture_difficulty): FPL fixture difficulty
+ [**fpmaps** by *gutt*](https://gutt.shinyapps.io/fpmaps): Guttmacher Institute
+ [**freeR** by *committedtotape*](https://committedtotape.shinyapps.io/freeR): FREE R READING MATERIAL
+ [**friedman_acronym_generator** by *nnstats*](https://nnstats.shinyapps.io/friedman_acronym_generator): Elliotte Friedman Acronym Generator
+ [**FrissDashboard** by *frissdemo*](https://frissdemo.shinyapps.io/FrissDashboard): Friss analytics
+ [**fsp_refugees** by *savings-frontier*](https://savings-frontier.shinyapps.io/fsp_refugees): Financial Lives of Refugees
+ [**FunGeneClusterS** by *fungiminions*](https://fungiminions.shinyapps.io/FunGeneClusterS): FunGeneClusterS: Fungal Gene Clustering
+ [**funnelinf_app** by *metaviz*](https://metaviz.shinyapps.io/funnelinf_app): Visual funnel plot inference

## G
+ [**G2Sd** by *regisgallon*](https://regisgallon.shinyapps.io/G2Sd): G2Sd : Grain-size Statistics and Description of Sediment
+ [**g6pd_screening** by *malaria*](https://malaria.shinyapps.io/g6pd_screening): Cost effectiveness of G6PD screening
+ [**ga-dimsmets** by *artemklevtsov*](https://artemklevtsov.shinyapps.io/ga-dimsmets): Google Analytics: Dimensions & Metrics
+ [**ga-effect** by *gallery*](https://gallery.shinyapps.io/ga-effect): GA Effect
+ [**ga-effect** by *mark*](https://mark.shinyapps.io/ga-effect): GA Effect
+ [**ga-meta** by *mark*](https://mark.shinyapps.io/ga-meta): GA Meta
+ [**ga-rollup** by *mark*](https://mark.shinyapps.io/ga-rollup): GA Rollup
+ [**gahner** by *56north*](https://56north.shinyapps.io/gahner): Danish Polls
+ [**game-of-thrones** by *wd2017*](https://wd2017.shinyapps.io/game-of-thrones): Game of Thrones - character occurences
+ [**Game_of_life** by *ulvic*](https://ulvic.shinyapps.io/Game_of_life): Game of Life
+ [**gamebygame** by *jalapic*](https://jalapic.shinyapps.io/gamebygame): Comparing Seasons
+ [**gamePredictor** by *malter61*](https://malter61.shinyapps.io/gamePredictor): Baseball game wins probability calculator by Mark Malter
+ [**gamma** by *gamma-trader*](https://gamma-trader.shinyapps.io/gamma): G.O. Gamma Central
+ [**ganttshiny** by *asgr*](https://asgr.shinyapps.io/ganttshiny): Extra-Galactic Survey Gantts
+ [**Gapminder-app** by *creagh*](https://creagh.shinyapps.io/Gapminder-app): Gapminder Shiny app
+ [**gas-mileage** by *karawoo*](https://karawoo.shinyapps.io/gas-mileage): Gas Mileage
+ [**GBIFapp** by *aleruete*](https://aleruete.shinyapps.io/GBIFapp): Ignorance Explorer
+ [**gbmParameterPerformance** by *ramshiny*](https://ramshiny.shinyapps.io/gbmParameterPerformance): Visualizing parameter performance in GBM
+ [**GBS_Atlas** by *landcare*](https://landcare.shinyapps.io/GBS_Atlas): New Zealand Garden Bird Atlas (2007–2015)
+ [**GDELTNetApp** by *gallery*](https://gallery.shinyapps.io/GDELTNetApp): Network
+ [**gem-scd** by *jepusto*](https://jepusto.shinyapps.io/gem-scd): Gradual Effects Model Calculator
+ [**gender** by *gokhan*](https://gokhan.shinyapps.io/gender): LSE IR Gender Project
+ [**GeneExpresso** by *griffith*](https://griffith.shinyapps.io/GeneExpresso): Gene Expresso.. quick view of the gene expression
+ [**GenEst** by *west-inc*](https://west-inc.shinyapps.io/GenEst): GenEst v1.3.1
+ [**GeneTyPR** by *wjjessen*](https://wjjessen.shinyapps.io/GeneTyPR): Gene Type ParseR (Gene TyPR) | Homo Sapiens
+ [**geneuron20150218** by *geneuron*](https://geneuron.shinyapps.io/geneuron20150218): Geneuron 1.1
+ [**genjiapp** by *gtcym*](https://gtcym.shinyapps.io/genjiapp): 絵入源氏物語
+ [**genome_browser** by *gallery*](https://gallery.shinyapps.io/genome_browser): ICGC Pancreatic Cancer (Ductal Adenocarcinoma) - Genome Viewer
+ [**geocoder** by *rich*](https://rich.shinyapps.io/geocoder): Reed College Geocoding Application
+ [**GeoDemographics** by *mariplaza*](https://mariplaza.shinyapps.io/GeoDemographics): Vienna GeoDemographics
+ [**georefr** by *mrjoh3*](https://mrjoh3.shinyapps.io/georefr): Image Georeferencing
+ [**GeoVis** by *kkalyan3*](https://kkalyan3.shinyapps.io/GeoVis): Geo Viz
+ [**gganatogram** by *jespermaag*](https://jespermaag.shinyapps.io/gganatogram): gganatogram
+ [**ggplotwithyourdata** by *pharmacometrics*](https://pharmacometrics.shinyapps.io/ggplotwithyourdata): Welcome to ggquickeda!
+ [**ggsegDemo** by *athanasiamo*](https://athanasiamo.shinyapps.io/ggsegDemo): Demonstration of ggseg package
+ [**ggtree** by *gallery*](https://gallery.shinyapps.io/ggtree): Visualizing ggplot2 internals
+ [**ggvis-maps** by *hrbrmstr*](https://hrbrmstr.shinyapps.io/ggvis-maps): ggvis shiny maps
+ [**ghanatelecomdatainspector** by *davidquartey*](https://davidquartey.shinyapps.io/ghanatelecomdatainspector): Ghana Telecom Data Inspector
+ [**gifted_identification_explorer** by *mmcbee*](https://mmcbee.shinyapps.io/gifted_identification_explorer): Gifted Identification Psychometrics Explorer
+ [**githubAnalyses** by *mytinyshinys*](https://mytinyshinys.shinyapps.io/githubAnalyses): Github
+ [**GLDC** by *shareshiny2018*](https://shareshiny2018.shinyapps.io/GLDC): Generalized Lambda Distribution Calculator
+ [**glee** by *lponnala*](https://lponnala.shinyapps.io/glee): GLEE: differential protein expression test
+ [**global_cities_visualization** by *oecdregional*](https://oecdregional.shinyapps.io/global_cities_visualization): Cities in the world
+ [**Global_Temp** by *loiyumba*](https://loiyumba.shinyapps.io/Global_Temp): Average Temperature of Indian Cities
+ [**globalspectr** by *sdray*](https://sdray.shinyapps.io/globalspectr): The global spectrum of plant form and function
+ [**GlobalTerrorism** by *sarthakdasadia*](https://sarthakdasadia.shinyapps.io/GlobalTerrorism): Studying Bomb / Explotion Attacks
+ [**gmse_gui** by *bradduthie*](https://bradduthie.shinyapps.io/gmse_gui): GMSE
+ [**golf** by *jalapic*](https://jalapic.shinyapps.io/golf): Scatterplot 1
+ [**GolfR** by *tzurloye*](https://tzurloye.shinyapps.io/GolfR): GolfR
+ [**google-charts** by *gallery*](https://gallery.shinyapps.io/google-charts): Google Charts demo
+ [**googleAnalyticsRv4Demo** by *mark*](https://mark.shinyapps.io/googleAnalyticsRv4Demo): Google Analytics v4 API Demo
+ [**googly** by *tvganesh*](https://tvganesh.shinyapps.io/googly): Googly : yorkr analyzes IPL!
+ [**GOPtax2017** by *benjaminackerman*](https://benjaminackerman.shinyapps.io/GOPtax2017): How will the House Tax Bill Impact Graduate Students?
+ [**got_shiny** by *alval*](https://alval.shinyapps.io/got_shiny): Game of Thrones (GoT): A Network Analysis
+ [**gotv-app** by *egap*](https://egap.shinyapps.io/gotv-app): Analysis of Field Experiments
+ [**GPAvatar** by *paceturf*](https://paceturf.shinyapps.io/GPAvatar): Make a GP avatar for your location
+ [**GPCRsnakeplotter** by *yuejiang*](https://yuejiang.shinyapps.io/GPCRsnakeplotter): snakeplotter for GPCRs
+ [**graph2png** by *blacksheep*](https://blacksheep.shinyapps.io/graph2png): Download a Graph from DiagrammeR
+ [**graphic** by *mrooijer*](https://mrooijer.shinyapps.io/graphic): Global Temperature Explorer
+ [**gravicom** by *andeek*](https://andeek.shinyapps.io/gravicom): gravicom
+ [**grc2h** by *steno*](https://steno.shinyapps.io/grc2h): Glucose Response Classifier
+ [**greengov** by *cwee*](https://cwee.shinyapps.io/greengov): Background
+ [**gremApp** by *timcdlucas*](https://timcdlucas.shinyapps.io/gremApp): gREM: Estimate animal density or abundance
+ [**GribbleGap_Discharge** by *wcu-hydro*](https://wcu-hydro.shinyapps.io/GribbleGap_Discharge): Gribble Gap Discharge (beta)
+ [**GSCA** by *zhiji*](https://zhiji.shinyapps.io/GSCA): GSCA: Gene Set Context Analysis
+ [**guesscorr** by *istats*](https://istats.shinyapps.io/guesscorr): Correlation Game
+ [**guessing-game** by *statisfactions*](https://statisfactions.shinyapps.io/guessing-game): Guessing Game
+ [**guestApps** by *mytinyshinys*](https://mytinyshinys.shinyapps.io/guestApps): Guest Apps
+ [**gVision-shiny** by *flovv*](https://flovv.shinyapps.io/gVision-shiny): Object Detection using Google Cloud Vision
+ [**gwas_shiny_app** by *shiring*](https://shiring.shinyapps.io/gwas_shiny_app): GWAS disease- & trait-associated SNP locations of the human genome
+ [**gwdegree** by *michaellevy*](https://michaellevy.shinyapps.io/gwdegree): GW Degree Statistic Behavior

## H
+ [**hackathon** by *tangerine007*](https://tangerine007.shinyapps.io/hackathon): Honduras - Correlation Matrix
+ [**hackathon_shiny** by *safferli*](https://safferli.shinyapps.io/hackathon_shiny): Build Your Own Offshore Corporation
+ [**HackVizOccitanie** by *tnidelet*](https://tnidelet.shinyapps.io/HackVizOccitanie): Bonjour !!
+ [**Haelisleitendur** by *a-m-agustsson*](https://a-m-agustsson.shinyapps.io/Haelisleitendur): Distribution of Asylum Seekers in the EU/EEA Area
+ [**haikugen** by *adamishere*](https://adamishere.shinyapps.io/haikugen): Random Haiku Generator
+ [**Halo5_Stats** by *jjohn9000*](https://jjohn9000.shinyapps.io/Halo5_Stats): Halo 5 Stats
+ [**HappyJobsTestApp** by *what-works-wellbeing*](https://what-works-wellbeing.shinyapps.io/HappyJobsTestApp): Happy Jobs! - How does your well-being compare to people in different jobs in the UK?
+ [**harmonic** by *ludger*](https://ludger.shinyapps.io/harmonic): Harmonic Regression
+ [**HarrellPlot** by *middleprofessor*](https://middleprofessor.shinyapps.io/HarrellPlot): Harrell Plot
+ [**harvey-ses-layers** by *ianwells*](https://ianwells.shinyapps.io/harvey-ses-layers): Mapping Modeled Flood Damage, Property Values, and Socio-Economic Data In Harris County
+ [**hclust-shiny** by *joyofdata*](https://joyofdata.shinyapps.io/hclust-shiny): Hierarchical Clustering in Action
+ [**hdnom-app** by *gallery*](https://gallery.shinyapps.io/hdnom-app): hdnom.io - Nomograms for High-Dimensional Data
+ [**healthdatabreach** by *sungexplore*](https://sungexplore.shinyapps.io/healthdatabreach): Health Data Breaches
+ [**healthplot** by *databiomics*](https://databiomics.shinyapps.io/healthplot): HealthPlot - Exploring public health in USA through R and Open Data
+ [**HEAT** by *whoequity*](https://whoequity.shinyapps.io/HEAT): Health Equity Assessment Toolkit
+ [**heatmap** by *stefanwilhelm*](https://stefanwilhelm.shinyapps.io/heatmap): Interactive Highcharts Heat Map in Shiny
+ [**heatmapStock** by *blenditbayes*](https://blenditbayes.shinyapps.io/heatmapStock): Stock Market Calendar Heat Map
+ [**helpmeviz-malnutrition** by *jpaulson*](https://jpaulson.shinyapps.io/helpmeviz-malnutrition): As Women Rise, Malnutrition Falls Use this interactive tool to compare country data on women's empowerment and stunting. Click here to open in separate window.
+ [**helsinkikuntavaalit-app** by *veikkoisotalo*](https://veikkoisotalo.shinyapps.io/helsinkikuntavaalit-app): Kuntavaalit 2017
+ [**HerbicideRiskCalculator** by *wyoweeds*](https://wyoweeds.shinyapps.io/HerbicideRiskCalculator): Herbicide Resistance Risk Caluclator
+ [**HEVmodel** by *moru*](https://moru.shinyapps.io/HEVmodel): HEV vaccination policy evaluation tool
+ [**HINTS2017** by *translatedmedicine*](https://translatedmedicine.shinyapps.io/HINTS2017): HINTS 2017 Survey: Smartphone Ownership Demographics (Weighted Frequencies)
+ [**hip_fracture** by *moppettsmusings*](https://moppettsmusings.shinyapps.io/hip_fracture): Prediction of outcomes following hip fracture
+ [**HistPat** by *histpat*](https://histpat.shinyapps.io/HistPat): Choose a Variable
+ [**HitterDashBoard** by *joshua-rodrigues*](https://joshua-rodrigues.shinyapps.io/HitterDashBoard): Hitting Dashboard
+ [**hmd_explorer** by *datascapes*](https://datascapes.shinyapps.io/hmd_explorer): Human Mortality Database Explorer
+ [**hmdexp** by *jschoeley*](https://jschoeley.shinyapps.io/hmdexp): Human Mortality Explorer
+ [**HNSCCmodel** by *katrin*](https://katrin.shinyapps.io/HNSCCmodel): Estimated risk profile for 3yr outcome
+ [**Home** by *qmi-fcrr*](https://qmi-fcrr.shinyapps.io/Home): QMI Shiny Home
+ [**homebrewR** by *davesteps*](https://davesteps.shinyapps.io/homebrewR): HomebrewR
+ [**homicide_app** by *rfnajera*](https://rfnajera.shinyapps.io/homicide_app): Baltimore Homicide Map
+ [**household-typology** by *hanifsamad*](https://hanifsamad.shinyapps.io/household-typology): Bank of England household survey
+ [**housing2** by *cergs*](https://cergs.shinyapps.io/housing2): Data Explorer
+ [**housingandmigration** by *mhpcenterforhousingdata*](https://mhpcenterforhousingdata.shinyapps.io/housingandmigration): Migration, housing production, and price
+ [**HoustonCrimeViewer** by *seasmith*](https://seasmith.shinyapps.io/HoustonCrimeViewer): Houston Crime Viewer
+ [**hoxom-card** by *ksmzn*](https://ksmzn.shinyapps.io/hoxom-card): HOXO-M Card
+ [**hPVI_2015_histapp** by *tonyangelo*](https://tonyangelo.shinyapps.io/hPVI_2015_histapp): Minnesota 2015 hPVI Distribution
+ [**HR-Hitters** by *danmalter*](https://danmalter.shinyapps.io/HR-Hitters): Hitters in Baseball
+ [**HRFirstDevDatProd_Normal** by *hrcamilo*](https://hrcamilo.shinyapps.io/HRFirstDevDatProd_Normal): Random Generator for Normal Distribution on Shiny
+ [**html2r** by *alandipert*](https://alandipert.shinyapps.io/html2r): HTML to R Converter
+ [**hyperbolic_discounting_demo** by *inferencelab*](https://inferencelab.shinyapps.io/hyperbolic_discounting_demo): Hyperbolic Discounting

## I
+ [**iaaf** by *bluecattechnical*](https://bluecattechnical.shinyapps.io/iaaf): Rankings
+ [**ibp-demo** by *mcdickenson*](https://mcdickenson.shinyapps.io/ibp-demo): Indian Buffet Process
+ [**ICLD** by *indoligensia*](https://indoligensia.shinyapps.io/ICLD): YogyEWS v.0.1
+ [**iconicity_patterns** by *sl-iconicity*](https://sl-iconicity.shinyapps.io/iconicity_patterns): Iconicity patterns in Sign Languges
+ [**IdealPointsUN** by *erikvoeten*](https://erikvoeten.shinyapps.io/IdealPointsUN): Ideal Points Estimation
+ [**image** by *martinmolder*](https://martinmolder.shinyapps.io/image): R + Shiny = Crude image processing
+ [**image-output** by *gallery*](https://gallery.shinyapps.io/image-output): Client data and query string example
+ [**imagesurvey** by *gzthompson*](https://gzthompson.shinyapps.io/imagesurvey): Image Distortion Calibration Survey
+ [**IMDB_Explorer** by *yuorme*](https://yuorme.shinyapps.io/IMDB_Explorer): IMDB Movie Explorer
+ [**imgsvd** by *nanx*](https://nanx.shinyapps.io/imgsvd): ImgSVD: Image Compression via SVD
+ [**imgsvd** by *yihui*](https://yihui.shinyapps.io/imgsvd): ImgSVD - Image Compression via SVD
+ [**immigration_overview_mini** by *jeffersonselectorate*](https://jeffersonselectorate.shinyapps.io/immigration_overview_mini): US Immigration Explorer
+ [**immunecelltypes** by *mfoos*](https://mfoos.shinyapps.io/immunecelltypes): Immune Cell Gene Expression Data
+ [**IMO-ODE-solver** by *ashcroftp*](https://ashcroftp.shinyapps.io/IMO-ODE-solver): Test ODE model
+ [**importancesamplingshiny** by *agomezh*](https://agomezh.shinyapps.io/importancesamplingshiny): Importance Sampling Samples
+ [**ims-shiny** by *sgibb*](https://sgibb.shinyapps.io/ims-shiny): MALDIquant - MSI example
+ [**including-html-text-and-markdown-files** by *gallery*](https://gallery.shinyapps.io/including-html-text-and-markdown-files): includeText, includeHTML, and includeMarkdown
+ [**incubator-progress** by *gallery*](https://gallery.shinyapps.io/incubator-progress): Progress demo
+ [**indeedoor** by *jcp1016*](https://jcp1016.shinyapps.io/indeedoor): Target your data science job search
+ [**index** by *powerupr*](https://powerupr.shinyapps.io/index): PowerUpR
+ [**indiana-hiv** by *forrestcrawford*](https://forrestcrawford.shinyapps.io/indiana-hiv): Dynamics of the HIV outbreak and response in Scott County, Indiana 2011-2015
+ [**individual-vote-nzes** by *ellisp*](https://ellisp.shinyapps.io/individual-vote-nzes): Modelled individual party vote in the New Zealand 2014 General Election
+ [**iNEXTOnline** by *chao*](https://chao.shinyapps.io/iNEXTOnline): iNEXT Online (Sept. 2016)
+ [**Inference** by *olivierklein*](https://olivierklein.shinyapps.io/Inference): Comparaison de deux moyennes
+ [**Influence_Analysis** by *omaymas*](https://omaymas.shinyapps.io/Influence_Analysis): Influence Analysis
+ [**influenza** by *calthaus*](https://calthaus.shinyapps.io/influenza): Simulating an influenza epidemic
+ [**Influenza_isolates** by *pmacp*](https://pmacp.shinyapps.io/Influenza_isolates): Influenza types from global surveillance isolates: 1995 to 2016
+ [**intbp** by *sanjaybasu*](https://sanjaybasu.shinyapps.io/intbp): Intensive BP Rx
+ [**interaction** by *thomassiegmund*](https://thomassiegmund.shinyapps.io/interaction): Interactive features
+ [**interactive** by *connorjmccabe*](https://connorjmccabe.shinyapps.io/interactive): interActive: A tool for the visual display of interactions
+ [**InteractiveLTV** by *pianalytics*](https://pianalytics.shinyapps.io/InteractiveLTV): PI Analytics
+ [**interest** by *interest*](https://interest.shinyapps.io/interest): INTEREST
+ [**international_jobs** by *tomliptrot*](https://tomliptrot.shinyapps.io/international_jobs): International jobs search | Map
+ [**intervene** by *asntech*](https://asntech.shinyapps.io/intervene): Intervene - a tool for intersection and visualization of multiple gene or genomic region sets
+ [**intervene** by *intervene*](https://intervene.shinyapps.io/intervene): Intervene - an interactive Shiny app for UpSet plots, Venn diagrams and Pairwise heatmaps
+ [**InvestmentInWatershedServices** by *cromulo*](https://cromulo.shinyapps.io/InvestmentInWatershedServices): Investments in Watershed Services
+ [**IPLAnalytics** by *iplfantasy*](https://iplfantasy.shinyapps.io/IPLAnalytics): IPL Analytics
+ [**IPlookup** by *rkennedy*](https://rkennedy.shinyapps.io/IPlookup): IP Lookup Application
+ [**irisExplore** by *vranjan*](https://vranjan.shinyapps.io/irisExplore): Iris Data Exploration and Prediction
+ [**irr_ph** by *asianturfgrass*](https://asianturfgrass.shinyapps.io/irr_ph): Turfgrass irrigation requirement at a few locations in the Philippines
+ [**irrigation** by *asianturfgrass*](https://asianturfgrass.shinyapps.io/irrigation): Irrigation water requirement
+ [**isithotrightnow** by *rensa*](https://rensa.shinyapps.io/isithotrightnow): Is it hot in Sydney right now?
+ [**isogloss** by *isogloss*](https://isogloss.shinyapps.io/isogloss): Word Mapper
+ [**iSwathX** by *biolinfo*](https://biolinfo.shinyapps.io/iSwathX): iSwathX 2.0
+ [**ivy_tiebreaks** by *lbenz730*](https://lbenz730.shinyapps.io/ivy_tiebreaks): Ivy League TiebreakR
+ [**iwinrnfl** by *kpele*](https://kpele.shinyapps.io/iwinrnfl): NFL In-Game Win Probability - iWinrNFL

## J
+ [**Jambo_Map** by *poppypresents*](https://poppypresents.shinyapps.io/Jambo_Map): World Scout Jamboree International Unit Map
+ [**JAPTopicNetwork** by *blistyg*](https://blistyg.shinyapps.io/JAPTopicNetwork): Visualizing The Relationship between JAP Article Keywords
+ [**jb-flight-deals** by *sparsedata*](https://sparsedata.shinyapps.io/jb-flight-deals): Sparse Data
+ [**JDPayCalc** by *dannyjnwong*](https://dannyjnwong.shinyapps.io/JDPayCalc): Junior Doctors' Pay Calculator v.0.5
+ [**Jester** by *mhahsler-apps*](https://mhahsler-apps.shinyapps.io/Jester): Joke Recommender Using Jester Data
+ [**jiebaR-shiny** by *qinwf*](https://qinwf.shinyapps.io/jiebaR-shiny): 输入文本
+ [**joggingdash** by *zfleeman*](https://zfleeman.shinyapps.io/joggingdash): Speed vs. Mood Chart
+ [**journal_turnaround_app** by *jcsuarez*](https://jcsuarez.shinyapps.io/journal_turnaround_app): Journal Turnaround Times
+ [**jp_mlsnK** by *asianturfgrass*](https://asianturfgrass.shinyapps.io/jp_mlsnK): MLSN ガイドラインからK要求量を求める
+ [**JPL_Shiny** by *mldschry*](https://mldschry.shinyapps.io/JPL_Shiny): Kick&RushLab JPL-table season 16-17
+ [**judiciales** by *ppiccato*](https://ppiccato.shinyapps.io/judiciales): Estadísticas del crimen en México: Series Históricas 1926 - 2008
+ [**junction_app** by *jiddualexander*](https://jiddualexander.shinyapps.io/junction_app): Junction Profiling
+ [**jwp-app** by *jeopardy-win-probability*](https://jeopardy-win-probability.shinyapps.io/jwp-app): Jeopardy Win Probability

## K
+ [**KaggleSurveyDataAnalysisDashboard** by *anishwalia20*](https://anishwalia20.shinyapps.io/KaggleSurveyDataAnalysisDashboard): Kaggle Survey Data analysis
+ [**karachi_property** by *azam*](https://azam.shinyapps.io/karachi_property): Property Price Predictor
+ [**kcompshiny** by *win-vector*](https://win-vector.shinyapps.io/kcompshiny): Messages
+ [**kenya** by *lenalyticslab*](https://lenalyticslab.shinyapps.io/kenya): Visualizing Kenya County Data
+ [**keras-customer-churn** by *jjallaire*](https://jjallaire.shinyapps.io/keras-customer-churn): Customer Churn Analytics
+ [**kfre_app** by *mccudden*](https://mccudden.shinyapps.io/kfre_app): KFRE 2-year Risk Variation Model
+ [**klexdatr-movement** by *poissonconsulting*](https://poissonconsulting.shinyapps.io/klexdatr-movement): Kootenay Lake Fish Movement
+ [**kmeans** by *jcheng*](https://jcheng.shinyapps.io/kmeans): Iris k-means clustering
+ [**knowlabshiny** by *compassnz*](https://compassnz.shinyapps.io/knowlabshiny): Knowledge Lab
+ [**ky-house-18** by *rkahne*](https://rkahne.shinyapps.io/ky-house-18): Kentucky Election, 2018
+ [**kyelect_2018** by *rkahne*](https://rkahne.shinyapps.io/kyelect_2018): Kentucky Election, 2018
+ [**kyleg** by *rkahne*](https://rkahne.shinyapps.io/kyleg): Geographical Voting Visualization
+ [**kyleg_twitter** by *rkahne*](https://rkahne.shinyapps.io/kyleg_twitter): Kentucky Legislature Twitter Sentiment Dashboards

## L
+ [**Lab_Exercise_CatVars2** by *kbodwin*](https://kbodwin.shinyapps.io/Lab_Exercise_CatVars2): Lab Exercise: Categorical Variables
+ [**Lab_Exercise_t_tests2** by *kbodwin*](https://kbodwin.shinyapps.io/Lab_Exercise_t_tests2): Lab Exercise: t-tests and Confidence Intervals
+ [**labour-market-dashboard_prod** by *mbienz*](https://mbienz.shinyapps.io/labour-market-dashboard_prod): The New Zealand Labour Market Dashboard
+ [**lac_diversity** by *wb-lac*](https://wb-lac.shinyapps.io/lac_diversity): Violence in Latin America
+ [**lactate** by *orreco*](https://orreco.shinyapps.io/lactate): Lactate-OR has moved!
+ [**lahontan** by *trout*](https://trout.shinyapps.io/lahontan): Lahontan Cutthroat Trout Population Simulator v2.01
+ [**lake_water_quality** by *statisticsnz*](https://statisticsnz.shinyapps.io/lake_water_quality): Lake water quality
+ [**lakens_effect_sizes** by *katherinemwood*](https://katherinemwood.shinyapps.io/lakens_effect_sizes): Calculating Effect Sizes
+ [**langmap** by *cainesap*](https://cainesap.shinyapps.io/langmap): Languages of the world
+ [**LatentChangeScore** by *qmi-fcrr*](https://qmi-fcrr.shinyapps.io/LatentChangeScore): LGM Comp
+ [**LCO-CI** by *jdoi*](https://jdoi.shinyapps.io/LCO-CI): LCO Confidence Interval Generator
+ [**leafletDrilldown_Improvements** by *efh0888*](https://efh0888.shinyapps.io/leafletDrilldown_Improvements): Reset to the country level map by clicking anywhere outside the polygons.
+ [**leafviz** by *leafcutter*](https://leafcutter.shinyapps.io/leafviz): LeafViz
+ [**leg_app** by *ofchurches*](https://ofchurches.shinyapps.io/leg_app): South Australian Legislation Network current as of November 2018 including only acts with at least one link (including loops)
+ [**lego-viz** by *gallery*](https://gallery.shinyapps.io/lego-viz): LEGO Set Visualizer
+ [**Lending_Club_App_v1** by *hitesh-mistry-systemsforecasting*](https://hitesh-mistry-systemsforecasting.shinyapps.io/Lending_Club_App_v1): Lending Club Profit/Loss App
+ [**lexical_dispersion_plot** by *christian-burkhart*](https://christian-burkhart.shinyapps.io/lexical_dispersion_plot): Plot your own lexical dispersion plots
+ [**LeyWeberFechner** by *urigonzalezbravo*](https://urigonzalezbravo.shinyapps.io/LeyWeberFechner): Ley de Weber-Fechner
+ [**lfcgmR** by *terrydolan*](https://terrydolan.shinyapps.io/lfcgmR): The LFC Goal Machine
+ [**librelink** by *personalscience*](https://personalscience.shinyapps.io/librelink): Richard Sprague
+ [**likelihood** by *lakens*](https://lakens.shinyapps.io/likelihood): Likelihood Ratio for Mixed Results
+ [**LinearRegression** by *istats*](https://istats.shinyapps.io/LinearRegression): Linear Regression
+ [**linreg** by *cabaceo*](https://cabaceo.shinyapps.io/linreg): Linear Regression
+ [**liver** by *zliu-omics*](https://zliu-omics.shinyapps.io/liver): The Liver Integrative Omics Network (LION) Project
+ [**livingcostsexplorer** by *statisticsnz*](https://statisticsnz.shinyapps.io/livingcostsexplorer): Explore living-costs in New Zealand
+ [**LJmaraton** by *crtahlin*](https://crtahlin.shinyapps.io/LJmaraton): Ljubljanski maratoni
+ [**lnhBrowser** by *mlewis*](https://mlewis.shinyapps.io/lnhBrowser): Linguistic Niche Browser
+ [**location_mapper** by *cultureofinsight*](https://cultureofinsight.shinyapps.io/location_mapper): Google Location Map
+ [**loggerapp** by *microclimate*](https://microclimate.shinyapps.io/loggerapp): Microclimate logger networks
+ [**LogisticModel** by *mdpillet*](https://mdpillet.shinyapps.io/LogisticModel): Illustrating the logistic growth model
+ [**londonShiny** by *adam-dennett*](https://adam-dennett.shinyapps.io/londonShiny): Social Statistics for Wards in London
+ [**loook** by *shariliu*](https://shariliu.shinyapps.io/loook): 🔍 Loook: A tool for visualizing and analyzing infant looking time data
+ [**lorenz** by *bobturner*](https://bobturner.shinyapps.io/lorenz): Lorenz Attractor
+ [**LotkaVolterraPredPrey** by *davearmitage*](https://davearmitage.shinyapps.io/LotkaVolterraPredPrey): Predator-Prey model example
+ [**LOTR** by *sarahpapworth*](https://sarahpapworth.shinyapps.io/LOTR): Revised Life Orientation Test
+ [**love-actually-network** by *dgrtwo*](https://dgrtwo.shinyapps.io/love-actually-network): Love, Actually Network
+ [**ltwnrw17-arena** by *debatometer*](https://debatometer.shinyapps.io/ltwnrw17-arena): Debat-O-Meter: Die Wahlarena im WDR am 4. Mai 2017
+ [**ltwsh17** by *debatometer*](https://debatometer.shinyapps.io/ltwsh17): Debat-O-Meter: Die NDR-Wahlarena Schleswig-Holstein am 25. April 2017

## M
+ [**MaBapp** by *vbonapersona*](https://vbonapersona.shinyapps.io/MaBapp): MaBapp: Effects of early life adversity on behavior
+ [**macbeth** by *gdlinguistics*](https://gdlinguistics.shinyapps.io/macbeth): Macbeth Network
+ [**macro_visual** by *sautergroup*](https://sautergroup.shinyapps.io/macro_visual): fastcormics:monocyte-macrophage differentiation
+ [**mafia_ny_times** by *kostakospanos*](https://kostakospanos.shinyapps.io/mafia_ny_times): Word Cloud, NY Times articles, 2014-2016, Keyword: Mafia, by: Panos Kostakos, University of Oulu
+ [**MaicesMx50kSNP-english** by *conabio*](https://conabio.shinyapps.io/MaicesMx50kSNP-english): Mexican maize landraces genetic diversity explorer
+ [**MaicesMx50kSNP-espanol** by *conabio*](https://conabio.shinyapps.io/MaicesMx50kSNP-espanol): Explorador de la variación genética de las razas de maíz mexicanas
+ [**mammal-app** by *matthesecolab*](https://matthesecolab.shinyapps.io/mammal-app): Fantastic Beasts: Visualization of the PanTHERIA dataset
+ [**ManComp** by *resolve*](https://resolve.shinyapps.io/ManComp): Probability of Alpha Manager outperforming Beta Manager at various horizons
+ [**Manning** by *mikerspencer*](https://mikerspencer.shinyapps.io/Manning): Input Variables
+ [**ManningsConverterApp** by *johnyagecic*](https://johnyagecic.shinyapps.io/ManningsConverterApp): Manning's Input Variables
+ [**ManningsMC** by *johnyagecic*](https://johnyagecic.shinyapps.io/ManningsMC): Input Variables
+ [**manoseimas** by *petras*](https://petras.shinyapps.io/manoseimas): Interaktyvi balsavimo analizė
+ [**MapApp** by *denden*](https://denden.shinyapps.io/MapApp): FluTracking Map - data for week ending Sunday, October 20, 2019
+ [**MAPAS4** by *fjra01*](https://fjra01.shinyapps.io/MAPAS4): Crime Prediction by City
+ [**mapascultvar** by *claudia*](https://claudia.shinyapps.io/mapascultvar): Información Cultural de Coahuila
+ [**MapPortal** by *s-ic*](https://s-ic.shinyapps.io/MapPortal): Mapový portál
+ [**MAPPPD_Domain1** by *blackbawks*](https://blackbawks.shinyapps.io/MAPPPD_Domain1): Penguin colonies in CCAMLR Subarea 48.1
+ [**maps** by *bog2018*](https://bog2018.shinyapps.io/maps): Where is BoG science from?
+ [**maps** by *selfesteem*](https://selfesteem.shinyapps.io/maps): World self esteem plot
+ [**Marea** by *turfeffect*](https://turfeffect.shinyapps.io/marea): Evaluacion de Reservas Marinas
+ [**MarginalFactors** by *cedm*](https://cedm.shinyapps.io/MarginalFactors): Electricity Marginal Factors Estimates
+ [**marketing** by *gallery*](https://gallery.shinyapps.io/marketing): Radiant - Marketing
+ [**Markov-Generative-Language-Model** by *m-ezekiel*](https://m-ezekiel.shinyapps.io/Markov-Generative-Language-Model): Markov Generative Language Model
+ [**marmetadatamexeng** by *jepa*](https://jepa.shinyapps.io/marmetadatamexeng): Building a Meta-database of Marine Research in Mexico
+ [**marmetadatamexesp** by *jepa*](https://jepa.shinyapps.io/marmetadatamexesp): Hacia la creación de una base de metadatos de investigación marina en México
+ [**mars-sat** by *mars-project-sat*](https://mars-project-sat.shinyapps.io/mars-sat): MARS
+ [**marshal** by *plantmodelling*](https://plantmodelling.shinyapps.io/marshal): MARSHAL
+ [**mashup_names** by *data-chips*](https://data-chips.shinyapps.io/mashup_names): Name Mashups
+ [**master_app** by *gage-justin*](https://gage-justin.shinyapps.io/master_app): Social Listening - NYC Colleges
+ [**matrix_condenser** by *bmedeiros*](https://bmedeiros.shinyapps.io/matrix_condenser): Matrix condenser
+ [**matrixes** by *riate*](https://riate.shinyapps.io/matrixes): Convertisseur de matrices
+ [**maxent_beta_multiplier_visualiser** by *simontarr*](https://simontarr.shinyapps.io/maxent_beta_multiplier_visualiser): MaxEnt Parameter Visualiser
+ [**mc_power_med** by *schoemanna*](https://schoemanna.shinyapps.io/mc_power_med): Monte Carlo Power Analysis for Indirect Effects
+ [**mcdowell_etal_2018** by *mtn-adaptation*](https://mtn-adaptation.shinyapps.io/mcdowell_etal_2018): Adaptation action and research in glaciated mountain systems
+ [**meanSdEfficientFrontier** by *cfrm*](https://cfrm.shinyapps.io/meanSdEfficientFrontier): Mean - Standard Deviation Efficient Frontier
+ [**mecha** by *plantmodelling*](https://plantmodelling.shinyapps.io/mecha): MECHA - Model of Explicit Cross-section Hydraulic Anatomy
+ [**mechanics-of-CBM-app** by *awkruijt*](https://awkruijt.shinyapps.io/mechanics-of-CBM-app): on pre-existing bias affecting training contingency in CBM
+ [**Medical_Expense_Predictor** by *diwashrestha*](https://diwashrestha.shinyapps.io/Medical_Expense_Predictor): Medical Expense Predictor
+ [**MedicarePayments** by *gutta*](https://gutta.shinyapps.io/MedicarePayments): Know how many X you may be over-billed?
+ [**MedPower** by *davidakenny*](https://davidakenny.shinyapps.io/MedPower): Power and N Computations for Mediation
+ [**medtrucks** by *dsidd*](https://dsidd.shinyapps.io/medtrucks): Cartographie et E-santé pour hôpitaux, cliniques et associations - Luttez contre les déserts médicaux - MedTrucks
+ [**meet_summ_proto** by *safetyapp*](https://safetyapp.shinyapps.io/meet_summ_proto): Graph degeneracy and submodularity for unsupervised extractive summarization
+ [**meetingsR** by *jumpingrivers*](https://jumpingrivers.shinyapps.io/meetingsR): Worldwide R
+ [**meetup-analysis** by *pawelp*](https://pawelp.shinyapps.io/meetup-analysis): Who are attendees?
+ [**megalex** by *sedufau*](https://sedufau.shinyapps.io/megalex): Megastudies of visual and auditory word recognition
+ [**meioticdrive** by *jflh*](https://jflh.shinyapps.io/meioticdrive): Meiotic Drive for two alleles
+ [**menaro_database** by *chaiml*](https://chaiml.shinyapps.io/menaro_database): Years of experience
+ [**Meropenem_for_OPAT** by *opat*](https://opat.shinyapps.io/Meropenem_for_OPAT): Meropenem for Outpatient Parenteral Antimicrobial Thearpy
+ [**MetaForest_online** by *utrecht-university*](https://utrecht-university.shinyapps.io/MetaForest_online): MetaForest Online
+ [**metainsightc** by *crsu*](https://crsu.shinyapps.io/metainsightc): MetaInsight
+ [**method_compare** by *bahar*](https://bahar.shinyapps.io/method_compare): Method Comparison
+ [**metro_walksheds** by *johnricco*](https://johnricco.shinyapps.io/metro_walksheds): Walk sheds by Metrorail line: A data visualization
+ [**microglia** by *vmenon*](https://vmenon.shinyapps.io/microglia): Human microglia single-cell expression (Olah et al. 2019)
+ [**migrationviz** by *asheshwor*](https://asheshwor.shinyapps.io/migrationviz): Mapping international migration flows from UN migrants stock data
+ [**milkPrice** by *dhaine*](https://dhaine.shinyapps.io/milkPrice): Milk Prices Comparison
+ [**minha-cidade** by *nazareno*](https://nazareno.shinyapps.io/minha-cidade): De onde vem a verba das campanhas de sua cidade?
+ [**mining_my_day** by *regan008*](https://regan008.shinyapps.io/mining_my_day): Mining the Eleanor Roosevelt My Day Columns
+ [**misanthrope_app** by *dnlmc*](https://dnlmc.shinyapps.io/misanthrope_app): Misanthropic Neighbors Simulation
+ [**MLB_franchise_performance** by *wallach*](https://wallach.shinyapps.io/MLB_franchise_performance): Historical Performance of Major League Baseball Franchises
+ [**mlbDashboard** by *dnegrey*](https://dnegrey.shinyapps.io/mlbDashboard): MLB Dashboard
+ [**MLBrunscoring_shiny** by *monkmanmh*](https://monkmanmh.shinyapps.io/MLBrunscoring_shiny): MLB run scoring trends
+ [**mlplasmids** by *sarredondo*](https://sarredondo.shinyapps.io/mlplasmids): mlplasmids
+ [**mlsn_K** by *asianturfgrass*](https://asianturfgrass.shinyapps.io/mlsn_K): K requirement using the MLSN Guidelines
+ [**MME_Global** by *iupui-earth-science*](https://iupui-earth-science.shinyapps.io/MME_Global): Map My Environment: Global
+ [**Model2** by *oncoresearch*](https://oncoresearch.shinyapps.io/Model2): Enter Your Information
+ [**MOG_education** by *webb*](https://webb.shinyapps.io/MOG_education): Mapping Overlaps Gadget
+ [**moonBook** by *cardiomoon*](https://cardiomoon.shinyapps.io/moonBook): Web-R.org
+ [**mortgage2** by *lcolladotor*](https://lcolladotor.shinyapps.io/mortgage2): Simple Mortgage Calculator
+ [**mote** by *doomlab*](https://doomlab.shinyapps.io/mote): MOTE
+ [**movethevote** by *movethevote*](https://movethevote.shinyapps.io/movethevote): Move the Vote
+ [**movie_loc** by *yabinfan*](https://yabinfan.shinyapps.io/movie_loc): NYC Movie Spot
+ [**movierecommendationlpufinalproject** by *arvindkr*](https://arvindkr.shinyapps.io/movierecommendationlpufinalproject): Movie Recommendation System
+ [**movies** by *winston*](https://winston.shinyapps.io/movies): Movie explorer
+ [**mRchmadness** by *saberpowers*](https://saberpowers.shinyapps.io/mRchmadness): mRchmadness: 2018
+ [**MRP_territorios** by *lmolla*](https://lmolla.shinyapps.io/MRP_territorios): MRP Preelectoral CIS 10-N
+ [**MSE_Southern_Hake** by *jcquiroz*](https://jcquiroz.shinyapps.io/MSE_Southern_Hake): MSUR - Visual app
+ [**msm-shiny** by *stulacy*](https://stulacy.shinyapps.io/msm-shiny): Multi-State Modelling
+ [**MSTgraphics** by *moral*](https://moral.shinyapps.io/MSTgraphics): Moral Sense Test
+ [**music** by *jalapic*](https://jalapic.shinyapps.io/music): Music Notation Plots of Social Interactions
+ [**mutation_selection_shiny** by *brianomeara*](https://brianomeara.shinyapps.io/mutation_selection_shiny): Mutation Selection (Macroevolution class, Brian O'Meara)
+ [**my_app** by *michaellopez*](https://michaellopez.shinyapps.io/my_app): Density plots of per-game QBR
+ [**myrcharts0** by *herimanitra*](https://herimanitra.shinyapps.io/myrcharts0): shiny, rCharts and Highcharts.js:
+ [**mysteps** by *weekendarchaeo*](https://weekendarchaeo.shinyapps.io/mysteps): Steps Record

## N
+ [**NAIABaseballStatistics** by *robertlfrey*](https://robertlfrey.shinyapps.io/NAIABaseballStatistics): NAIA Baseball Statistics
+ [**NAMCShiny** by *jefworks*](https://jefworks.shinyapps.io/NAMCShiny): NAMCShiny
+ [**NarReport** by *vzaigrin*](https://vzaigrin.shinyapps.io/NarReport): Instructions
+ [**national-security-strategy** by *dartthrowingchimp*](https://dartthrowingchimp.shinyapps.io/national-security-strategy): Exploring the U.S. National Security Strategy Reports
+ [**nationals15** by *ryandkerr*](https://ryandkerr.shinyapps.io/nationals15): 2015 College Ultimate Nationals - Men's and Women's
+ [**naturespostcodes** by *tomaugust*](https://tomaugust.shinyapps.io/naturespostcodes): Nature's Postcodes
+ [**navlistpanel-example** by *gallery*](https://gallery.shinyapps.io/navlistpanel-example): Navlist panel example
+ [**nba-play-type** by *presidual*](https://presidual.shinyapps.io/nba-play-type): NBA Team Play Type Breakdowns (beta)
+ [**nba-rolling-charts** by *presidual*](https://presidual.shinyapps.io/nba-rolling-charts): NBA Team Rolling Charts and Statistics
+ [**NBA-shot-range** by *scott-laforest*](https://scott-laforest.shinyapps.io/NBA-shot-range): NBA Shot Range Emoji Charts
+ [**nba_draft_by_team** by *dantok18*](https://dantok18.shinyapps.io/nba_draft_by_team): NBA Draft Data by Team (1989-2017)
+ [**nba_playoff_series_predictions_multinomial_regression** by *steadylosing*](https://steadylosing.shinyapps.io/nba_playoff_series_predictions_multinomial_regression): NBA Best-of-Seven Showdowns: Predictions -- It's Lit
+ [**nbafinalshistory** by *adp2223*](https://adp2223.shinyapps.io/nbafinalshistory): NBA Finals Series History
+ [**NBAShotChart** by *jiashenliu*](https://jiashenliu.shinyapps.io/NBAShotChart): NBA Shot Plot
+ [**NBAStatsExplorer** by *jcohensolal*](https://jcohensolal.shinyapps.io/NBAStatsExplorer): NBA Player Stats Explorer
+ [**ncaa** by *bracketmath*](https://bracketmath.shinyapps.io/ncaa): March Madness Optimization
+ [**nCov_control** by *art-bd*](https://art-bd.shinyapps.io/nCov_control): Reporting, epidemic growth, and reproduction numbers for the 2019-nCoV epidemic: understanding control
+ [**ncov_tracker** by *vac-lshtm*](https://vac-lshtm.shinyapps.io/ncov_tracker): Covid 2019 tracker
+ [**NDC_Evaluation** by *gicn*](https://gicn.shinyapps.io/NDC_Evaluation): The NDC app: Estimating GHG emissions in 2030
+ [**Nets-Shiny** by *andywon*](https://andywon.shinyapps.io/Nets-Shiny): The Brooklyn Nets Performance by Game
+ [**NetworkApp** by *jolandakos*](https://jolandakos.shinyapps.io/NetworkApp): Network App
+ [**networkgraph** by *jing-zen-garden*](https://jing-zen-garden.shinyapps.io/networkgraph): NetworkAnalysis
+ [**NeuroimagingLandscape** by *jdwor*](https://jdwor.shinyapps.io/NeuroimagingLandscape): The Landscape of NeuroImage-ing Research
+ [**neuromast_homeostasis_scrnaseq_2018** by *piotrowskilab*](https://piotrowskilab.shinyapps.io/neuromast_homeostasis_scrnaseq_2018): Zebrafish Neuromast scRNA-seq
+ [**neuropower** by *neuropower*](https://neuropower.shinyapps.io/neuropower): NeuroPower
+ [**new-test** by *bencasselman*](https://bencasselman.shinyapps.io/new-test): Select a category of major:
+ [**new_app** by *lynch-interactive-animations*](https://lynch-interactive-animations.shinyapps.io/new_app): The effect of occupation on migrations
+ [**new_outbreak_probability** by *cmmid-lshtm*](https://cmmid-lshtm.shinyapps.io/new_outbreak_probability): Probability of a large 2019-nCoV outbreak following introduction of cases
+ [**newselection** by *comparenjschools*](https://comparenjschools.shinyapps.io/newselection): This website uses the 2016-2017 State Performance Data. Using Artificial Intelligence algorithms the program will assimilate similar schools to the one you designate up top. There are also options for you to customize schools you wish to compare that were not deemed similar according to the algorithm.
+ [**newstart** by *steadylosing*](https://steadylosing.shinyapps.io/newstart): Likely or No? -- NBA Predictions Set
+ [**Next_Word_Prediction** by *anmuz*](https://anmuz.shinyapps.io/Next_Word_Prediction): Capstone Project
+ [**NextWordApp** by *massyfigini*](https://massyfigini.shinyapps.io/NextWordApp): The Next Word App
+ [**NextWordPrediction** by *iyermobile*](https://iyermobile.shinyapps.io/NextWordPrediction): iyermobile - CAPSTONE PROJECT
+ [**NextWordPrediction** by *johnakwei1*](https://johnakwei1.shinyapps.io/NextWordPrediction): Next Word Prediction App - by ContextBase
+ [**NFLAnalitics** by *gavilez*](https://gavilez.shinyapps.io/NFLAnalitics): NFL Fantasy Analisis
+ [**ngram** by *gill*](https://gill.shinyapps.io/ngram): NGram Performance Analysis
+ [**ngram** by *odeleon*](https://odeleon.shinyapps.io/ngram): Using the app
+ [**ngram** by *wrathematics*](https://wrathematics.shinyapps.io/ngram): Fun with Markov Chains
+ [**nhanes_explore** by *tladeras*](https://tladeras.shinyapps.io/nhanes_explore): NHANES
+ [**NHPubSchools** by *nhschoolfunds*](https://nhschoolfunds.shinyapps.io/NHPubSchools): New Hampshire Public Schools Financial Data FY2009-FY2019
+ [**ninja** by *sieriebriennikov*](https://sieriebriennikov.shinyapps.io/ninja): NINJA: Nematode INdicator Joint Analysis
+ [**nkrBaby** by *lenalyticslab*](https://lenalyticslab.shinyapps.io/nkrBaby): Nakuru Hospital Newborns Dashboard
+ [**nlpshiny** by *yufree*](https://yufree.shinyapps.io/nlpshiny): Data Science Capstone: Simple SwiftKey
+ [**nmdescintolerancescore** by *nmdprediction*](https://nmdprediction.shinyapps.io/nmdescintolerancescore): NMD Escape intolerance score metric
+ [**nmdescpredictor** by *nmdprediction*](https://nmdprediction.shinyapps.io/nmdescpredictor): NMDEscPredictor
+ [**noaaShiny** by *heatherkitada*](https://heatherkitada.shinyapps.io/noaaShiny): NOAA Fishing Effort
+ [**NormalDist** by *istats*](https://istats.shinyapps.io/NormalDist): Normal Dist
+ [**np-quake** by *asheshwor*](https://asheshwor.shinyapps.io/np-quake): Quake timeline
+ [**nwpgame** by *micasagroup*](https://micasagroup.shinyapps.io/nwpgame): Next Word Prediction
+ [**NY-Influence** by *johnrroby*](https://johnrroby.shinyapps.io/NY-Influence): Explore drug industry contributions in New York
+ [**NYC_311_Dashboard** by *isaac-michaels*](https://isaac-michaels.shinyapps.io/NYC_311_Dashboard): Service Requests
+ [**nyc_jail_population** by *vera-institute*](https://vera-institute.shinyapps.io/nyc_jail_population): JailVizNYC
+ [**nyc_noises** by *adamgao666*](https://adamgao666.shinyapps.io/nyc_noises): Noises Around You
+ [**nyc_sat** by *rich*](https://rich.shinyapps.io/nyc_sat): NYC High School Mean SAT and AP Score Analysis
+ [**NYC_Toilet_Map** by *chenluji*](https://chenluji.shinyapps.io/NYC_Toilet_Map): DIDI Toilets
+ [**nycwater** by *cks1001652*](https://cks1001652.shinyapps.io/nycwater): Exploring NYC's Water
+ [**NYT-bar-optimizer** by *gallery*](https://gallery.shinyapps.io/NYT-bar-optimizer): About this app
+ [**nz-election-2017** by *ellisp*](https://ellisp.shinyapps.io/nz-election-2017): Forecasts for New Zealand General Election 2017
+ [**NZ-general-election-2014** by *ellisp*](https://ellisp.shinyapps.io/NZ-general-election-2014): New Zealand General Election 2014 'party vote' results by voting place
+ [**nz-health-survey-2016-17-tier-1** by *minhealthnz*](https://minhealthnz.shinyapps.io/nz-health-survey-2016-17-tier-1): minhealthnz.shinyapps.io
+ [**nz-health-survey-2018-19-annual-data-explorer** by *minhealthnz*](https://minhealthnz.shinyapps.io/nz-health-survey-2018-19-annual-data-explorer): About
+ [**nzcensus-cartograms** by *ellisp*](https://ellisp.shinyapps.io/nzcensus-cartograms): New Zealand on census night 2013, at a glance
+ [**nzes2014_x_by_party** by *ellisp*](https://ellisp.shinyapps.io/nzes2014_x_by_party): Party vote characteristics at the New Zealand General Election 2014
+ [**NZX_Share_Price_Prediction** by *transbig*](https://transbig.shinyapps.io/NZX_Share_Price_Prediction): NZX Share Price Prediction Web App

## O
+ [**oakbirdpop** by *aknw*](https://aknw.shinyapps.io/oakbirdpop): Oak Bird Pop
+ [**oba1** by *biotransformers*](https://biotransformers.shinyapps.io/oba1): OBA
+ [**obsbrain** by *conxz*](https://conxz.shinyapps.io/obsbrain): obsBrain: Observatory of Brain
+ [**ODdash_v1** by *pdop*](https://pdop.shinyapps.io/ODdash_v1): The California Opioid Surveillance Dashboard has moved!
+ [**ODSI_continuousData** by *minnier*](https://minnier.shinyapps.io/ODSI_continuousData): Continuous Data
+ [**OECD** by *mytinyshinys*](https://mytinyshinys.shinyapps.io/OECD): OECD
+ [**OH_Medical_Treat_Toxin** by *arka1985*](https://arka1985.shinyapps.io/OH_Medical_Treat_Toxin): Medical Management Guidelines for Toxic Substances
+ [**OLS-App** by *econometricsbysimulation*](https://econometricsbysimulation.shinyapps.io/OLS-App): Ordinary Least Squares
+ [**olympics** by *cadolph*](https://cadolph.shinyapps.io/olympics): Who’s Winning the Olympics?
+ [**OnlineApp** by *flore*](https://flore.shinyapps.io/OnlineApp): A vous de jouer !
+ [**open-science-networks** by *subugoe*](https://subugoe.shinyapps.io/open-science-networks): European Open Science Networks (Beta)
+ [**openAnalysis** by *hdoran*](https://hdoran.shinyapps.io/openAnalysis): Toolbar
+ [**openfda-dashboard** by *diabetescheck*](https://diabetescheck.shinyapps.io/openfda-dashboard): FDA Adverse Event Dashboard
+ [**opioid_rx_rate** by *natea*](https://natea.shinyapps.io/opioid_rx_rate): Opioid Prescribing Rate Visualizations
+ [**OpioidActionPlan** by *injuryfreenc*](https://injuryfreenc.shinyapps.io/OpioidActionPlan): NC Opioid Dashboard
+ [**optimal_identification** by *mmcbee*](https://mmcbee.shinyapps.io/optimal_identification): Optimal Gifted Identification
+ [**orcid** by *aushsi*](https://aushsi.shinyapps.io/orcid): Reducing the administrative burden on researchers
+ [**oreilly_data_science_salary** by *yasserglez*](https://yasserglez.shinyapps.io/oreilly_data_science_salary): O'Reilly ‘2015 Data Science Salary Survey’ models
+ [**osf_shinyapp** by *kissel*](https://kissel.shinyapps.io/osf_shinyapp): Population supplemenation options for the Oregon spotted frog in British Columbia
+ [**Overall_ecosystem_stability_demo** by *frankpennekamp*](https://frankpennekamp.shinyapps.io/Overall_ecosystem_stability_demo): Overall ecosystem stability
+ [**Overplots** by *johnyagecic*](https://johnyagecic.shinyapps.io/Overplots): Input Variables
+ [**OxRep_maps_mines** by *livedataoxford*](https://livedataoxford.shinyapps.io/OxRep_maps_mines): Oxford Roman Economy Project

## P
+ [**p-curves** by *lakens*](https://lakens.shinyapps.io/p-curves): Distribution of Cohen's d, p-values, and power curves for an independent two-tailed t-test
+ [**p-uniform** by *rvanaert*](https://rvanaert.shinyapps.io/p-uniform): Web application p-uniform
+ [**p_mercado_dia_qro** by *detags*](https://detags.shinyapps.io/p_mercado_dia_qro): Detags
+ [**Pages** by *languagevariationsuite*](https://languagevariationsuite.shinyapps.io/Pages): Language Variation Suite (LVS)
+ [**pairs_graphicalvar** by *emoriebeck*](https://emoriebeck.shinyapps.io/pairs_graphicalvar): Idiographic Networks
+ [**pangea** by *jakewestfall*](https://jakewestfall.shinyapps.io/pangea): PANGEA: Power ANalysis for GEneral Anova designs
+ [**papr** by *jhubiostatistics*](https://jhubiostatistics.shinyapps.io/papr): papr - peer review, but easier
+ [**PARCIs** by *spirikahu*](https://spirikahu.shinyapps.io/PARCIs): Confidence Intervals for Population Attributable Risk
+ [**Parks** by *mhairi*](https://mhairi.shinyapps.io/Parks): Edinburgh Parks
+ [**Parliament** by *pitakakariki*](https://pitakakariki.shinyapps.io/Parliament): New Zealand Parliament
+ [**part1_devdataprod-shiny** by *swhgoon*](https://swhgoon.shinyapps.io/part1_devdataprod-shiny): mtcars dataset
+ [**partyExplorer** by *tladeras*](https://tladeras.shinyapps.io/partyExplorer): Tree Analysis
+ [**patek13** by *samizdat*](https://samizdat.shinyapps.io/patek13): Kolik pátků třináctého jste už zažili?
+ [**pc_delegate_tracker** by *tomstringham*](https://tomstringham.shinyapps.io/pc_delegate_tracker): PC Alberta Leadership Delegate Tracker
+ [**pces** by *blakemcshane*](https://blakemcshane.shinyapps.io/pces): Power-Calibrated Effect Size (PCES)
+ [**pD_app** by *johnlray*](https://johnlray.shinyapps.io/pD_app): Death Probability by Demographic Group
+ [**PenalizedRegression** by *andland*](https://andland.shinyapps.io/PenalizedRegression): Penalized Regression
+ [**Percy_Has_Neural_Gas** by *asbcllc*](https://asbcllc.shinyapps.io/Percy_Has_Neural_Gas): Percival Bresler's Got Neural Gas
+ [**PerformanceMeasures** by *cfrm*](https://cfrm.shinyapps.io/PerformanceMeasures): Performance Measures
+ [**PerformanceWebapp** by *applocation*](https://applocation.shinyapps.io/PerformanceWebapp): MMDAT
+ [**Permits** by *yvelez*](https://yvelez.shinyapps.io/Permits): Protest Permits
+ [**PERS-calc** by *kesh-lab*](https://kesh-lab.shinyapps.io/PERS-calc): Sample Psychosis Risk Prediction Calculator
+ [**perseus** by *rafaelmenmell*](https://rafaelmenmell.shinyapps.io/perseus): Web Scraping and Text Mining in Ancient Sources
+ [**Person_App** by *domrussel*](https://domrussel.shinyapps.io/Person_App): The Identity Generator
+ [**personal** by *pablovicentemunuera*](https://pablovicentemunuera.shinyapps.io/personal): Pablo Vicente Munuera
+ [**pet-records-app** by *jennadallen*](https://jennadallen.shinyapps.io/pet-records-app): Pet Records
+ [**petroglifos_galicia** by *c-rellan*](https://c-rellan.shinyapps.io/petroglifos_galicia): Arte rupestre galega
+ [**phenome_bingo** by *plantmodelling*](https://plantmodelling.shinyapps.io/phenome_bingo): Conference bingo!
+ [**Philly-Crime-Parts-I-II** by *miningthedetails*](https://miningthedetails.shinyapps.io/Philly-Crime-Parts-I-II): Philadelphia Crime Statistics
+ [**photo-voltaic-growth** by *acuariano*](https://acuariano.shinyapps.io/photo-voltaic-growth): Solar photo-voltaic capacity growth
+ [**phyllotaxis3d** by *cortinah*](https://cortinah.shinyapps.io/phyllotaxis3d): Phyllotaxis in 3D by @cortinah
+ [**physical_network** by *robertcope*](https://robertcope.shinyapps.io/physical_network): Physical transport network into Australia
+ [**phyteauviz** by *pedagueau*](https://pedagueau.shinyapps.io/phyteauviz): Phyt'eau viz
+ [**pickles** by *hartlab*](https://hartlab.shinyapps.io/pickles): Loading...
+ [**pimpMyShiny** by *dreamrs-fan*](https://dreamrs-fan.shinyapps.io/pimpMyShiny): Bienvenue dans l'application pimpée sur les R Addicts !
+ [**PingPongUH** by *rodlammers*](https://rodlammers.shinyapps.io/PingPongUH): Inputs
+ [**pips** by *pittsburghpa*](https://pittsburghpa.shinyapps.io/pips): Broadband Internet Coverage in Pittsburgh, PA: June 2016
+ [**PiSimulations** by *bgstieber*](https://bgstieber.shinyapps.io/PiSimulations): Simulating pi
+ [**Plan4Heat** by *greensway*](https://greensway.shinyapps.io/Plan4Heat): Plan4Heat
+ [**playoff_simulator** by *dantok18*](https://dantok18.shinyapps.io/playoff_simulator): Simulating an NBA Playoff Series
+ [**plebiscito** by *randommonkey*](https://randommonkey.shinyapps.io/plebiscito): Cargando...
+ [**ploption** by *trading*](https://trading.shinyapps.io/ploption): Ploption: A P&L tool for Plotting Options
+ [**plotlylayout** by *paulcbauer*](https://paulcbauer.shinyapps.io/plotlylayout): Plotly: Styling the layout by Paul C. Bauer Tweet
+ [**plotlymarkers** by *paulcbauer*](https://paulcbauer.shinyapps.io/plotlymarkers): Plotly: Styling the markers by Paul C. Bauer Tweet
+ [**plotROC** by *sachsmc*](https://sachsmc.shinyapps.io/plotROC): ROC Plot
+ [**pmi_calculator** by *acsgcipr-predictpmi*](https://acsgcipr-predictpmi.shinyapps.io/pmi_calculator): PMI Calculator
+ [**pmsignature_shiny** by *friend1ws*](https://friend1ws.shinyapps.io/pmsignature_shiny): pmsignture for shiny
+ [**PNW_Webpage** by *pnw-science*](https://pnw-science.shinyapps.io/PNW_Webpage): Welcome to the Pacific Northwest Regional Science Fair!
+ [**pogoda** by *openmeteo*](https://openmeteo.shinyapps.io/pogoda): Przeglądarka archiwalnych danych meteorologicznych
+ [**Point_Diff_Shiny** by *mattmills49*](https://mattmills49.shinyapps.io/Point_Diff_Shiny): Play by Play College Football Point Differentials
+ [**poker-variance-app** by *ibombonato*](https://ibombonato.shinyapps.io/poker-variance-app): Poker variance
+ [**PoliticalSpeechProject** by *rania*](https://rania.shinyapps.io/PoliticalSpeechProject): PSP
+ [**pollsavvy** by *pollsavvy*](https://pollsavvy.shinyapps.io/pollsavvy): PollSavvy
+ [**polMonitor** by *ewenme*](https://ewenme.shinyapps.io/polMonitor): polMonitor
+ [**population-estimates** by *scotland*](https://scotland.shinyapps.io/population-estimates): Population Estimates of Scotland - National Records of Scotland
+ [**population-projection-variants-scotland-uk** by *scotland*](https://scotland.shinyapps.io/population-projection-variants-scotland-uk): Population projections of Scotland - National Records of Scotland
+ [**PosiPredVal** by *acarloto*](https://acarloto.shinyapps.io/PosiPredVal): Disease Probability Given a Positive Diagnostic Test
+ [**positions** by *gamma-trader*](https://gamma-trader.shinyapps.io/positions): G.O. Positions Watch
+ [**posr** by *plantid*](https://plantid.shinyapps.io/posr): Plants of the Shoalhaven Region
+ [**postElection** by *jackman*](https://jackman.shinyapps.io/postElection): Performance of Sportsbet seat-by-seat market prices, 2016 Australian election results as of 7am 27 September 2016 AEST
+ [**power** by *istats*](https://istats.shinyapps.io/power): Errors & Power
+ [**power** by *sb452*](https://sb452.shinyapps.io/power): Online sample size and power calculator for Mendelian randomization with a binary outcome
+ [**power-app** by *egap*](https://egap.shinyapps.io/power-app): Power Calculator
+ [**Power_Calculator** by *egap*](https://egap.shinyapps.io/Power_Calculator): Power Calculator
+ [**Powerball** by *dvcv*](https://dvcv.shinyapps.io/Powerball): Powerball
+ [**powerplants** by *jianhua*](https://jianhua.shinyapps.io/powerplants): U.S. Powerplants
+ [**ppfd_by_time** by *asianturfgrass*](https://asianturfgrass.shinyapps.io/ppfd_by_time): PPFD and DLI by time, day, latitude, and longitude.
+ [**PRECISE** by *mjha*](https://mjha.shinyapps.io/PRECISE): PRECISE: Proteomic based integrated subject-specific networks in cancer
+ [**precisely** by *malcolmbarrett*](https://malcolmbarrett.shinyapps.io/precisely): Estimate Sample Size Based on Precision
+ [**precpbnu** by *fcdidone*](https://fcdidone.shinyapps.io/precpbnu): Precipitação em Blumenau
+ [**predict_real_estate_price** by *fbarth*](https://fbarth.shinyapps.io/predict_real_estate_price): Residential Real Estate Prices Prediction
+ [**predicter** by *estech*](https://estech.shinyapps.io/predicter): PredicTER
+ [**prediction_shinyApp** by *sayandev*](https://sayandev.shinyapps.io/prediction_shinyApp): Data Science Capstone: Text Prediction Engine
+ [**PredWord** by *abhishekumrawal*](https://abhishekumrawal.shinyapps.io/PredWord): PredWord
+ [**preferences** by *ipwenergy*](https://ipwenergy.shinyapps.io/preferences): Energie-Enquete 2016 - Erste Einblicke
+ [**premierleague** by *algospark*](https://algospark.shinyapps.io/premierleague): Premier League Predictor
+ [**premierLeague** by *mytinyshinys*](https://mytinyshinys.shinyapps.io/premierLeague): BPL
+ [**premium_map** by *nycschoolcost*](https://nycschoolcost.shinyapps.io/premium_map): Price Differences Across New York City School Zones
+ [**PreopDrugs** by *dannyjnwong*](https://dannyjnwong.shinyapps.io/PreopDrugs): Preop Medication Advice v0.1
+ [**presentation** by *herimanitra*](https://herimanitra.shinyapps.io/presentation): Presentation
+ [**presentation_jmlr_15_delgado14a** by *albahnsen*](https://albahnsen.shinyapps.io/presentation_jmlr_15_delgado14a): Paper - DWNHC
+ [**Presidential_Approval_Ratings_Developing_Data_Products** by *shdurham*](https://shdurham.shinyapps.io/Presidential_Approval_Ratings_Developing_Data_Products): Summarized Presidential Approval Ratings (1945-1974)
+ [**Presidential_Rankings** by *acm9q*](https://acm9q.shinyapps.io/Presidential_Rankings): US Presidential Rankings
+ [**ProbApp** by *ismay*](https://ismay.shinyapps.io/ProbApp): Calculator for Probability Distributions by Chester Ismay and Logan Soich
+ [**probitProportions** by *richarddmorey*](https://richarddmorey.shinyapps.io/probitProportions): Probit Bayes factor (two proportions)
+ [**problemas** by *juliomulero*](https://juliomulero.shinyapps.io/problemas): Problemas
+ [**process_nhanes_app** by *jhubiostatistics*](https://jhubiostatistics.shinyapps.io/process_nhanes_app): Web App for Processing NHANES Accelerometer Data
+ [**Project** by *amritpatel*](https://amritpatel.shinyapps.io/Project): 2015 NCAAB Tournament Predictor
+ [**project** by *rgferreira*](https://rgferreira.shinyapps.io/project): Interactive 3D plot for mtcars data set
+ [**project_develdataprod** by *juaparal*](https://juaparal.shinyapps.io/project_develdataprod): Developing Data Products Project
+ [**Project_Iris** by *inudaiskii*](https://inudaiskii.shinyapps.io/Project_Iris): Plotting Iris with Shiny Application
+ [**PROMISS** by *riskcalculator*](https://riskcalculator.shinyapps.io/PROMISS): CANARY-EDRN ACTIVE SURVEILLANCE BIOPSY RISK CALCULATOR (ABC)
+ [**prophet_explore** by *omaymas*](https://omaymas.shinyapps.io/prophet_explore): Prophet Explorer
+ [**prospecttheory** by *marcelogelati*](https://marcelogelati.shinyapps.io/prospecttheory): Navegação
+ [**providence_viewer** by *dgrtwo*](https://dgrtwo.shinyapps.io/providence_viewer): How StackOverflow Sees You
+ [**PSA_Velocity** by *zx8754*](https://zx8754.shinyapps.io/PSA_Velocity): PSA Velocity
+ [**psychRisk** by *leobrueg*](https://leobrueg.shinyapps.io/psychRisk): psychRisk
+ [**public_sector_employment** by *mroutley*](https://mroutley.shinyapps.io/public_sector_employment): Public-sector employment in Ontario
+ [**PulseWaveSync_2_1** by *pulsewavesync*](https://pulsewavesync.shinyapps.io/PulseWaveSync_2_1): PulseWaveSync2.1
+ [**pvalueviz** by *peerjeda*](https://peerjeda.shinyapps.io/pvalueviz): What do p-values look like?

## Q
+ [**qualite-des-eaux** by *ssm-ecologie*](https://ssm-ecologie.shinyapps.io/qualite-des-eaux): Les pesticides dans les cours d'eau des Pays de la Loire
+ [**quantgensimAPP** by *mgstetter*](https://mgstetter.shinyapps.io/quantgensimAPP): Genetic architecture and selective sweeps after polygenic adaptation to distant trait optima
+ [**QueenOfHearts** by *gjkerns*](https://gjkerns.shinyapps.io/QueenOfHearts): Queen of Hearts
+ [**QuoiR** by *wuli*](https://wuli.shinyapps.io/QuoiR): QuoiR

## R
+ [**R-Cube** by *randomwalker*](https://randomwalker.shinyapps.io/R-Cube): R Cube
+ [**r-tags** by *omaymas*](https://omaymas.shinyapps.io/r-tags): R Questions Tag Pairs on Stackoverflow
+ [**r11_app** by *usda*](https://usda.shinyapps.io/r11_app): Region 11 Web App
+ [**R_from_Stata** by *rslbliss*](https://rslbliss.shinyapps.io/R_from_Stata): To R from Stata: An Introduction
+ [**R_Programming** by *f3rdata*](https://f3rdata.shinyapps.io/R_Programming): Word Cloud
+ [**r_regex_tester** by *spannbaueradam*](https://spannbaueradam.shinyapps.io/r_regex_tester): R Regex Tester
+ [**R_social_data_analytics** by *curiositybits*](https://curiositybits.shinyapps.io/R_social_data_analytics): An interactive tutorial for COMM 497DB
+ [**radiant** by *vnijs*](https://vnijs.shinyapps.io/radiant): Radiant
+ [**railtrails** by *jmichaelrosenberg*](https://jmichaelrosenberg.shinyapps.io/railtrails): Find the top rail-trails (using reviews from TrailLink)
+ [**raincloudplots** by *gabrifc*](https://gabrifc.shinyapps.io/raincloudplots): Raincloud-shiny
+ [**random_gen** by *aurora*](https://aurora.shinyapps.io/random_gen): Randomization table for clinical trials!
+ [**random_mixing_PWID_models** by *rapmasterhap*](https://rapmasterhap.shinyapps.io/random_mixing_PWID_models): Random mixing & HIV prevention for PWID
+ [**ratp_traffic** by *dreamrs-phi*](https://dreamrs-phi.shinyapps.io/ratp_traffic): Le Métro parisien en 2017
+ [**rcc-risk-calculator** by *rgulati*](https://rgulati.shinyapps.io/rcc-risk-calculator): A risk calculator for a patient with clinical T1 renal cortical mass ≤ 7 cm
+ [**rcheology** by *hughjonesd*](https://hughjonesd.shinyapps.io/rcheology): Base R Functions from R 1.0.1 onwards
+ [**reactive-poll-and-file-reader** by *gallery*](https://gallery.shinyapps.io/reactive-poll-and-file-reader): reactivePoll and reactiveFileReader
+ [**recount** by *jhubiostatistics*](https://jhubiostatistics.shinyapps.io/recount): recount2: analysis-ready RNA-seq gene and exon counts datasets
+ [**recspecs_basketball_central** by *lbenz730*](https://lbenz730.shinyapps.io/recspecs_basketball_central): recspecs730 Basketball Central
+ [**red_trenes** by *frannetworks*](https://frannetworks.shinyapps.io/red_trenes): Introducción a la Teoría de Redes
+ [**redlight** by *miningchi2*](https://miningchi2.shinyapps.io/redlight): Accident Analysis for Chicago
+ [**ref2014** by *ttso*](https://ttso.shinyapps.io/ref2014): Keyword relevance and sentiment
+ [**regimes-of-the-world** by *tannenberg*](https://tannenberg.shinyapps.io/regimes-of-the-world): Regimes of the World
+ [**regression_plus** by *dgolicher-bu*](https://dgolicher-bu.shinyapps.io/regression_plus): Linear regression + other options
+ [**regressiontomean** by *andyf*](https://andyf.shinyapps.io/regressiontomean): Simulate regression to the mean
+ [**RegularExpressionR** by *simongoring*](https://simongoring.shinyapps.io/RegularExpressionR): Regular Expression Testing
+ [**repair_app_submit** by *vbonapersona*](https://vbonapersona.shinyapps.io/repair_app_submit): RePAIR
+ [**reports** by *nomoremarking*](https://nomoremarking.shinyapps.io/reports): No More Marking
+ [**ResearchProgramStrategy** by *antoniakrefeldschwalb*](https://antoniakrefeldschwalb.shinyapps.io/ResearchProgramStrategy): Evaluate the trustworthiness of your study!
+ [**resistmixseq** by *andysouth*](https://andysouth.shinyapps.io/resistmixseq): resistance to insecticide mixtures
+ [**resourceprice** by *andrewjgillen*](https://andrewjgillen.shinyapps.io/resourceprice): How Have Resource Prices Changed Over Time | Simon vs. Ehrlich Bet
+ [**Retirement** by *bcrossman*](https://bcrossman.shinyapps.io/Retirement): Retirement
+ [**retirement** by *gallery*](https://gallery.shinyapps.io/retirement): Retirement: simulating wealth with random returns, inflation and withdrawals
+ [**retractcheck_shinyapp** by *frederikaust*](https://frederikaust.shinyapps.io/retractcheck_shinyapp): retractcheck
+ [**RevoBlogApp** by *revolutionanalyticssid*](https://revolutionanalyticssid.shinyapps.io/RevoBlogApp): An Interactive Graph
+ [**rfb-explorer** by *conflictmetrics*](https://conflictmetrics.shinyapps.io/rfb-explorer): Russian Facebook Ads Data Explorer
+ [**rioweb** by *gallery*](https://gallery.shinyapps.io/rioweb): Output format
+ [**riskApp** by *melondonkey*](https://melondonkey.shinyapps.io/riskApp): Risk
+ [**rivals_shiny** by *nickbloom*](https://nickbloom.shinyapps.io/rivals_shiny): Mapping the Rivals 100, Interactive Edition
+ [**river_sunburst** by *nddeepak*](https://nddeepak.shinyapps.io/river_sunburst): Whole-Part
+ [**river_water_quality_nitrogen** by *statisticsnz*](https://statisticsnz.shinyapps.io/river_water_quality_nitrogen): River nitrogen
+ [**rmd_templates_on_cran** by *haozhu233*](https://haozhu233.shinyapps.io/rmd_templates_on_cran): RMD templates on CRAN
+ [**rnc-charlotte** by *wesslen*](https://wesslen.shinyapps.io/rnc-charlotte): Charlotte-RNC 2020 Tweets
+ [**rnomads_model_change** by *jpn5089*](https://jpn5089.shinyapps.io/rnomads_model_change): Exploring the rNOMADS Package
+ [**ROC-Curves** by *kennis-research*](https://kennis-research.shinyapps.io/ROC-Curves): Receiver Operating Characteristic (ROC) Curves
+ [**roc-precision-recall** by *rafalab*](https://rafalab.shinyapps.io/roc-precision-recall): ROC to precision-recall curve translator
+ [**roc_wage_data** by *cjf4*](https://cjf4.shinyapps.io/roc_wage_data): Rochester, NY Wage Data 2011-2015
+ [**roman_empire** by *kamilgregor*](https://kamilgregor.shinyapps.io/roman_empire): Roman Empire Year by Year
+ [**rPackageStats** by *craigwang*](https://craigwang.shinyapps.io/rPackageStats): Download of R Packages Worldwide
+ [**rPackedBarDemo** by *spannbaueradam*](https://spannbaueradam.shinyapps.io/rPackedBarDemo): Packed Bar Charts using the rPackedBar package
+ [**RPS-Shiny** by *brandonkopp*](https://brandonkopp.shinyapps.io/RPS-Shiny): RPS Shiny
+ [**RR_D** by *openfda*](https://openfda.shinyapps.io/RR_D): RR-Drug
+ [**rsconf_tweets** by *gadenbuie*](https://gadenbuie.shinyapps.io/rsconf_tweets): rstudio::conf_twitter()
+ [**rshinylady** by *gqueiroz*](https://gqueiroz.shinyapps.io/rshinylady): R-Ladies
+ [**rsprite** by *steamtraen*](https://steamtraen.shinyapps.io/rsprite): rSPRITE beta 0.15
+ [**rtide** by *poissonconsulting*](https://poissonconsulting.shinyapps.io/rtide): Tide Predictions
+ [**RTutorSoapOperas** by *claraulmer*](https://claraulmer.shinyapps.io/RTutorSoapOperas): RTutor
+ [**rugsmaps** by *blenditbayes*](https://blenditbayes.shinyapps.io/rugsmaps): R User Groups Around the World

## S
+ [**SACTN** by *robert-schlegel*](https://robert-schlegel.shinyapps.io/SACTN): The SACTN Web Interface
+ [**safe** by *safescore*](https://safescore.shinyapps.io/safe): SAFE Score: Individualized Prediction of Atrial Fibrillation in Critically Ill Patients with Sepsis
+ [**safetyapp** by *becca-krouse*](https://becca-krouse.shinyapps.io/safetyapp): Safety Explorer Shiny App
+ [**SalaryExample** by *kenriceuw*](https://kenriceuw.shinyapps.io/SalaryExample): Salary boxplots
+ [**sales** by *suebayes*](https://suebayes.shinyapps.io/sales): ECommerce Dashboard
+ [**saltydates** by *mekline*](https://mekline.shinyapps.io/saltydates): SaltyDates
+ [**SampDist_discrete** by *istats*](https://istats.shinyapps.io/SampDist_discrete): Sampling Distribution Mean
+ [**sample-size-calculator** by *fahim*](https://fahim.shinyapps.io/sample-size-calculator): Sample size calculation
+ [**sample_away** by *troettger*](https://troettger.shinyapps.io/sample_away): Sample away
+ [**sample_means** by *ihstevenson*](https://ihstevenson.shinyapps.io/sample_means): Distribution of Sample Means
+ [**sample_size_calculator** by *drkhaled*](https://drkhaled.shinyapps.io/sample_size_calculator): Sample size calculator by Khaled Alqahtani @alqahtani_khald
+ [**san_diego_progressive_voter_meta-guide** by *violadoesdata*](https://violadoesdata.shinyapps.io/san_diego_progressive_voter_meta-guide): San Diego Primaries 2018 - Progressive Voter Meta-Guide
+ [**Santander-Product-Recommendation** by *tvdwiele*](https://tvdwiele.shinyapps.io/Santander-Product-Recommendation): Santander product recommendation
+ [**SARexplore** by *ou-statswidgets*](https://ou-statswidgets.shinyapps.io/SARexplore): Species area relationship
+ [**sasmap** by *mangothecat*](https://mangothecat.shinyapps.io/sasmap): sasMap - Function Map for SAS
+ [**scavengerhunt** by *jlsumner*](https://jlsumner.shinyapps.io/scavengerhunt): Local Government Scavenger Hunt
+ [**SCD-effect-sizes** by *jepusto*](https://jepusto.shinyapps.io/SCD-effect-sizes): Single-case effect size calculator
+ [**SceneWalk** by *engbertlab*](https://engbertlab.shinyapps.io/SceneWalk): Spatial statistics and attentional dynamics in scene viewing
+ [**science_podcasts** by *plantmodelling*](https://plantmodelling.shinyapps.io/science_podcasts): Science podcast finder
+ [**scotlandperforms_alpha** by *scotland*](https://scotland.shinyapps.io/scotlandperforms_alpha): Scotland Performs Dashboard
+ [**Scratch** by *wilkins*](https://wilkins.shinyapps.io/Scratch): Bird Vocal Scaling
+ [**screen_tb** by *wpro*](https://wpro.shinyapps.io/screen_tb): ScreenTB - target prioritization and strategy selection for tuberculosis screening (active case finding)
+ [**scripts** by *nicholas-coles*](https://nicholas-coles.shinyapps.io/scripts): Open MetaPipeline
+ [**SDAppvX1** by *yanru-xing*](https://yanru-xing.shinyapps.io/SDAppvX1): Evaluating yield loss due to seed degeneration over time
+ [**seabird-threats** by *dragonfly-science*](https://dragonfly-science.shinyapps.io/seabird-threats): Demography
+ [**SealedMTG** by *troyhernandez*](https://troyhernandez.shinyapps.io/SealedMTG): MTG Sealed Draft Tool - M20
+ [**Search_Pepys** by *goldin*](https://goldin.shinyapps.io/Search_Pepys): Search the Diary of Samuel Pepys
+ [**searchConsoleRDemo** by *mark*](https://mark.shinyapps.io/searchConsoleRDemo): searchConsoleR Shiny Demo
+ [**Season_Projections** by *loghan*](https://loghan.shinyapps.io/Season_Projections): Hansen Ratings
+ [**season_projections** by *Loghan*](https://Loghan.shinyapps.io/season_projections): Hansen Ratings
+ [**seasonal_rainfall** by *statisticsnz*](https://statisticsnz.shinyapps.io/seasonal_rainfall): Seasonal rainfall
+ [**seasoning** by *mdlincoln*](https://mdlincoln.shinyapps.io/seasoning): seasoning: salt your data
+ [**seattle_sidewalks** by *gngu*](https://gngu.shinyapps.io/seattle_sidewalks): SEA Sidewalks
+ [**SeawaterCarbonateSystem** by *gcri-doab*](https://gcri-doab.shinyapps.io/SeawaterCarbonateSystem): Seawater Carbonate System
+ [**seb-tallinn-marathon** by *andybeger*](https://andybeger.shinyapps.io/seb-tallinn-marathon): SEB Tallinn Marathon 2014 Results
+ [**section7** by *defenders-esc*](https://defenders-esc.shinyapps.io/section7): Section 7 consultations
+ [**seeClimate** by *wilkins*](https://wilkins.shinyapps.io/seeClimate): SeeClimate
+ [**seg_admision_colegios_zgz_2016** by *scien-analytics*](https://scien-analytics.shinyapps.io/seg_admision_colegios_zgz_2016): Evolución solicitudes Colegios Zaragoza
+ [**semantic_net** by *rosenbusch*](https://rosenbusch.shinyapps.io/semantic_net): SSN
+ [**SensSpec** by *gettingthingsr*](https://gettingthingsr.shinyapps.io/SensSpec): GettingThingsR
+ [**Sentiment-analysis** by *quintana*](https://quintana.shinyapps.io/Sentiment-analysis): Twitter Sentiment Analysis
+ [**sentiment-visualization-us-dataset** by *hnhenk10*](https://hnhenk10.shinyapps.io/sentiment-visualization-us-dataset): Sentiment visualization of US leaders, source - Twitter/ Ranfor.com
+ [**SentimentApp** by *thedatajournalist*](https://thedatajournalist.shinyapps.io/SentimentApp): The Data Journalist: Summarize My Text
+ [**SER_TWITTER** by *adelmoaguiarfilho*](https://adelmoaguiarfilho.shinyapps.io/SER_TWITTER): III SER on Twitter
+ [**serialApp** by *dgrtwo*](https://dgrtwo.shinyapps.io/serialApp): Visualizing the phone calls of Serial
+ [**server-to-client-custom-messages** by *gallery*](https://gallery.shinyapps.io/server-to-client-custom-messages): sendCustomMessage example
+ [**SETHs** by *jmichaelrosenberg*](https://jmichaelrosenberg.shinyapps.io/SETHs): State Educational Twitter Hashtags (SETHs)
+ [**settFeb2015** by *objectcomputing*](https://objectcomputing.shinyapps.io/settFeb2015): Fitting Data to a Model
+ [**Severity** by *marcosjnez*](https://marcosjnez.shinyapps.io/Severity): Severe Testing
+ [**severity_power_pvalues** by *karthikdurvasula*](https://karthikdurvasula.shinyapps.io/severity_power_pvalues): Calculator: P-value, Power, Severity
+ [**sfhip-app** by *jrnew*](https://jrnew.shinyapps.io/sfhip-app): SFHIP
+ [**sfm-exporter** by *stefanocoretta*](https://stefanocoretta.shinyapps.io/sfm-exporter): SFM exporter (Toolbox/FLEx SIL)
+ [**SFREC_Web_Application** by *ucanr*](https://ucanr.shinyapps.io/SFREC_Web_Application): University of California - Sierra Foothill Research and Extension Center
+ [**sg-equality-evidence-finder** by *scotland*](https://scotland.shinyapps.io/sg-equality-evidence-finder): This is the beta version of the new Equality Evidence Finder. We're still working on the site, and welcome any comments or suggestions by email to social-justice-analysis@gov.scot
+ [**sg-salmon-conservation** by *scotland*](https://scotland.shinyapps.io/sg-salmon-conservation): Conservation Regulations
+ [**sgpvalue** by *lucy*](https://lucy.shinyapps.io/sgpvalue): Second Generation P-values
+ [**shank_family_running_log_2012-2017** by *fweco*](https://fweco.shinyapps.io/shank_family_running_log_2012-2017): Shank Family Running Log 2012-2017
+ [**shc_example** by *pkimes*](https://pkimes.shinyapps.io/shc_example): Significance for Hierarchical Clustering
+ [**sheep** by *maxshang*](https://maxshang.shinyapps.io/sheep): Lamb Finishing
+ [**shiny** by *blancacalvofigueras*](https://blancacalvofigueras.shinyapps.io/shiny): The Life of News Stories
+ [**Shiny** by *decisionsciences*](https://decisionsciences.shinyapps.io/Shiny): Shiny
+ [**shiny** by *james-thorson*](https://james-thorson.shinyapps.io/shiny): Visualize fish traits
+ [**shiny** by *keniasousa*](https://keniasousa.shinyapps.io/shiny): Graduates by Country per Year
+ [**shiny** by *kyle765*](https://kyle765.shinyapps.io/shiny): School Idol Tomodachi Team Builder
+ [**shiny** by *nmdpredictions*](https://nmdpredictions.shinyapps.io/shiny): NMD Prediction Tool
+ [**shiny** by *nsf-grfp*](https://nsf-grfp.shinyapps.io/shiny): Undergraduate Universities of GRFP Recipients
+ [**shiny** by *penn-musa*](https://penn-musa.shinyapps.io/shiny): Predicting Neighborhood Lead Risk in Minneapolis
+ [**Shiny** by *principalimages*](https://principalimages.shinyapps.io/Shiny): Image decomposition
+ [**shiny** by *randomizeauthor*](https://randomizeauthor.shinyapps.io/shiny): randomizeAuthor
+ [**shiny** by *sifteambuilder*](https://sifteambuilder.shinyapps.io/shiny): School Idol Tomodachi Team Builder
+ [**SHINY** by *summersuny*](https://summersuny.shinyapps.io/SHINY): The NYC Citi Bike App
+ [**shiny** by *swainjo*](https://swainjo.shinyapps.io/shiny): Ebola Twitter Analysis
+ [**shiny-accidents-barcelona** by *ddrbcn*](https://ddrbcn.shinyapps.io/shiny-accidents-barcelona): Accidents gestionats per la Guàrdia Urbana a la ciutat de Barcelona.
+ [**shiny-biclust** by *uhasselt*](https://uhasselt.shinyapps.io/shiny-biclust): biclustGUI
+ [**Shiny-CutOffs** by *neurotroph*](https://neurotroph.shinyapps.io/Shiny-CutOffs): Cut-Off Values for Tests
+ [**shiny-examples** by *wrightaprilm*](https://wrightaprilm.shinyapps.io/shiny-examples): treesiftr
+ [**shiny-iatlas** by *isb-cgc*](https://isb-cgc.shinyapps.io/shiny-iatlas): CRI iAtlas Portal
+ [**shiny-on** by *dc-coder*](https://dc-coder.shinyapps.io/shiny-on): Lebanon's data indicators
+ [**shiny-pov** by *ndasilva*](https://ndasilva.shinyapps.io/shiny-pov): US Poverty
+ [**shiny-salesman** by *gallery*](https://gallery.shinyapps.io/shiny-salesman): Traveling Salesman with Simulated Annealing, Shiny, and R
+ [**shiny-stocks** by *und1f*](https://und1f.shinyapps.io/shiny-stocks): Stock graph
+ [**shiny_app** by *aakarshgupta*](https://aakarshgupta.shinyapps.io/shiny_app): My Text prediction App
+ [**shiny_app** by *jflancer*](https://jflancer.shinyapps.io/shiny_app): The Sports Network
+ [**shiny_app_project_montecarlo** by *guilleatt*](https://guilleatt.shinyapps.io/shiny_app_project_montecarlo): MonteCarlo method: Calculating a circle area
+ [**shiny_cumu_hr_app** by *billpetti*](https://billpetti.shinyapps.io/shiny_cumu_hr_app): About
+ [**shiny_Ergebnismodell** by *nobilor*](https://nobilor.shinyapps.io/shiny_Ergebnismodell): Fussball-Ergebnissimulation nach Mannschaftsscore und erwarteter Torzahl
+ [**shiny_ffl_app** by *billpetti*](https://billpetti.shinyapps.io/shiny_ffl_app): Fantasy Football Tool
+ [**shiny_geolocation** by *tomaugust*](https://tomaugust.shinyapps.io/shiny_geolocation): Superzip
+ [**shiny_gradient_descent** by *analysingstuffs*](https://analysingstuffs.shinyapps.io/shiny_gradient_descent): Gradient Descent
+ [**shiny_model2** by *niceguy*](https://niceguy.shinyapps.io/shiny_model2): 1yr mortality risk calculator
+ [**shiny_plots** by *costeapaul*](https://costeapaul.shinyapps.io/shiny_plots): Silly plots
+ [**shiny_spraychart** by *billpetti*](https://billpetti.shinyapps.io/shiny_spraychart): The Interactive Spray Chart Tool
+ [**shiny_testers** by *testersurvey*](https://testersurvey.shinyapps.io/shiny_testers): Explore a Sample of Software Testers
+ [**shiny_travel** by *stevenvanbelleghem*](https://stevenvanbelleghem.shinyapps.io/shiny_travel): Shiny travel
+ [**shiny_twitter_chart** by *daigotanaka*](https://daigotanaka.shinyapps.io/shiny_twitter_chart): My Tweets in 2014: Impressions and Engagements
+ [**shinyaim** by *chikudaisei*](https://chikudaisei.shinyapps.io/shinyaim): ShinyAIM: Shiny Application for Interactive Manhattan Plots
+ [**shinyampvis** by *kasperskytte*](https://kasperskytte.shinyapps.io/shinyampvis): Amplicon Visualiser
+ [**shinyapp** by *chadburdyshaw*](https://chadburdyshaw.shinyapps.io/shinyapp): Twitter Origin Word Cloud
+ [**shinyApp** by *dgason*](https://dgason.shinyapps.io/shinyApp): Cost of College
+ [**shinyapp** by *opendata*](https://opendata.shinyapps.io/shinyapp): Rate bicycle infrastructure in your area!
+ [**ShinyApp** by *sriyoda*](https://sriyoda.shinyapps.io/ShinyApp): Airline Passenger Density by Country
+ [**shinyappbubbles** by *franiis*](https://franiis.shinyapps.io/shinyappbubbles): What does this application do?
+ [**ShinyAppEmployment** by *dmundjar*](https://dmundjar.shinyapps.io/ShinyAppEmployment): Zaposlenost: Hrvatska
+ [**ShinyAssignment** by *aakarshgupta*](https://aakarshgupta.shinyapps.io/ShinyAssignment): Data visualization of a Random Sample
+ [**shinybrot** by *blmr*](https://blmr.shinyapps.io/shinybrot): Shinybrot
+ [**ShinyBuilder** by *iheart*](https://iheart.shinyapps.io/ShinyBuilder): Confirm Deletion
+ [**ShinyCaret** by *earlglynn*](https://earlglynn.shinyapps.io/ShinyCaret): Shiny Caret Lab: Image Segmentation Data
+ [**shinyCEO** by *joseppuig*](https://joseppuig.shinyapps.io/shinyCEO): Baròmetre d'opinió
+ [**shinychamp** by *psychemedia*](https://psychemedia.shinyapps.io/shinychamp): F1 Driver Championship Scenarios, 2016
+ [**shinyCountryTimeseries** by *chendaniely*](https://chendaniely.shinyapps.io/shinyCountryTimeseries): Plotting Ebola
+ [**shinycsv** by *jhubiostatistics*](https://jhubiostatistics.shinyapps.io/shinycsv): shinycsv: explore a table interactively
+ [**ShinyDeploy** by *datagenii*](https://datagenii.shinyapps.io/ShinyDeploy): Data Genii Interactive Analysis Tool
+ [**ShinyDosing** by *zaborek-uwsurgery*](https://zaborek-uwsurgery.shinyapps.io/ShinyDosing): Thyroid Hormone Dosing with Poisson Regression
+ [**shinyearr_demo** by *nickstrayer*](https://nickstrayer.shinyapps.io/shinyearr_demo): shinyearr demo
+ [**shinyfftrees** by *econpsychbasel*](https://econpsychbasel.shinyapps.io/shinyfftrees): Shiny FFTrees
+ [**ShinyFork** by *mattbrehmer*](https://mattbrehmer.shinyapps.io/ShinyFork): ShinyFork
+ [**shinyGEO** by *gdancik*](https://gdancik.shinyapps.io/shinyGEO): shinyGEO
+ [**shinygpas** by *chikudaisei*](https://chikudaisei.shinyapps.io/shinygpas): ShinyGPAS
+ [**shinyK** by *gmdn*](https://gmdn.shinyapps.io/shinyK): Reuters-21578 Data
+ [**shinykonfound** by *jmichaelrosenberg*](https://jmichaelrosenberg.shinyapps.io/shinykonfound): KonFound-It!
+ [**ShinyMarsouin** by *marsouin*](https://marsouin.shinyapps.io/ShinyMarsouin): Shiny Marsouin
+ [**shinyMB** by *fedematt*](https://fedematt.shinyapps.io/shinyMB): Power&Sample Sizes Tool
+ [**shinyMig_UpperAT** by *donk23*](https://donk23.shinyapps.io/shinyMig_UpperAT): shinyMig OÖ - Migrationsbilanz der oö. Bezirke, 2002 - 2012
+ [**ShinyNLP** by *gianfranco-campana*](https://gianfranco-campana.shinyapps.io/ShinyNLP): JHU Data Science Specialization Capstone Project
+ [**shinyplay03** by *weinbergerlab*](https://weinbergerlab.shinyapps.io/shinyplay03): Vaccine Impact Confidence Evaluation (VICE)
+ [**shinyplot** by *sjspielman*](https://sjspielman.shinyapps.io/shinyplot): Visualize simple data distributions with ggplot2
+ [**ShinyPop** by *iainmstott*](https://iainmstott.shinyapps.io/ShinyPop): ShinyPop
+ [**shinyQuantMod** by *edbullen*](https://edbullen.shinyapps.io/shinyQuantMod): Stock Closing Price History
+ [**shinyr_trends** by *ajaykumar*](https://ajaykumar.shinyapps.io/shinyr_trends): Interactive Bivariate
+ [**shinyresumedemo** by *mfoos*](https://mfoos.shinyapps.io/shinyresumedemo): Shiny Resume Builder
+ [**shinyRootBox** by *plantmodelling*](https://plantmodelling.shinyapps.io/shinyRootBox): CRootBox
+ [**shinySC** by *internetrepublica*](https://internetrepublica.shinyapps.io/shinySC): Calculadora del efecto de cambios SEO
+ [**shinysense_earr_demo** by *nickstrayer*](https://nickstrayer.shinyapps.io/shinysense_earr_demo): shinyearr demo
+ [**shinyski** by *skitestguys*](https://skitestguys.shinyapps.io/shinyski): shiny ski
+ [**shinySpecClust** by *abreschi*](https://abreschi.shinyapps.io/shinySpecClust): CGM viewer
+ [**shinytextpredict** by *herchu*](https://herchu.shinyapps.io/shinytextpredict): Let me guess your next word
+ [**ShinyTimeseriesForecasting** by *aneesha*](https://aneesha.shinyapps.io/ShinyTimeseriesForecasting): Timeseries Forecasting
+ [**shinyTreeViewer** by *klash*](https://klash.shinyapps.io/shinyTreeViewer): shinyTreeViewer
+ [**shinyV03** by *natydasilva*](https://natydasilva.shinyapps.io/shinyV03): PPforest visualization
+ [**shinyvalidinp-demo** by *szilard*](https://szilard.shinyapps.io/shinyvalidinp-demo): Shiny input validation - demo
+ [**shinyweatherdata** by *rokka*](https://rokka.shinyapps.io/shinyweatherdata): Shiny weather data
+ [**shinyWidgets** by *dreamrs-vic*](https://dreamrs-vic.shinyapps.io/shinyWidgets): shinyWidgets Overview
+ [**shinyWYSIWYG** by *jcrodriguez*](https://jcrodriguez.shinyapps.io/shinyWYSIWYG): shinyWYSIWYG
+ [**shotGroupsApp** by *dwoll*](https://dwoll.shinyapps.io/shotGroupsApp): Analyze shooting results using shotGroups
+ [**showcase** by *rusdracor*](https://rusdracor.shinyapps.io/showcase): Russian Drama Corpus (RusDraCor): Showcase
+ [**ShowofHands** by *kgilpas*](https://kgilpas.shinyapps.io/ShowofHands): Show of Hands Quiz
+ [**shrlog_example** by *knilda*](https://knilda.shinyapps.io/shrlog_example): Graylog - Analysis
+ [**SHW2** by *dsollberger*](https://dsollberger.shinyapps.io/SHW2): SHW2
+ [**SHW3** by *dsollberger*](https://dsollberger.shinyapps.io/SHW3): SHW3
+ [**signify** by *nanx*](https://nanx.shinyapps.io/signify): Signify
+ [**Simple** by *erikvoeten*](https://erikvoeten.shinyapps.io/Simple): Voting with the US in the UN
+ [**simple_regression** by *gallery*](https://gallery.shinyapps.io/simple_regression): Simple Linear Regression
+ [**simple_shiny_randomization** by *josh-kalla*](https://josh-kalla.shinyapps.io/simple_shiny_randomization): Randomization Tool
+ [**SimpleROC** by *maureen*](https://maureen.shinyapps.io/SimpleROC): Simple ROC Demo
+ [**singlemalt** by *kart*](https://kart.shinyapps.io/singlemalt): Single Malt Discovery, by Bespoke Data Insights Ltd
+ [**Sixer** by *tvganesh*](https://tvganesh.shinyapps.io/Sixer): cricketr analyzes Cricketers!
+ [**skill_metrics** by *meteoswiss-climate*](https://meteoswiss-climate.shinyapps.io/skill_metrics): Forecast skill metrics
+ [**skill_metrics** by *meteoswiss*](https://meteoswiss.shinyapps.io/skill_metrics): Forecast skill metrics
+ [**SLOAPCDWebDataDisplay** by *ktupper*](https://ktupper.shinyapps.io/SLOAPCDWebDataDisplay): Air Quality Conditions in San Luis Obispo County
+ [**slr_diag** by *gallery*](https://gallery.shinyapps.io/slr_diag): Diagnostics for simple linear regression
+ [**Smart_Cities_India** by *avinashr*](https://avinashr.shinyapps.io/Smart_Cities_India): Smart Cities Mission
+ [**smartphonepersonality** by *psychology*](https://psychology.shinyapps.io/smartphonepersonality): Predicting smartphone operating system from personality and individual differences
+ [**SMARTsize** by *nseewald1*](https://nseewald1.shinyapps.io/SMARTsize): SMART Sample Size Calculator
+ [**SMT-Sudan** by *momen*](https://momen.shinyapps.io/SMT-Sudan): Social Media Trend Sudan
+ [**so-trends** by *dgrtwo*](https://dgrtwo.shinyapps.io/so-trends): Stack Overflow Trends
+ [**soccerteams** by *jalapic*](https://jalapic.shinyapps.io/soccerteams): Comparing English soccer teams across time
+ [**SocialMediaPulse** by *manaswink*](https://manaswink.shinyapps.io/SocialMediaPulse): Sentiment Pie
+ [**sodastream** by *mali-codes*](https://mali-codes.shinyapps.io/sodastream): SodaStream Calculator
+ [**solar-system-mapper** by *pdwarf*](https://pdwarf.shinyapps.io/solar-system-mapper): Solar System Mapper
+ [**song_lyric_term_matching** by *michaelpawlus*](https://michaelpawlus.shinyapps.io/song_lyric_term_matching): Song Lyric Matching Terms
+ [**sotushiny** by *brandonkopp*](https://brandonkopp.shinyapps.io/sotushiny): SOTU Explorer
+ [**SOTUshiny** by *brandonkopp*](https://brandonkopp.shinyapps.io/SOTUshiny): SOTU Explorer
+ [**spatialepiapp** by *paulamoraga*](https://paulamoraga.shinyapps.io/spatialepiapp): SpatialEpiApp
+ [**Spearman-Brown_App_18Oct2016** by *ajthurston*](https://ajthurston.shinyapps.io/Spearman-Brown_App_18Oct2016): Spearman-Brown Calculator
+ [**specialprotectionwatersexplorer** by *elainepanuccio*](https://elainepanuccio.shinyapps.io/specialprotectionwatersexplorer): DRBC Special Protection Waters Monitoring Program Explorer
+ [**speciesplotviewer** by *charlieouthwaite*](https://charlieouthwaite.shinyapps.io/speciesplotviewer): Species Occupancy Plot Viewer
+ [**speedtestR** by *rhuanlima*](https://rhuanlima.shinyapps.io/speedtestR): Net Virtua Speedtest
+ [**spillover-app** by *egap*](https://egap.shinyapps.io/spillover-app): Geographic Spillovers
+ [**splineapp** by *obrl-soil*](https://obrl-soil.shinyapps.io/splineapp): SplineApp
+ [**spmetacase1** by *blakemcshane*](https://blakemcshane.shinyapps.io/spmetacase1): SPM: Single Paper Meta-analysis
+ [**Sport_Difficulty** by *jwwanalytics*](https://jwwanalytics.shinyapps.io/Sport_Difficulty): Common Sports Ranked by Difficulty
+ [**spotifyapp** by *joelcponte*](https://joelcponte.shinyapps.io/spotifyapp): Pick Artists
+ [**Spray-Chart** by *danmalter*](https://danmalter.shinyapps.io/Spray-Chart): MLB Spray Charts
+ [**SRM_R** by *davidakenny*](https://davidakenny.shinyapps.io/SRM_R): Social Relations Model Estimation
+ [**SS_regression** by *paternogbc*](https://paternogbc.shinyapps.io/SS_regression): Parameters
+ [**START** by *kcvi*](https://kcvi.shinyapps.io/START): START: Shiny Transcriptome Analysis Resource Tool
+ [**startup-funding** by *abmish*](https://abmish.shinyapps.io/startup-funding): How much fund can you raise for your startup?
+ [**statnetWeb** by *statnet*](https://statnet.shinyapps.io/statnetWeb): statnetWeb
+ [**Stats** by *sahuvaibhav*](https://sahuvaibhav.shinyapps.io/Stats): Stats
+ [**Steve_Bronder_Tufte** by *stevebronder*](https://stevebronder.shinyapps.io/Steve_Bronder_Tufte): Edward Tufte Weather Graphic for Eleven Cities
+ [**sthlm_temperatures** by *mikaelhuss*](https://mikaelhuss.shinyapps.io/sthlm_temperatures): Current Stockholm temperature in context
+ [**sti-screen** by *epimodel*](https://epimodel.shinyapps.io/sti-screen): MSM STI Screening
+ [**StochasticCompetition** by *phyzoo*](https://phyzoo.shinyapps.io/StochasticCompetition): Stochastic competition model (2 Species)
+ [**stock_vol** by *trading*](https://trading.shinyapps.io/stock_vol): Chart Inputs
+ [**stockReturns** by *nitingupta2*](https://nitingupta2.shinyapps.io/stockReturns): Investment Performance
+ [**stocks** by *hansonwu*](https://hansonwu.shinyapps.io/stocks): StockChart
+ [**StockWatch** by *dataflemming*](https://dataflemming.shinyapps.io/StockWatch): Stock Watch
+ [**stopcovar** by *echodroff*](https://echodroff.shinyapps.io/stopcovar): Covariation of stop consonant cues
+ [**streamflow_joyplots** by *lsteely*](https://lsteely.shinyapps.io/streamflow_joyplots): JoyFlow
+ [**stringr_help** by *omaymas*](https://omaymas.shinyapps.io/stringr_help): Stringr Explorer
+ [**StructuralCoexistence** by *ecodynamics*](https://ecodynamics.shinyapps.io/StructuralCoexistence): Understanding Structural Coexistence for Multispecies Communities
+ [**student_alc_consumption** by *adhokshaja*](https://adhokshaja.shinyapps.io/student_alc_consumption): Daily Alcohol Consumption And Grades/Gender
+ [**subalgebra** by *trevor*](https://trevor.shinyapps.io/subalgebra): Reddit Subreddit Similarity and Algebra
+ [**Sudoku** by *michielkoens*](https://michielkoens.shinyapps.io/Sudoku): Sudoku
+ [**sudoku-solver** by *dirk*](https://dirk.shinyapps.io/sudoku-solver): Solve Sudokus with GLPK and R
+ [**suicide** by *seigma*](https://seigma.shinyapps.io/suicide): SEIGMA: Suicide Shiny App
+ [**suicidenetwork** by *derekdebeurs*](https://derekdebeurs.shinyapps.io/suicidenetwork): Tutorial
+ [**SuperDuplicates** by *chao*](https://chao.shinyapps.io/SuperDuplicates): SuperDuplicates
+ [**superzip** by *jcheng*](https://jcheng.shinyapps.io/superzip): Superzip
+ [**surv_h27** by *rs-fan-jp*](https://rs-fan-jp.shinyapps.io/surv_h27): 日本人H27完全生命表による生存曲線
+ [**survey** by *csaid*](https://csaid.shinyapps.io/survey): #Repligate survey
+ [**Survey** by *econometricsbysimulation*](https://econometricsbysimulation.shinyapps.io/Survey): Shiny Survey Tool v.01
+ [**SurvivalCalculator** by *kecc*](https://kecc.shinyapps.io/SurvivalCalculator): Estimated Kidney Graft Survival Calculator
+ [**Survivor_Optimization_App_2** by *hatch113g*](https://hatch113g.shinyapps.io/Survivor_Optimization_App_2): Hatch's Eliminator/Survivor Optimization App
+ [**SuspicionScoreswithDataDownload** by *jprims*](https://jprims.shinyapps.io/SuspicionScoreswithDataDownload): Suspicious Response Detector
+ [**svensk_partiopinion** by *lovechristensen*](https://lovechristensen.shinyapps.io/svensk_partiopinion): Svensk partiopinion
+ [**svmeasyapp** by *axelmora*](https://axelmora.shinyapps.io/svmeasyapp): SVM easyApp
+ [**SwedishTwitterCommunities** by *mikaelhuss*](https://mikaelhuss.shinyapps.io/SwedishTwitterCommunities): Swedish Twitter
+ [**swiftkey-cap** by *farsite*](https://farsite.shinyapps.io/swiftkey-cap): Type Ahead Prediction
+ [**swmp_agg** by *beckmw*](https://beckmw.shinyapps.io/swmp_agg): Aggregation of SWMP parameters within/between reserves
+ [**swmp_comp** by *beckmw*](https://beckmw.shinyapps.io/swmp_comp): Trends in SWMP parameters
+ [**swmp_summary** by *beckmw*](https://beckmw.shinyapps.io/swmp_summary): Monthly and annual summary of SWMP parameters
+ [**SWOP** by *swopmd*](https://swopmd.shinyapps.io/SWOP): Statistics Without Probability - A New Statistical Paradigm: www.statistics.sastram.com By Dr Mithilesh Dronavalli
+ [**swopreg** by *swopmd*](https://swopmd.shinyapps.io/swopreg): Regression with Statistics Without Probability using Corrected Treatment Effect for adjusting: www.statistics.sastram.com By Dr Mithilesh Dronavalli
+ [**syllabustool** by *jlsumner*](https://jlsumner.shinyapps.io/syllabustool): Gender Balance Assessment Tool (GBAT)

## T
+ [**T1RiskEngine** by *steno*](https://steno.shinyapps.io/T1RiskEngine): Steno T1 Risk Engine
+ [**t21app** by *hoehle*](https://hoehle.shinyapps.io/t21app): Risk of trisomy 21 after First-Trimester Screening
+ [**tag-traffic-hour** by *dgrtwo*](https://dgrtwo.shinyapps.io/tag-traffic-hour): When do Stack Overflow users visit particular technologies?
+ [**tagtime-vis** by *alexschell*](https://alexschell.shinyapps.io/tagtime-vis): TagTime Visualizer
+ [**tallfeet** by *hayle*](https://hayle.shinyapps.io/tallfeet): Exploring Class Height and Foot Size Data
+ [**tarteebEldof3a** by *alexf*](https://alexf.shinyapps.io/tarteebEldof3a): Tarteeb Eldof3a scraped from the website. Not responsible for mistakes
+ [**taskviewr** by *bearloga*](https://bearloga.shinyapps.io/taskviewr): R Packages and Licenses by Task View
+ [**TAVI_Risk_calculator** by *atsol*](https://atsol.shinyapps.io/TAVI_Risk_calculator): TAVI 30 day Mortality Calculator
+ [**taxcuts** by *econdata*](https://econdata.shinyapps.io/taxcuts): Comparison of Tax Plans
+ [**Taxis-Trajectories** by *dguzman*](https://dguzman.shinyapps.io/Taxis-Trajectories): Oporto Taxi Routes
+ [**tdist** by *dswalter*](https://dswalter.shinyapps.io/tdist): Interactive Student's T Density
+ [**tds_leaflet** by *richpauloo*](https://richpauloo.shinyapps.io/tds_leaflet): TDS in the Tulare Basin
+ [**TeamPerformance** by *cchappas*](https://cchappas.shinyapps.io/TeamPerformance): Comparing Actual and Expected Football Results
+ [**Telecom_Trend** by *sirujam*](https://sirujam.shinyapps.io/Telecom_Trend): Yearwise Trend - Mobile (1980 - 2013)
+ [**Tenure_Explorer_App** by *datascapes*](https://datascapes.shinyapps.io/Tenure_Explorer_App): Housing Tenure Explorer
+ [**test1** by *jabiologo*](https://jabiologo.shinyapps.io/test1): BioTraffic , by KATUMWA RANGERS
+ [**test_project** by *skaae*](https://skaae.shinyapps.io/test_project): Gaussian Process example
+ [**texas_pyramids** by *walkerke*](https://walkerke.shinyapps.io/texas_pyramids): Demographics of Texas Counties, 2010-2050
+ [**text-predictor** by *andywon*](https://andywon.shinyapps.io/text-predictor): Text Prediction
+ [**TextMining** by *languagevariationsuite*](https://languagevariationsuite.shinyapps.io/TextMining): Interactive Text Mining Suite
+ [**thecost** by *precision-methodologies*](https://precision-methodologies.shinyapps.io/thecost): The Cost of 1-Size-Fits-All Dose Finding in Oncology
+ [**themepower** by *andyf*](https://andyf.shinyapps.io/themepower): Supporting thinking on sample sizes for thematic analyses
+ [**theorymaker3** by *stevepowell*](https://stevepowell.shinyapps.io/theorymaker3): Theory Maker
+ [**thePhactory** by *tylerclavelle*](https://tylerclavelle.shinyapps.io/thePhactory): The Phactory
+ [**thermohydrographs** by *aquapeek*](https://aquapeek.shinyapps.io/thermohydrographs): River Thermohydrographs
+ [**thisnotthatstat** by *rkbarney*](https://rkbarney.shinyapps.io/thisnotthatstat): ThisNotThatStat
+ [**tiapp** by *rajuvarghese*](https://rajuvarghese.shinyapps.io/tiapp): Top Income Share
+ [**tidyeval** by *ijlyttle*](https://ijlyttle.shinyapps.io/tidyeval): Tidyeval
+ [**tidytuesdayrocks** by *nsgrantham*](https://nsgrantham.shinyapps.io/tidytuesdayrocks): tidytuesday.rocks
+ [**tigris-zip-income** by *walkerke*](https://walkerke.shinyapps.io/tigris-zip-income): Average total income reported to the IRS, 2013
+ [**timer** by *cistrome*](https://cistrome.shinyapps.io/timer): TIMER
+ [**titanic** by *gregbehm*](https://gregbehm.shinyapps.io/titanic): Titanic
+ [**titanic-app** by *paul-reiners*](https://paul-reiners.shinyapps.io/titanic-app): Would you survive on the Titanic?
+ [**TitanicSurvivalApp** by *shashanksalvi*](https://shashanksalvi.shinyapps.io/TitanicSurvivalApp): Titanic Survival Analysis and Prediction
+ [**tlc_fast_dash** by *tlcanalytics*](https://tlcanalytics.shinyapps.io/tlc_fast_dash): TLC FastDash
+ [**tlit** by *stia*](https://stia.shinyapps.io/tlit): SATIS Tool Prototype
+ [**tmb_orr** by *ahopkins*](https://ahopkins.shinyapps.io/tmb_orr): TMB Predictions
+ [**TODD_UWhunger** by *kdvdecisionanalysis*](https://kdvdecisionanalysis.shinyapps.io/TODD_UWhunger): Childhood Poverty and Hunger in the Triangle
+ [**tommerpriser** by *endrh*](https://endrh.shinyapps.io/tommerpriser): Tømmerpriser
+ [**tompkins-county-law-enforcement-shared-services** by *cgr-datascience*](https://cgr-datascience.shinyapps.io/tompkins-county-law-enforcement-shared-services): Tompkins County LESS Data Explorer
+ [**tornasol** by *datascienceperu*](https://datascienceperu.shinyapps.io/tornasol): TORNASOL: National Peruvian Data - Cross Sectional Study of Cardiovascular Diseases
+ [**tourism_dashboard_prod** by *mbienz*](https://mbienz.shinyapps.io/tourism_dashboard_prod): New Zealand Tourism Dashboard
+ [**ToxBox** by *lancs*](https://lancs.shinyapps.io/ToxBox): Jittered Boxplots for Toxicological Data
+ [**track** by *mrd4*](https://mrd4.shinyapps.io/track): Data Viz Dashboard
+ [**traffic_riddle** by *mfviz*](https://mfviz.shinyapps.io/traffic_riddle): Traffic Simulation
+ [**trafficcare2** by *guanzy*](https://guanzy.shinyapps.io/trafficcare2): In this Area:
+ [**training_console_sample** by *jinsmeme*](https://jinsmeme.shinyapps.io/training_console_sample): JINS MEME Run - Training Console
+ [**trajectory-distribution** by *saberpowers*](https://saberpowers.shinyapps.io/trajectory-distribution): Jointly predicting exit velocity and launch angle for batter-pitcher matchups
+ [**TransitionInEnergyDemandSectors** by *imaclim*](https://imaclim.shinyapps.io/TransitionInEnergyDemandSectors): The transition in energy demand sectors to limit global warming to 1.5°C - an Interactive app
+ [**TrapSim_C2C** by *landcare*](https://landcare.shinyapps.io/TrapSim_C2C): TrapSim: Cape to City
+ [**traveller_screening** by *cmmid-lshtm*](https://cmmid-lshtm.shinyapps.io/traveller_screening): Effectiveness of airport-based interventions at detecting travellers and delaying an outbreak of COVID-19 (formerly 2019-nCoV)
+ [**trimleaguetable2** by *nzcms-ct-data-explorer*](https://nzcms-ct-data-explorer.shinyapps.io/trimleaguetable2): BODE3 League Table
+ [**TRiPS** by *starrfelt*](https://starrfelt.shinyapps.io/TRiPS): Paleodiversity - TRiPS and the Paleobiology Database
+ [**TSupplyDemand** by *gallery*](https://gallery.shinyapps.io/TSupplyDemand): Pilot Police Demand Planning Tool
+ [**tun_elections** by *agstudy*](https://agstudy.shinyapps.io/tun_elections): Tunisian Election Analyzer
+ [**turf_twitter_2018** by *asianturfgrass*](https://asianturfgrass.shinyapps.io/turf_twitter_2018): Turfgrass Twitter 2018
+ [**turfsi** by *asianturfgrass*](https://asianturfgrass.shinyapps.io/turfsi): Sustainability index (SI) calculator
+ [**turnover-and-retention-grids** by *department-for-education*](https://department-for-education.shinyapps.io/turnover-and-retention-grids): Teachers Analysis Compendium 4
+ [**tv_show_aging_curves** by *robarthur*](https://robarthur.shinyapps.io/tv_show_aging_curves): TV Show Aging Curves
+ [**TWD_Projekt2** by *madziq*](https://madziq.shinyapps.io/TWD_Projekt2): Pick your favourite hero in the Avengers movie
+ [**tweedie-viz** by *colonelsmoothie*](https://colonelsmoothie.shinyapps.io/tweedie-viz): Tweedie-Visualizer
+ [**tweetcloud** by *vivekkhetan*](https://vivekkhetan.shinyapps.io/tweetcloud): WordCloud from Twitter Trends and Search
+ [**tweetdivide** by *alspeed09*](https://alspeed09.shinyapps.io/tweetdivide): Divide tu texto en tweets manejables
+ [**TweetsAboutMe** by *acarloto*](https://acarloto.shinyapps.io/TweetsAboutMe): Tweets About Me
+ [**tweetstorm** by *thinkr*](https://thinkr.shinyapps.io/tweetstorm): tweetstorm
+ [**twitter** by *huck*](https://huck.shinyapps.io/twitter): #SIOP16 Tweets
+ [**twitter** by *maitray*](https://maitray.shinyapps.io/twitter): Twitter Archive Analysis
+ [**twitter** by *masterdatcom2017*](https://masterdatcom2017.shinyapps.io/twitter): Analisis sentimientos Twitter - DATCOM 2017
+ [**TwitteR** by *medhi*](https://medhi.shinyapps.io/TwitteR): A Minimum Viable Twitter Analysis Tool
+ [**twitter_analysis** by *cameronlhansen*](https://cameronlhansen.shinyapps.io/twitter_analysis): Twitter Analysis
+ [**Twitter_Cluster_Analysis** by *twittertextclustering*](https://twittertextclustering.shinyapps.io/Twitter_Cluster_Analysis): Twitter Topic Cluster Analysis
+ [**Twitter_SMCelection2016_app** by *curiositybits*](https://curiositybits.shinyapps.io/Twitter_SMCelection2016_app): Select candidates and performance indicators.
+ [**Twitter_Tern** by *etachov*](https://etachov.shinyapps.io/Twitter_Tern): Did you make a Bad Tweet?
+ [**twitteranalytics** by *aj17*](https://aj17.shinyapps.io/twitteranalytics): Twitter Analytics
+ [**TwitterAnalytics** by *tradewp*](https://tradewp.shinyapps.io/TwitterAnalytics): TWP Labs - Twitter Analytics
+ [**TwitterApp** by *datapprfn*](https://datapprfn.shinyapps.io/TwitterApp): Cazador de tweets
+ [**twitterlive** by *praneeth*](https://praneeth.shinyapps.io/twitterlive): Live Twitter Trends
+ [**twitterSayDisease** by *kenniajin*](https://kenniajin.shinyapps.io/twitterSayDisease): Health Tweet!
+ [**TwitterSentiment** by *davidski*](https://davidski.shinyapps.io/TwitterSentiment): Sentiment Analysis for Tweets on the Strata 2015 San Jose Conference
+ [**twittersentimentanalysis** by *mounabelaid*](https://mounabelaid.shinyapps.io/twittersentimentanalysis): Mona's up2: Twitter Sentiment Analysis of news from American profiles using R and ShinyDashboard
+ [**TwitterSIYapp** by *lumatadigital*](https://lumatadigital.shinyapps.io/TwitterSIYapp): Twitter : Score it yourself
+ [**twitterwordcloud** by *ksharma26*](https://ksharma26.shinyapps.io/twitterwordcloud): Twitter Word Cloud
+ [**two_factor_power** by *jakewestfall*](https://jakewestfall.shinyapps.io/two_factor_power): Power Analysis with Random Targets and Participants
+ [**twodice** by *gregbehm*](https://gregbehm.shinyapps.io/twodice): Sum of two dice simulation
+ [**TwoWayANOVA** by *houssein-assaad*](https://houssein-assaad.shinyapps.io/TwoWayANOVA): Publication-ready 2-AOV Tables
+ [**type_decision_tree** by *zmsgnk*](https://zmsgnk.shinyapps.io/type_decision_tree): 女性の好みを診断

## U
+ [**ucrdatatool** by *kaplan*](https://kaplan.shinyapps.io/ucrdatatool): UCR Data Tool
+ [**UCSC_COLA_Data** by *mck8dg*](https://mck8dg.shinyapps.io/UCSC_COLA_Data): UCSC Graduates Students are on Strike!
+ [**ufc_predict** by *arachnarchy*](https://arachnarchy.shinyapps.io/ufc_predict): Fight Prediction
+ [**ufr_analysis** by *mikegros*](https://mikegros.shinyapps.io/ufr_analysis): MGoBlog Upon Further Review (UFR) Visualization
+ [**UGIB_App_USA** by *dshung*](https://dshung.shinyapps.io/UGIB_App_USA): Acute UGIB ML Prediction Tool - U.S. Version
+ [**UKB_geo** by *holtzyan*](https://holtzyan.shinyapps.io/UKB_geo): Geographical Unit
+ [**UKMSim** by *kavee*](https://kavee.shinyapps.io/UKMSim): UKM Simulator (SPVV)
+ [**UNVoting** by *erikvoeten*](https://erikvoeten.shinyapps.io/UNVoting): United Nations General Assembly Voting Data Viewer (Beta)
+ [**updatedncaashotchart** by *reefersadness*](https://reefersadness.shinyapps.io/updatedncaashotchart): NCAAB Shot Charts
+ [**uploadfile** by *gallery*](https://gallery.shinyapps.io/uploadfile): Uploading Files
+ [**upsetr** by *gehlenborglab*](https://gehlenborglab.shinyapps.io/upsetr): Welcome to the UpSetR Shiny App!
+ [**urban-development-capacity** by *mbienz*](https://mbienz.shinyapps.io/urban-development-capacity): Urban Development Capacity
+ [**us_avg_tuition** by *krohitm*](https://krohitm.shinyapps.io/us_avg_tuition): US average tuition for different states
+ [**usabortionaccess** by *gutt*](https://gutt.shinyapps.io/usabortionaccess): Guttmacher Institute
+ [**user_genotypes** by *ekung*](https://ekung.shinyapps.io/user_genotypes): Ludometrica.org
+ [**USParkFindR** by *tzurloye*](https://tzurloye.shinyapps.io/USParkFindR): US Park FindR
+ [**usts** by *tvbassine*](https://tvbassine.shinyapps.io/usts): Usage and True Shooting Tracker
+ [**utility** by *morgan*](https://morgan.shinyapps.io/utility): Ekonomisk nytta vid rekryteringsurval
+ [**utility** by *psychometrics*](https://psychometrics.shinyapps.io/utility): Selection methods: Precision and Return On Investment
+ [**Utility-EUT** by *olivierlharidon*](https://olivierlharidon.shinyapps.io/Utility-EUT): Risk and Expected Utility
+ [**utility_calculator** by *morgan*](https://morgan.shinyapps.io/utility_calculator): Selection methods: Precision and Return On Investment

## V
+ [**VancouverCrimeDashboard** by *bisg*](https://bisg.shinyapps.io/VancouverCrimeDashboard): Vancouver Crime Data Vizualization
+ [**varclust_online** by *psobczyk*](https://psobczyk.shinyapps.io/varclust_online): varclust - R package for dimensionality reduction via variables clustering
+ [**vereinbarkeitssimulator** by *fhsg*](https://fhsg.shinyapps.io/vereinbarkeitssimulator): Vereinbarkeitssimulator
+ [**versi-DPRD-vs-versi-Pemprov** by *ainunnajib*](https://ainunnajib.shinyapps.io/versi-DPRD-vs-versi-Pemprov): Tabel Perbandingan Mata Anggaran Belanja Daerah RAPBD 2015 versi DPRD versus versi Pemprov DKI Jakarta
+ [**version8** by *nzcms-ct-data-explorer*](https://nzcms-ct-data-explorer.shinyapps.io/version8): NZ Census Mortality and CancerTrends Study Data Explorer
+ [**vFeedCard** by *kill3rbee*](https://kill3rbee.shinyapps.io/vFeedCard): vFeed - CARD
+ [**vFeedCve** by *kill3rbee*](https://kill3rbee.shinyapps.io/vFeedCve): CVE Reporting Dashboard
+ [**viewr_imagenet** by *nstrayer*](https://nstrayer.shinyapps.io/viewr_imagenet): Imagenet Classifier
+ [**Violin** by *vivaldianalytics*](https://vivaldianalytics.shinyapps.io/Violin): Violin
+ [**Virus_Titration_Calculators** by *alegione*](https://alegione.shinyapps.io/Virus_Titration_Calculators): Virus titration calculators
+ [**VisMRI** by *athanasiamo*](https://athanasiamo.shinyapps.io/VisMRI): MRI visualisation
+ [**Visual_Resume** by *ndphillips*](https://ndphillips.shinyapps.io/Visual_Resume): Visual Resume Generator
+ [**Visualisasi** by *surabayanlp*](https://surabayanlp.shinyapps.io/Visualisasi): Visualisasi Analisis Sentimen Terhadap Kinerja Pelayanan Publik Di Kota Surabaya Berdasarkan Klasifikasi Komentar Di Media Sosial Dengan Menggunakan Algoritma Naïve Bayes
+ [**visualizeChange** by *supersambo*](https://supersambo.shinyapps.io/visualizeChange): #VisualizeChange
+ [**VizAward_HS** by *gfoe2016*](https://gfoe2016.shinyapps.io/VizAward_HS): GfÖ 2016
+ [**VO2sim** by *tenan*](https://tenan.shinyapps.io/VO2sim): VO2sim: A Tool for Visualizing and Quantifying Day-to-Day Measurement Error in Indirect Calorimetry
+ [**voice_random_sampling** by *jcrodriguez*](https://jcrodriguez.shinyapps.io/voice_random_sampling): Random Sampling
+ [**VoronoiInegi** by *conabio*](https://conabio.shinyapps.io/VoronoiInegi): Tianguis de México
+ [**voronoys** by *voronoys*](https://voronoys.shinyapps.io/voronoys): VORONOYS
+ [**vote** by *minecr*](https://minecr.shinyapps.io/vote): Should I vote?
+ [**votr** by *cdermont*](https://cdermont.shinyapps.io/votr): Abstimmungsresultate 1866-2017

## W
+ [**wackywordlist** by *cainesap*](https://cainesap.shinyapps.io/wackywordlist): The WaCky Wordlist
+ [**Wage** by *catwizard*](https://catwizard.shinyapps.io/Wage): Wage Exploration
+ [**Wahlerwartung** by *zweitstimme*](https://zweitstimme.shinyapps.io/Wahlerwartung): Ihre Wahlerwartung
+ [**WaitingForTheEditor** by *jweisber*](https://jweisber.shinyapps.io/WaitingForTheEditor): Waiting for the Editor
+ [**water_network** by *plantmodelling*](https://plantmodelling.shinyapps.io/water_network): Water Tool Network
+ [**waterlevel** by *ttso*](https://ttso.shinyapps.io/waterlevel): Sea water level along the Finnish coastline
+ [**wc18-age** by *mattdray*](https://mattdray.shinyapps.io/wc18-age): How many footballers at World Cup 2018 were younger than you?
+ [**weatherdashboard** by *bigagdata*](https://bigagdata.shinyapps.io/weatherdashboard): Weather dashboard
+ [**web_app** by *asclepiusgal*](https://asclepiusgal.shinyapps.io/web_app): awesome troll filter!
+ [**WebAnalytics-Dashboard** by *mcpasin*](https://mcpasin.shinyapps.io/WebAnalytics-Dashboard): Web Analytics Dashboard with R Shiny
+ [**webapp** by *dirkseidensticker*](https://dirkseidensticker.shinyapps.io/webapp): aDRAC (Archives des datations radiocarbone d'Afrique centrale)
+ [**webappdontrandomize** by *maxkasy*](https://maxkasy.shinyapps.io/webappdontrandomize): Design parameters
+ [**WeightFunctionModel** by *vevealab*](https://vevealab.shinyapps.io/WeightFunctionModel): The Vevea and Hedges Weight-Function Model for Publication Bias
+ [**WelshStudy2** by *lippincott*](https://lippincott.shinyapps.io/WelshStudy2): Welsh ICU 1-year survival data
+ [**wgstogk** by *zkuralt*](https://zkuralt.shinyapps.io/wgstogk): WGStoGK - version 0.8.7
+ [**wham_v1** by *ruggleslab*](https://ruggleslab.shinyapps.io/wham_v1): Workflow Hub for Automated Metagenomic Exploration
+ [**whatsapp_analyser** by *holnburger*](https://holnburger.shinyapps.io/whatsapp_analyser): Whatsapp Analyser
+ [**WhereShouldYouLive** by *derek-corcoran*](https://derek-corcoran.shinyapps.io/WhereShouldYouLive): Where should you live according to your climate preferences?
+ [**whiskyTastingsApp** by *ojessen*](https://ojessen.shinyapps.io/whiskyTastingsApp): Whisky tastings
+ [**whos-at-cogsci** by *nolan*](https://nolan.shinyapps.io/whos-at-cogsci): Who's at CogSci? 2016
+ [**wildfireapp** by *geospatialtraining*](https://geospatialtraining.shinyapps.io/wildfireapp): Visualizing Wildfires in the Western United States
+ [**windapp** by *danbro*](https://danbro.shinyapps.io/windapp): Comparing the Regional Wind Power Potential in Sweden
+ [**winprot20** by *saidee*](https://saidee.shinyapps.io/winprot20): In-game Win Probability Calculator for T20 Matches
+ [**wisdom_database** by *marckissel*](https://marckissel.shinyapps.io/wisdom_database): Search by age
+ [**Word_cloud_generator_wikipedia** by *josearuiperez*](https://josearuiperez.shinyapps.io/Word_cloud_generator_wikipedia): Word Cloud of Wikipedia Terms
+ [**word_psychic** by *melissatan*](https://melissatan.shinyapps.io/word_psychic): word psychic - a coursera capstone project
+ [**wordcloud01** by *rapps*](https://rapps.shinyapps.io/wordcloud01): Word Clouds
+ [**WordcloudExploreR** by *verenahaunschmid*](https://verenahaunschmid.shinyapps.io/WordcloudExploreR): WordcloudExploreR
+ [**WordCloudProject** by *agileanalytics*](https://agileanalytics.shinyapps.io/WordCloudProject): Hearthstone Twitch Chat Clouds for 8 Streamers
+ [**wordmapper** by *wordmapper*](https://wordmapper.shinyapps.io/wordmapper): Word Mapper
+ [**WordSeer_ShinyApp** by *gcampuzano14*](https://gcampuzano14.shinyapps.io/WordSeer_ShinyApp): WordSeer
+ [**wordspace** by *doomlab*](https://doomlab.shinyapps.io/wordspace): Word Space Creator
+ [**work-pals** by *aushsi*](https://aushsi.shinyapps.io/work-pals): Network diagram of investigators
+ [**World_Conflicts** by *andrewrmcneil*](https://andrewrmcneil.shinyapps.io/World_Conflicts): World Conflicts
+ [**world_map** by *bsuthersan*](https://bsuthersan.shinyapps.io/world_map): Annual food consumption (kilograms per person)
+ [**World_Population_Pyramid** by *andrewrmcneil*](https://andrewrmcneil.shinyapps.io/World_Population_Pyramid): World Population
+ [**worldBank** by *mytinyshinys*](https://mytinyshinys.shinyapps.io/worldBank): World Bank
+ [**worldcup** by *cultureofinsight*](https://cultureofinsight.shinyapps.io/worldcup): LES BUTS DE LA COUPE DU MONDE 2018
+ [**WorldCupGoals** by *tylerlewiscook*](https://tylerlewiscook.shinyapps.io/WorldCupGoals): When World Cup Goals Are Scored
+ [**wuenic_analytics** by *unicef*](https://unicef.shinyapps.io/wuenic_analytics): WUENIC Analytics

## Y
+ [**yahoo** by *quantstats*](https://quantstats.shinyapps.io/yahoo): Download Data from Yahoo Finance by Majeed Simaan
+ [**yuimaGUI** by *yuima*](https://yuima.shinyapps.io/yuimaGUI): yuimaGUI

## Z
+ [**zika_cdc_dashboard** by *chendaniely*](https://chendaniely.shinyapps.io/zika_cdc_dashboard): Number of valid data points per country
+ [**ztable** by *cardiomoon*](https://cardiomoon.shinyapps.io/ztable): Demonstration of ztable

## 0
+ [**002-text** by *demo*](https://demo.shinyapps.io/002-text): Shiny Text
+ [**002-text** by *gallery*](https://gallery.shinyapps.io/002-text): Shiny Text
+ [**003-reactivity** by *gallery*](https://gallery.shinyapps.io/003-reactivity): Reactivity
+ [**005-sliders** by *gallery*](https://gallery.shinyapps.io/005-sliders): Sliders
+ [**007-widgets** by *gallery*](https://gallery.shinyapps.io/007-widgets): More Widgets
+ [**009-upload** by *gallery*](https://gallery.shinyapps.io/009-upload): Uploading Files
+ [**00_ClassProject-Submittals** by *modernkris*](https://modernkris.shinyapps.io/00_ClassProject-Submittals): US Storms/Weather Events and Damages
+ [**01-barcelona-incidents-complaints-suggestions** by *marcfresquet*](https://marcfresquet.shinyapps.io/01-barcelona-incidents-complaints-suggestions): Contactes Aj. BCN
+ [**011-timer** by *gallery*](https://gallery.shinyapps.io/011-timer): Timer by RStudio, Inc.
+ [**012-datatables** by *gallery*](https://gallery.shinyapps.io/012-datatables): Examples of DataTables
+ [**013-selectize** by *gallery*](https://gallery.shinyapps.io/013-selectize): Selectize examples
+ [**016-knitr-pdf** by *gallery*](https://gallery.shinyapps.io/016-knitr-pdf): Download a PDF report
+ [**018-datatable-options** by *gallery*](https://gallery.shinyapps.io/018-datatable-options): DataTable Options
+ [**019-mathjax** by *gallery*](https://gallery.shinyapps.io/019-mathjax): MathJax Examples
+ [**02-Vis-Basics** by *tutorials*](https://tutorials.shinyapps.io/02-Vis-Basics): Data Visualization Basics
+ [**021-selectize-plot** by *demo*](https://demo.shinyapps.io/021-selectize-plot): Create plots in selectize input
+ [**021-selectize-plot** by *gallery*](https://gallery.shinyapps.io/021-selectize-plot): Create plots in selectize input
+ [**022-unicode-chinese** by *gallery*](https://gallery.shinyapps.io/022-unicode-chinese): 麻麻再也不用担心我的Shiny应用不能显示中文了
+ [**024-optgroup-selectize** by *gallery*](https://gallery.shinyapps.io/024-optgroup-selectize): Options groups for select(ize) input
+ [**027-absolutely-positioned-panels** by *gallery*](https://gallery.shinyapps.io/027-absolutely-positioned-panels): Absolutely-positioned panels
+ [**029-row-selection** by *demo*](https://demo.shinyapps.io/029-row-selection): Row selection in DataTables
+ [**02_text** by *gallery*](https://gallery.shinyapps.io/02_text): Shiny Text
+ [**030-basic-datatable** by *gallery*](https://gallery.shinyapps.io/030-basic-datatable): Basic DataTable
+ [**032-client-data-and-query-string** by *gallery*](https://gallery.shinyapps.io/032-client-data-and-query-string): Client data and query string example
+ [**035-custom-input-bindings** by *gallery*](https://gallery.shinyapps.io/035-custom-input-bindings): Custom input example
+ [**037-date-and-date-range** by *gallery*](https://gallery.shinyapps.io/037-date-and-date-range): Dates and date ranges
+ [**040-dynamic-clustering** by *gallery*](https://gallery.shinyapps.io/040-dynamic-clustering): Dynamic Clustering in Shiny
+ [**047-image-output** by *gallery*](https://gallery.shinyapps.io/047-image-output): Image output
+ [**050-kmeans-example** by *gallery*](https://gallery.shinyapps.io/050-kmeans-example): Iris k-means clustering
+ [**051-movie-explorer** by *gallery*](https://gallery.shinyapps.io/051-movie-explorer): Movie explorer
+ [**053-navlistpanel-example** by *gallery*](https://gallery.shinyapps.io/053-navlistpanel-example): Navlist panel example
+ [**054-nvd3-line-chart-output** by *gallery*](https://gallery.shinyapps.io/054-nvd3-line-chart-output): JavaScript output binding example
+ [**057-plot-plus-three-columns** by *gallery*](https://gallery.shinyapps.io/057-plot-plus-three-columns): Diamonds Explorer
+ [**058-progress-example** by *gallery*](https://gallery.shinyapps.io/058-progress-example): Progress demo
+ [**061-server-to-client-custom-messages** by *gallery*](https://gallery.shinyapps.io/061-server-to-client-custom-messages): sendCustomMessage example
+ [**064-telephones-by-region** by *gallery*](https://gallery.shinyapps.io/064-telephones-by-region): Telephones by region
+ [**065-update-input-demo** by *gallery*](https://gallery.shinyapps.io/065-update-input-demo): Changing the values of inputs from the server
+ [**066-upload-file** by *gallery*](https://gallery.shinyapps.io/066-upload-file): Uploading Files
+ [**069-widget-check-group** by *gallery*](https://gallery.shinyapps.io/069-widget-check-group): Checkbox group
+ [**072-widget-date-range** by *gallery*](https://gallery.shinyapps.io/072-widget-date-range): Date range
+ [**073-widget-file** by *gallery*](https://gallery.shinyapps.io/073-widget-file): File input
+ [**076-widget-select** by *gallery*](https://gallery.shinyapps.io/076-widget-select): Select box
+ [**077-widget-slider** by *gallery*](https://gallery.shinyapps.io/077-widget-slider): Slider
+ [**082-word-cloud** by *gallery*](https://gallery.shinyapps.io/082-word-cloud): Word Cloud
+ [**084-single-file** by *gallery*](https://gallery.shinyapps.io/084-single-file): Single-file shiny app by RStudio, Inc.
+ [**085-progress** by *gallery*](https://gallery.shinyapps.io/085-progress): Progress bar example by RStudio, Inc.
+ [**086-bus-dashboard** by *gallery*](https://gallery.shinyapps.io/086-bus-dashboard): Twin Cities Buses
+ [**087-crandash** by *gallery*](https://gallery.shinyapps.io/087-crandash): cran.rstudio.com
+ [**094-image-interaction-basic** by *gallery*](https://gallery.shinyapps.io/094-image-interaction-basic): Image interaction - basic by RStudio, Inc.
+ [**095-plot-interaction-advanced** by *gallery*](https://gallery.shinyapps.io/095-plot-interaction-advanced): Points selected by clicking, with nearPoints():

## 1
+ [**110-error-sanitization** by *gallery*](https://gallery.shinyapps.io/110-error-sanitization): Error Sanitization Demo
+ [**113-bookmarking-url** by *gallery*](https://gallery.shinyapps.io/113-bookmarking-url): Bookmarking - URL by Winston Chang
+ [**117-shinythemes** by *gallery*](https://gallery.shinyapps.io/117-shinythemes): shinythemes
+ [**14-ggvis** by *hadley*](https://hadley.shinyapps.io/14-ggvis): 14-ggvis

## 2
+ [**2018-5-Philly-Primary** by *hollander*](https://hollander.shinyapps.io/2018-5-Philly-Primary): 2018 Philly Primary Vote Explorer
+ [**2amconf** by *ttso*](https://ttso.shinyapps.io/2amconf): Scatterplot by School
+ [**2randomize** by *jlsumner*](https://jlsumner.shinyapps.io/2randomize): 2Randomize: A Tool for Large-Scale Randomization in Qualtrics

## 3
+ [**3D_Mapping** by *gallery*](https://gallery.shinyapps.io/3D_Mapping): 3D Network Mapper

## 7
+ [**7State_App** by *es-data*](https://es-data.shinyapps.io/7State_App): Ballotpedia/Evolving Strategies LLC
+ [**_myShinyApp** by *domfernandez*](https://domfernandez.shinyapps.io/_myShinyApp): Dom Fernandez's Shiny World!
